### ISSUE TITLE
Seems like *.d.ts file not being found.

### ISSUE THREAD

**Issue by shrinktofit** [ezolenko/rollup-plugin-typescript2#104]
Here is my code:
```ts
import { Body } from 'cannon';
class CannonCollider extends Body {
    //....
}
```
Hints me that 
```Error: 'Body' is not exported by node_modules\cannon\build\cannon.js```

I have installed  the ```cannon``` and ```@types/cannon```.

Here is my tsconfig:

```json
{
  "compilerOptions": {
    "target": "es6", 
    "module": "es6",
    "strict": true, 
    "moduleResolution": "node",
    "esModuleInterop": true,
  },
  // NO USE:
  // "include": [
  //   "@types/**/*.d.ts",
  //   "./**/*.d.ts",
  //   "./**/*.ts"
  // ],
  "exclude": [
    "node_modules",
  ]
}
```

**Comment by ezolenko** [comment]
Does it work when you run tsc directly, not through rollup?

**Comment by forsigner** [comment]
set `"declaration": true`  in tsconfig.json `compilerOptions`

**Comment by shrinktofit** [comment]
@ezolenko Yes. It works well if I compile it using tsc directly, with same tsconfig.json

**Comment by shrinktofit** [comment]
@forsigner  Not working.

**Comment by shrinktofit** [comment]
I trace the ```transform``` in rollup-plugin-typescript2.cjs.js and capture the result:
transform E:/Tmp/engine-3d/lib/framework/physics/cannon-collider.ts
transform E:\Tmp\engine-3d\node_modules\cannon\build\cannon.js
transform ```a-null-graph``` commonjsHelpers

**Comment by shrinktofit** [comment]
I doubt that rollup-plugin-typescript2 transform my ts files to es6-style first and then ROLLUP it with node_modules\cannon\build\cannon.js, the cannon.js is non-es6 style.

**Comment by ezolenko** [comment]
@shrinktofit could you post your rollup config?

**Comment by shrinktofit** [comment]
Hey @ezolenko , I have resolved this problem by introducing commonjs plugin and do as following:
```
commonjs({
      namedExports: {
          'cannon': ['Body']
      }
    }
```
___________________

My rollup config:

module.exports = {
  input: './source/index.ts',
  external: [],
  plugins: [
    resolve({
      jsnext: true,
      main: true,
      root: process.cwd()
    }),
    commonjs({
      namedExports: {
        'cannon': ['Body']
      }
    }),
    typescript(),
  ],
  output: [
    {
      file: `${outDir}/${file}.dev.js`,
      format: 'iife',
      name,
      banner,
      globals,
      sourcemap,
    },
    {
      file: `${outDir}/${file}.js`,
      format: 'cjs',
      name,
      banner,
      globals,
      sourcemap,
    }
  ],
};
