### ISSUE TITLE
Did not generated declarations file

### ISSUE THREAD

**Issue by onelongblock** [ezolenko/rollup-plugin-typescript2#109]
#### What happens and why it is wrong

I tried a lot of different configuration methods, and no d.ts files were output.

#### Versions
- typescript: 3.0.1
- rollup: 0.17.0
- rollup-plugin-typescript2: 0.17.0

#### tsconfig.json
{
  "include": [
    "src"
  ],
  "exclude": [
    "typings"
  ],
  "compilerOptions": {
    "target": "es5",
    "strict": true,
    "module": "es6",
    "lib": [
      "es6",
      "es7",
      "dom"
    ],
    "declaration": true,
    "declarationDir": "typings"
  }
}

#### rollup-plugin-typescript2 config

{
  verbosity: 3,
  clean: true,
  tsconfig:'tsconfig.json'
}

#### plugin output with verbosity 3

rpt2: typescript version: 3.0.1
rpt2: tslib version: 1.9.3
rpt2: rollup-plugin-typescript2 version: 0.17.0
rpt2: plugin options:
{
    "verbosity": 3,
    "clean": true,
    "tsconfig": "tsconfig.json",
    "check": true,
    "cacheRoot": "/Data/me/weapp-workflow/feu/.rpt2_cache",
    "include": [
        "*.ts+(|x)",
        "**/*.ts+(|x)"
    ],
    "exclude": [
        "*.d.ts",
        "**/*.d.ts"
    ],
    "abortOnError": true,
    "rollupCommonJSResolveHack": false,
    "typescript": "version 3.0.1",
    "useTsconfigDeclarationDir": false,
    "tsconfigOverride": {},
    "transformers": [],
    "tsconfigDefaults": {},
    "objectHashIgnoreUnknownHack": false
}
rpt2: rollup config:
{
    "experimentalCacheExpiry": 10,
    "external": [
        ""
    ],
    "inlineDynamicImports": false,
    "input": "/Data/me/weapp-workflow/feu/src/main.ts",
    "chunkGroupingSize": 5000,
    "perf": false,
    "plugins": [
        {
            "name": "replace"
        },
        {
            "name": "rpt2"
        },
        {
            "name": "buble"
        },
        {}
    ],
    "entry": "/Data/me/weapp-workflow/feu/src/main.ts"
}
rpt2: built-in options overrides: {
    "noEmitHelpers": false,
    "importHelpers": true,
    "noResolve": false,
    "noEmit": false,
    "inlineSourceMap": false,
    "outDir": "/Data/me/weapp-workflow/feu/.rpt2_cache/placeholder",
    "moduleResolution": 2,
    "declarationDir": "/Data/me/weapp-workflow/feu",
    "sourceRoot": null
}
rpt2: parsed tsconfig: {
    "options": {
        "module": 5,
        "target": 1,
        "strict": true,
        "lib": [
            "lib.es2015.d.ts",
            "lib.es2016.d.ts",
            "lib.dom.d.ts"
        ],
        "outDir": "/Data/me/weapp-workflow/feu/.rpt2_cache/placeholder",
        "declaration": true,
        "declarationDir": "/Data/me/weapp-workflow/feu",
        "configFilePath": "/Data/me/weapp-workflow/feu/tsconfig.json",
        "noEmitHelpers": false,
        "importHelpers": true,
        "noResolve": false,
        "noEmit": false,
        "inlineSourceMap": false,
        "moduleResolution": 2,
        "sourceRoot": null
    },
    "fileNames": [
        "/Data/me/weapp-workflow/feu/src/main.ts",
        "/Data/me/weapp-workflow/feu/src/base/EventBus.ts",
        "/Data/me/weapp-workflow/feu/src/base/MQ.ts",
        "/Data/me/weapp-workflow/feu/src/base/debounce.ts",
        "/Data/me/weapp-workflow/feu/src/base/throttle.ts",
        "/Data/me/weapp-workflow/feu/src/base/type.ts",
        "/Data/me/weapp-workflow/feu/src/browser/cookie.ts",
        "/Data/me/weapp-workflow/feu/src/browser/isWeChatBrowser.ts"
    ],
    "typeAcquisition": {
        "enable": false,
        "include": [],
        "exclude": []
    },
    "raw": {
        "compilerOptions": {
            "module": "es6",
            "target": "es5",
            "strict": true,
            "lib": [
                "es6",
                "es7",
                "dom"
            ],
            "outDir": "dist",
            "declaration": true,
            "declarationDir": "dist/typings"
        },
        "include": [
            "src"
        ],
        "exclude": [
            "typings"
        ],
        "compileOnSave": false
    },
    "errors": [],
    "wildcardDirectories": {
        "/Data/me/weapp-workflow/feu/src": 1
    },
    "compileOnSave": false,
    "configFileSpecs": {
        "includeSpecs": [
            "src"
        ],
        "excludeSpecs": [
            "typings"
        ],
        "validatedIncludeSpecs": [
            "src"
        ],
        "validatedExcludeSpecs": [
            "typings"
        ],
        "wildcardDirectories": {
            "/Data/me/weapp-workflow/feu/src": 1
        }
    }
}
rpt2: included:
'[
    "*.ts+(|x)",
    "**/*.ts+(|x)"
]'
rpt2: excluded:
'[
    "*.d.ts",
    "**/*.d.ts"
]'
rpt2: transpiling '/Data/me/weapp-workflow/feu/src/main.ts'
rpt2: generated declarations for '/Data/me/weapp-workflow/feu/src/main.ts'
rpt2: dependency '/Data/me/weapp-workflow/feu/src/base/type.ts'
rpt2:     imported by '/Data/me/weapp-workflow/feu/src/main.ts'
rpt2: resolving './base/type'
rpt2:     to '/Data/me/weapp-workflow/feu/src/base/type.ts'
rpt2: dependency '/Data/me/weapp-workflow/feu/src/base/debounce.ts'
rpt2:     imported by '/Data/me/weapp-workflow/feu/src/main.ts'
rpt2: resolving './base/debounce'
rpt2:     to '/Data/me/weapp-workflow/feu/src/base/debounce.ts'
rpt2: dependency '/Data/me/weapp-workflow/feu/src/base/throttle.ts'
rpt2:     imported by '/Data/me/weapp-workflow/feu/src/main.ts'
rpt2: resolving './base/throttle'
rpt2:     to '/Data/me/weapp-workflow/feu/src/base/throttle.ts'
rpt2: dependency '/Data/me/weapp-workflow/feu/src/base/EventBus.ts'
rpt2:     imported by '/Data/me/weapp-workflow/feu/src/main.ts'
rpt2: resolving './base/EventBus'
rpt2:     to '/Data/me/weapp-workflow/feu/src/base/EventBus.ts'
rpt2: dependency '/Data/me/weapp-workflow/feu/src/browser/cookie.ts'
rpt2:     imported by '/Data/me/weapp-workflow/feu/src/main.ts'
rpt2: resolving './browser/cookie'
rpt2:     to '/Data/me/weapp-workflow/feu/src/browser/cookie.ts'
rpt2: dependency '/Data/me/weapp-workflow/feu/src/browser/isWeChatBrowser.ts'
rpt2:     imported by '/Data/me/weapp-workflow/feu/src/main.ts'
rpt2: resolving './browser/isWeChatBrowser'
rpt2:     to '/Data/me/weapp-workflow/feu/src/browser/isWeChatBrowser.ts'
rpt2: transpiling '/Data/me/weapp-workflow/feu/src/base/type.ts'
rpt2: generated declarations for '/Data/me/weapp-workflow/feu/src/base/type.ts'
rpt2: transpiling '/Data/me/weapp-workflow/feu/src/base/debounce.ts'
rpt2: generated declarations for '/Data/me/weapp-workflow/feu/src/base/debounce.ts'
rpt2: transpiling '/Data/me/weapp-workflow/feu/src/base/throttle.ts'
rpt2: generated declarations for '/Data/me/weapp-workflow/feu/src/base/throttle.ts'
rpt2: transpiling '/Data/me/weapp-workflow/feu/src/base/EventBus.ts'
rpt2: generated declarations for '/Data/me/weapp-workflow/feu/src/base/EventBus.ts'
rpt2: transpiling '/Data/me/weapp-workflow/feu/src/browser/cookie.ts'
rpt2: generated declarations for '/Data/me/weapp-workflow/feu/src/browser/cookie.ts'
rpt2: transpiling '/Data/me/weapp-workflow/feu/src/browser/isWeChatBrowser.ts'
rpt2: generated declarations for '/Data/me/weapp-workflow/feu/src/browser/isWeChatBrowser.ts'
rpt2: dependency '/Data/me/weapp-workflow/feu/src/base/type.ts'
rpt2:     imported by '/Data/me/weapp-workflow/feu/src/browser/cookie.ts'
rpt2: resolving '../base/type'
rpt2:     to '/Data/me/weapp-workflow/feu/src/base/type.ts'
rpt2: generating target 1
rpt2: rolling caches
dist/feu.min.js 3.85kb (gzipped: 1.58kb)

**Comment by mesqueeb** [comment]
@onelongblock I have the same problem! How did you solve it?
PS: please add ``` before and after code blocks for the code-formatting.

**Comment by agilgur5** [comment]
The log shows that declaration files were indeed output and OP closed issue same day, so I'm guessing they just didn't see where the type declarations landed. 

In particular, I noticed they had specified a `declarationDir` in their `tsconfig` but did not use this plugin's `useTsconfigDeclarationDir` option, so they probably did not realize it was in a different directory as a result.
Also confirmed that back when this issue was filed, this option already existed and that [the docs](https://github.com/ezolenko/rollup-plugin-typescript2/tree/0.16.1#some-compiler-options-are-forced) back then already mentioned that `declarationDir` is forced.
