### ISSUE TITLE
can not work with nightly build typescript: yarn add --dev typescript@next

### ISSUE THREAD

**Issue by grayflow** [ezolenko/rollup-plugin-typescript2#117]
#### What happens and why it is wrong
[!] Error: Installed typescript version '3.2.0-dev.20181011' is outside of supported range '>=2.4.0'
#### Versions
- typescript:3.2.0-dev.20181011
- rollup: 0.66.5
- rollup-plugin-typescript2:0.17.1

**Comment by ezolenko** [comment]
Should be fixed in master now, let me know if it works for you

**Comment by grayflow** [comment]
@ezolenko ,
fixed, thanks
