### ISSUE TITLE
just something ironic

### ISSUE THREAD

**Issue by aMarCruz** [ezolenko/rollup-plugin-typescript2#118]
#### Environment 

VSCode on Linux Mint 18.3

#### Versions
- typescript: 3.1.3
- rollup: 0.66.6
- rollup-plugin-typescript2: 0.17.2

#### rollup.config.js

```js
  return rollup({
    input: 'index.ts',
    external,
    plugins: [
      nodeResolve(),
      replacer(),
      typescript(rptsConf),
    ],
  })
    .then((bundle) => bundle.write({
      banner,
      file: 'index.mjs',
      format: 'esm',
      sourcemap: true,
    }))
    .then(() => {
      if (pkgJson.browser) {
        console.log(`Packing ${pkgJson.browser}...`)
        return makeBrowser(pkgJson, srcPath, camelize(folder))
      }
      return Promise.resolve()
    })
```

#### tsconfig.json

```json
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "declaration": false,
    "declarationMap": false,
    "module": "es6",
    "target": "es6"
  },
  "files": [
    "dummy.ts",
  ],
  "include": [
  ],
}
```

#### package.json

n/a

#### plugin output with verbosity 3

It's not really a problem, it's just something ironic and a little annoying:

![image](https://user-images.githubusercontent.com/6636980/47785402-3972d200-dcce-11e8-943c-c533089db0ab.png)

This is part of the code that runs rollup in a monorepo, it's in a folder ("scripts") with ~23 JS files, all with a "@ts-check" directive, and this is the only one that shows a typing error ...in the typescript plugin :smirk:

Anyway, this plugin is awesome!

**Comment by ezolenko** [comment]
Ha, no that should work. You might want to do `import ts from "rollup-plugin-typescript2";` or `import ts from "<path>/rollup-plugin-typescript2.es"` if you need to give it full path, not `import "<path>/index"`.

**Comment by ezolenko** [comment]
![image](https://user-images.githubusercontent.com/1617834/47806114-925a5e80-dcfe-11e8-9616-9af39edfc883.png)

**Comment by aMarCruz** [comment]
@ezolenko yeah I know, but this code runs on node 8 and I don't wanna add transpilation to this tools.
Simple workaround was:

```js
/** @type {any} */
const typescript = require('rollup-plugin-typescript2')
```
Closing this. Thanks!

**Comment by ezolenko** [comment]
There is also cjs version if that helps `import ts from "<path>/rollup-plugin-typescript2.cjs"`

**Comment by aMarCruz** [comment]
@ezolenko that also works but, like with the other solutions, it loose the typings.

Just I'm writing an isomorphic library and seems the solution is a traditional `export = `. With this and `allowSyntheticDefaultImports`, typings are visible even in the above case (JS with node CJS `require`s) and with `esModuleInterop` there's no issues with the import.

After this change:
```
export = function typescript(options?: Partial<IOptions>): {
```

...this is the result (you can see here the CJS require):

![image](https://user-images.githubusercontent.com/6636980/47816436-ca6e9b00-dd18-11e8-8acd-c4b0befaef1a.png)

The `export =` syntax in "*.d.ts" looks more correct to me, since TS ignores the package.json's "module" and always loads from the file pointed by "main".

In my lib, I have the files of each module in the same folder, like this:
```
index.d.ts
index.d.ts.map
index.js      <== CJS version without interop, transpilled to ES5, addressed by the "main" property
               of package.json. It is the one (always) loaded by TS and JS w/CJS requires.

index.mjs.map
index.mjs   <== unstranspilled ES6 version with ES modules, loaded by node w/experimental
             ES modules support, and by Rollup/Webpack through the "module" property.

index.b.min.js   <== transpilled IIFE for browsers, autoload, addressed by the "browser" prop.
```

Right now, this setup is wotking fine, the "bad" is I need to swap the tsconfig (with your plugin is easy) and replace the "export=" of the *.ts files with "default export" or "export {" with another specialized plugin.

:)
