### ISSUE TITLE
What dose this file 'rpt2_cache' do

### ISSUE THREAD

**Issue by Yangfan2016** [ezolenko/rollup-plugin-typescript2#119]
#### Versions
- typescript:3.1.5
- rollup:0.66.6
- rollup-plugin-typescript2:0.17.2

**Comment by ezolenko** [comment]
It's a folder with cache of transpilation results, to speed up following builds if nothing changes. See `cacheRoot` and `clean` options in readme to control it.

**Comment by Yangfan2016** [comment]
Tnx
