### ISSUE TITLE
parse release candidate versions of typescript

### ISSUE THREAD

**Issue by AWCostabile** [ezolenko/rollup-plugin-typescript2#121]
#### What happens and why it is wrong
Typescript `3.2.0-rc` is being identified as `outside of supported range '>=2.4.0'`.

#### Versions
- typescript: `3.2.0-rc`
- rollup: `0.66.6`
- rollup-plugin-typescript2: `0.17.1`

**Comment by AWCostabile** [comment]
nevermind me.. I just realised my version was out of date and therefore this is irrelevant.

**Comment by agilgur5** [comment]
Duplicate of #117
