### ISSUE TITLE
paths remapping is not done for type declarations

### ISSUE THREAD

**Issue by michaeldzjap** [ezolenko/rollup-plugin-typescript2#125]
Is it possible to use this plugin together with _rollup-plugin-alias_ to replace mapped paths with their "true" paths and if not, would you have a recommendation for a plugin which could do that? I found [this](https://github.com/ezolenko/rollup-plugin-typescript2/issues/65). But unfortunately it doesn't resolve my problem or answers my question.

What I am trying to do; I am trying to replace the mapped paths / path aliases (i.e. `@src`) with the correct path in the transpiled type files. I've tried with the setup below and everything compiles fine. However, my type declaration files that contain a reference to a mapped path are not replaced. So to give an example, I have a `Callable.d.ts` file after transpilation that looks like

```typescript
import { Instantiable, Instance } from '@src/Support/types';
declare class Callable<T> {
    private _target;
    private _method?;
    private _isStatic;
    constructor(target: Instantiable<T> | Instance<T>, method?: string, isStatic?: boolean);
    readonly target: Instantiable<T> | Instance<T>;
    readonly method: string | undefined;
    readonly isStatic: boolean;
    asArray(): [Instantiable<T> | Instance<T>, string | undefined, boolean];
    call(args: any[]): any;
}
export default Callable;
```

instead of

```typescript
import { Instantiable, Instance } from '../Support/types';
declare class Callable<T> {
    private _target;
    private _method?;
    private _isStatic;
    constructor(target: Instantiable<T> | Instance<T>, method?: string, isStatic?: boolean);
    readonly target: Instantiable<T> | Instance<T>;
    readonly method: string | undefined;
    readonly isStatic: boolean;
    asArray(): [Instantiable<T> | Instance<T>, string | undefined, boolean];
    call(args: any[]): any;
}
export default Callable;
```

My _tsconfig.json_, _rollup.config.js_ files and _src_ folder are located at the same (top) level.

#### Versions
- typescript: 3.2.2
- rollup: 0.68.0
- rollup-plugin-typescript2: 0.18.1

#### rollup.config.js

```javascript
import path from 'path';
import resolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';
import alias from 'rollup-plugin-alias';
import sourceMaps from 'rollup-plugin-sourcemaps';
import typescript from 'rollup-plugin-typescript2';
import {eslint} from 'rollup-plugin-eslint';
import {terser} from 'rollup-plugin-terser';
import pkg from './package.json';

export default {
    input: 'src/index.ts',
    output: {file: pkg.module, format: 'es', sourcemap: true},
    external: [
        ...Object.keys(pkg.dependencies || {}),
        ...Object.keys(pkg.peerDependencies || {}),
    ],
    watch: {
        include: 'src/**'
    },
    plugins: [
        eslint(),
        resolve(),
        commonjs(),
        alias({
            resolve: ['.ts'],
            '@src': path.resolve(__dirname, './src')
        }),
        typescript({
            typescript: require('typescript'),
            rollupCommonJSResolveHack: true
        }),
        sourceMaps(),
        terser()
    ]
};
```

#### tsconfig.json

```json
{
    "compilerOptions": {
        "baseUrl": ".",
        "paths": {
            "@src/*": ["src/*"]
        },
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "moduleResolution": "node",
        "target": "es6",
        "module": "es6",
        "lib": ["es5", "es6", "es7", "dom"],
        "removeComments": true,
        "strict": true,
        "sourceMap": true,
        "declaration": true,
        "declarationDir": "./dist",
        "outDir": "./dist",
        "suppressImplicitAnyIndexErrors": true
    },
    "include": [
        "src/**/*"
    ],
    "exclude": [
        "node_modules",
        "dist"
    ]
}
```

**Comment by ezolenko** [comment]
Looks like this should work without `rollup-plugin-alias` at all. Did you try that? What ends up in the transpiled js?

Somewhat related #112

**Comment by ezolenko** [comment]
Looks like this is a typescript problem, paths feature is not quite complete(?), see https://github.com/Microsoft/TypeScript/issues/16088 and https://github.com/Microsoft/TypeScript/issues/27218.

Try removing `baseUrl` and `paths` from tsconfig and instead do all remapping with `rollup-plugin-alias`, so that paths are expanded by the time typescript sees them. This might break intellisense in your IDE though.

**Comment by iliyaZelenko** [comment]
I have the same problem. [My package with issue](https://github.com/iliyaZelenko/tiptap-vuetify/issues/1).

How to make path in `.d.ts` relative?

I also tried `@zerollup/ts-transform-paths` package but I have a [error there](https://github.com/zerkalica/zerollup/issues/11).

**Comment by josketres** [comment]
I could do the paths remapping with `@zerollup/ts-transform-paths` 

https://github.com/zerkalica/zerollup/issues/11

@iliyaZelenko thanks for the hint!

**Comment by viT-1** [comment]
Another way is try to configure rollup-plugin-typescript2 with typescript: [ttypescript](https://github.com/cevek/ttypescript) and tsconfig.json > compilerOptions > `"plugins": [{ "transform": "typescript-transform-paths" }]`

**Comment by developer239** [comment]
```
// tsconfig.build.ts

// ...
"moduleResolution": "node",
"plugins": [
  {
    "transform": "@zerollup/ts-transform-paths",
    "exclude": ["*"]
  }
]
// ...
```

```
// rollup.config.js

/* eslint-disable import/no-default-export */
import cleaner from 'rollup-plugin-cleaner'
import typescript from 'rollup-plugin-typescript2'
import ttypescript from 'ttypescript'

export default {
  input: `./src/index.ts`,
  output: [
    { file: 'lib/index.js' },
  ],
  plugins: [
    cleaner({
      targets: ['./lib'],
    }),
    typescript({
      tsconfig: 'tsconfig.build.json',
      typescript: ttypescript
    }),
  ],
}
```

**Comment by agilgur5** [comment]
Going to mark this as duplicate of #201.
While this issue came first, that one has had a lot more activity, workarounds, etc, so better to continue any discussions there.
