### ISSUE TITLE
Move cache directory to `node_modules`

### ISSUE THREAD

**Issue by znck** [ezolenko/rollup-plugin-typescript2#133]
It's common practice to use `node_modules/.cache/[namespace]` as cache directory. 

Benefits of having a cache directory in `node_modules`:

1. No need to update `.gitignore` as `node_modules` is always ignored.
2. It invisible to users.

**Comment by ezolenko** [comment]
Sounds reasonable, looks like some of the cool kids are using it, but it looks like there are objections?
https://github.com/avajs/find-cache-dir/issues/1
https://github.com/facebook/jest/pull/2303

**Comment by ezolenko** [comment]
Can be overriden with `cacheRoot` option, but at that point user is already involved and both benefits are moot.

**Comment by znck** [comment]
What I'm suggesting is an invisible cache directory, which exists but you don't care about it.

**Comment by ForsakenHarmony** [comment]
We're doing this in microbundle now
