### ISSUE TITLE
Generate library with .ts and .js together

### ISSUE THREAD

**Issue by IvanRodriCalleja** [ezolenko/rollup-plugin-typescript2#134]
Hi,

I am not totally sure if this bug is from this plugin.

#### What happens and why it is wrong

I am trying to package a library using .ts and .js files at same time, the entry file is a .ts file and this file make a require to a .js file (It is because this files are generated because the base project is made with reasonML and i want to generate the library for multiple languages). The problem is that the output is not valid to consume, this output has require to files that don't exist in this directory. I don`t know if it is possible to bundle .js and .ts together with this plugin.

I have created a [repository](https://github.com/IvanRodriCalleja/rollup-plugin-typescript2-bug) with the example i am talking about

What an i doing wrong?

**Comment by ezolenko** [comment]
To change require to imports you might need to set your generator to produce ES6 modules -- this is what rollup expects.

**Comment by n2k3s2it** [comment]
I think I want to do the same as OP. I've set `allowJs` to true in `tsconfig.json`. And when running regular `tsc` the .js files show up in the outputDir. But when running `rollup -c`, the code isn't included in my `main.js` file (see `rollup.config.js` below).

I've tried setting the `include` property inside the `typescript()`, with the value
```
[
    "*.ts+(|x)",
    "**/*.ts+(|x)",
    "./<pathToJsFile>"
]
```
which will directly reference the .js files that need to be included. But this still doesn't result in the code of the .js file to be included in my `main.js` file.

What am I doing wrong?

`rollup.config.js` contents:
``` javascript
import resolve from 'rollup-plugin-node-resolve';
import typescript from 'rollup-plugin-typescript2';

export default
{
   input: './application.ts',
   output: [
       {
           file: './dist/main.js',
           format: 'cjs'
       },
   ],

   plugins: [
       resolve(),
       typescript()
   ]
}
```

**Comment by ezolenko** [comment]
@n2k3s2it check if anything from those js files is actually used, rollup will treeshake imports that are not needed.

**Comment by n2k3s2it** [comment]
@ezolenko I might be missing something, but AFAIK I am. I'm using `declare let JsLibraryThatIsNotAModule: any;` and then use the JavaScript code in my TypeScript class. This is probably just satisfying the TS compiler, without actually referencing to a .js file where it can find the code. This probably is not correct way, is there a better alternative?

**Comment by ezolenko** [comment]
Yeah, if you are not actually importing the file, ts will think it is supposed to be provided by environment somehow. Rollup will never see that file because nothing ever runs `import` on it. You have to turn that ls library into module for rollup to pick it up I think. Or maybe specify it as one of inputs in rollup config.

**Comment by agilgur5** [comment]
Closing as this should already be possible (may require more configuration though, like `allowJs` and [setting this plugin's `include`](https://github.com/ezolenko/rollup-plugin-typescript2#plugin-options)) and because this issue never received a response from OP and has not had activity in a few years.
