### ISSUE TITLE
How can I prolyfill Array.from or Set ... ?

### ISSUE THREAD

**Issue by kungfuboy** [ezolenko/rollup-plugin-typescript2#138]
#### What happens and why it is wrong
I don 't kown how to tansform Array.from or Set or something like that.
#### Environment 

iMac

#### Versions
- typescript: ^3.2.4
- rollup: ^1.1.2
- rollup-plugin-typescript2: ^0.19.2

#### rollup.config.js
```
import typescript from 'rollup-plugin-typescript2'

export default {
  input: 'src/index.ts',
  output: [
    {
      file: 'dist/index.js',
      format: 'es',
    },
  ],
  plugins: [
    typescript()
  ],
}
```

#### tsconfig.json
```
{
    "compilerOptions": {
        "moduleResolution": "node",
        "declaration": true,
        "target": "es5",
        "module": "es6",
        "outDir": "./dist/",
        "strict": true,
        "esModuleInterop": true,
        "experimentalDecorators": true
    }
}
```

#### package.json
```
{
  "name": "foo",
  "version": "1.0.1",
  "main": "dist/index.js",
  "license": "MIT",
  "scripts": {
    "build": "rollup -cw"
  },
  "dependencies": {
    "typescript": "^3.2.4"
  },
  "devDependencies": {
    "@types/node": "^11.9.4",
    "rollup": "^1.1.2",
    "rollup-plugin-typescript2": "^0.19.2"
  }
}
```

#### input
```
// index.ts
function foo(arr:number[]):number[] {
    return Array.from(new Set(arr))
}
console.log(foo([1, 4, 2, 3, 4]))
```
#### output
```
function foo(arr) {
    return Array.from(new Set(arr));
}
console.log(foo([1, 4, 2, 3, 4]));

```

So, how can I add prolyfill and transform from Array.form() to real es5 code ? Thanks.

**Comment by ezolenko** [comment]
Generally you will need to hook up babel for language transformations: https://github.com/rollup/rollup-plugin-babel

**Comment by agilgur5** [comment]
See https://github.com/ezolenko/rollup-plugin-typescript2/issues/115#issuecomment-1124279783 for more details on how one might go about polyfilling.

This effectively duplicates that issue
