### ISSUE TITLE
Add support for project references

### ISSUE THREAD

**Issue by thdk** [ezolenko/rollup-plugin-typescript2#139]
#### What happens and why it is wrong
Since typescript 3.0, typescript has added support for project references.
`tsc -b` now build all projects listed in references section of the main tsconfig before the main project is built. See [typescript documentation](https://www.typescriptlang.org/docs/handbook/project-references.html) for project references.

When using rollup-plugin-typescript2, the references projects are not being build at all. It only builds the current project.

#### Versions
- typescript: 3.2.2
- rollup: 1.1.2
- rollup-plugin-typescript2: 0.19.2

#### rollup.config.js

Not relevant

#### tsconfig.json

Main project:
```
{
  "compilerOptions": {
    "target": "es6",
    "module": "es2015", 
    "lib": [
      "es2015",
      "dom"
    ],
},
  "references": [
    {
      "path": "./common"
    }
  ]
}
```
Common project

```
{
  "compilerOptions": {
    /* Basic Options */
    "target": "es5",
    "module": "es2015",
    "declaration": true,
    "declarationMap": false,
    "outDir": "dist",
    "rootDir": ".",
    "composite": true,
    "strict": true, 
     "moduleResolution": "node", 
    "esModuleInterop": true
  },
  "references": []  // * Any project that is referenced must itself have a `references` array (which may be empty).
}
```

#### package.json

Not relevant

#### plugin output with verbosity 3

Not relevant

**Comment by ezolenko** [comment]
Also related to #112

**Comment by rosskevin** [comment]
I just made a big effort to get to rollup/bundle based output on our internal projects (instead of exploded output) and ran into this.  Is there any guidance on where the gap is to get project references supported?  I'd like to help but unsure if it will take me a lot of time to ramp up on this plugin or rollup internals.

**Comment by ezolenko** [comment]
@rosskevin I haven't looked at what would be involved, with any luck changes should be fairly limited (unless complicated by decisions like if projects should be all rolled into one bundle or split up, etc). 

If you can make a small example repo that is using project references that will help a lot.

**Comment by thdk** [comment]
I had made a very small repo to try out project references with typescript and now I've added a new branch with rollup configured to bundle the typescript files using rollup-plugin-typescript2.

https://github.com/thdk/TS3-projects-references-example/tree/es-rollup-typescript

Would that be of any help?

**Comment by rosskevin** [comment]
@thdk you aren't using `composite` according to the reference docs, not sure how that impacts things.

@ezolenko Here is a repo setup based on Ryan Cavanaugh's original sample with project references according to https://www.typescriptlang.org/docs/handbook/project-references.html:
https://github.com/rosskevin/learn-a/tree/build-rollup

It is also setup in a common lerna monorepo structure using yarn workspaces.  Currently `bundle` seems to and only warns on `rpt2: config error TS18002 The 'files' list in config file '/Users/kross/projects/learn-a/tsconfig.json' is empty.`

I'll try this now in my more complex internal repo and see if there are more complications.

**Comment by rosskevin** [comment]
So it appears that with the same setup from the `learn-a` sample above run in a more complex internal project, that rpt2 stops using the inherited tsconfig settings.  

For example, rpt2 yields:
```
semantic error TS1192 Module '"/Users/kross/projects/js/node_modules/@types/lodash/merge"' has no default export.
```

 which is solved with and part of my base tsconfig: `esModuleInterop/allowSyntheticDefaultImports`.

Is tsconfig extension (I have two levels of extension) unsupported?

**Comment by thdk** [comment]
@rosskevin composite need to be set only for the referenced projects

> "Referenced projects must have the new composite setting enabled."

[https://www.typescriptlang.org/docs/handbook/project-references.html](https://www.typescriptlang.org/docs/handbook/project-references.html)

Note that my repo only contains a very simple example using only typescript files with no other dependencies in the referenced projects. I'll try to add some more complexity to allow to test more features of rollup-plugin-typescript2 with project references.

**Comment by ezolenko** [comment]
@thdk I made both examples in TS3-projects-references-example work, for project-b you'll need to build common-with-dist before running rollup though.

**Comment by ezolenko** [comment]
@rosskevin tsconfig extension should work, but there might be bugs propagating the options. Try increasing plugin verbosity to 4 and check if the option shows up in parsed tsconfig (look for `rpt2: parsed tsconfig: {` line).

**Comment by thdk** [comment]
@ezolenko I know it works when I build project common-with-dist before running rollup, but coudn't the common project be detected and be build when required?

**Comment by ezolenko** [comment]
@thdk Maybe it could, but it feels like an overreach to launch independent tsc compilations from rollup. Workaround for now is to add referenced project build step as a dependency or a pre-build in whatever build system starts rollup itself. Or to use direct imports like in `project-a`.

**Comment by ezolenko** [comment]
Partial support is in 0.20.0 now.

**Comment by dtassone** [comment]
> Partial support is in 0.20.0 now.

What does it mean partial? I'm trying to use this feature in a monorepo and I don't get my referenced package rebuilt when I add the option in the plugin conf or in my tsconfig...
```
    typescript({ build: true }),
```
```
...
  "compilerOptions": {
    "declaration": true,
    "declarationDir": "./dist",
    "module": "es6",
    "noImplicitAny": true,
    "strict": true,
    "outDir": "./dist",
    "target": "es6",
    "sourceMap": true,
    "build": true
  },
```
Composite flag is on in my referenced package and running `tsc --build` works as expected

Am I missing something?
