### ISSUE TITLE
Imported helper support requires "moduleResolution": "node" in tsconfig

### ISSUE THREAD

**Issue by ezolenko** [ezolenko/rollup-plugin-typescript2#14]
Otherwise typescript can't find tslib in local node_modules. (see #12)

Running `tsc` without that option works, so there must be a better way of finding tslib than using `require.resolve`.

**Comment by ezolenko** [comment]
https://github.com/Microsoft/TypeScript/issues/14468
https://github.com/s-panferov/awesome-typescript-loader/issues/250

**Comment by vardius** [comment]
Any solutions for this one ?

**Comment by ezolenko** [comment]
That shouldn't happen... Did you set tslib as an external dependency in rollup config?

What's you rollup / typescript versions and what does top of your transpiled bundle look like? Does it have import/require tslib?

**Comment by vardius** [comment]
I have `var tslib_1 = require("tslib");`

Versions:
```json
    "rollup": "^0.43.0",
    "tslib": "^1.7.1",
    "tslint": "^5.4.3",
    "typescript": "^2.4.1"
```

and my config is:
```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "rootDir": "src",
    "outDir": ".code",
    "newLine": "LF",
    "lib": [
      "es2015",
      "es2016",
      "es2017",
      "dom",
      "scripthost"
    ],
    "moduleResolution": "node",
    "importHelpers": true,
    "declaration": true,
    "pretty": true,
    "sourceMap": true,
    "inlineSources": true,
    "noUnusedLocals": true,
    "skipLibCheck": true
  },
  "include": [
    "src/**/*"
  ],
  "exclude": [
    "node_modules",
    "**/*.spec.ts",
    "dist",
    "es",
    "lib"
  ]
}
```

**Comment by ezolenko** [comment]
What your rollup config look like?

Also, try with `"rollup-plugin-typescript2": "github:ezolenko/rollup-plugin-typescript2#master"` instead of 0.4.4 -- I just (hopefully) fixed a bug related to typescript 2.4.1.

**Comment by vardius** [comment]
```json
  moduleName: pascalCase(pkg.name),
  entry: "src/index.ts",
  dest: "dist/bundle.js",
  format: "umd",
  exports: "named",
  sourceMap: true,
  plugins: [
    typescript(),
    sourcemaps(),
    resolve({
      jsnext: true,
      browser: true
    }),
    commonjs(),
    globals(),
    builtins(),
    uglify()
  ]
```

**Comment by ezolenko** [comment]
Could you run the build with `typescript({ clean: true, verbosity: 3 }),` (on master branch) and post the output?

Also post your package config (the part with all the rollup plugins).

It is possible one of those plugins clobbers tslib resolution and it doesn't get replaced by this plugin...

**Comment by vardius** [comment]
With the master branch it does work. Could you release it ?

**Comment by ezolenko** [comment]
Cool, I'll release later today.

**Comment by ezolenko** [comment]
Back to original bug, reading [typescript documentation](https://www.typescriptlang.org/docs/handbook/module-resolution.html) it seems `classic`  resolution is mostly for backwards compatibility anyway, so closing as won't fix.
