### ISSUE TITLE
Invalid triple-slash reference after build

### ISSUE THREAD

**Issue by f1cognite** [ezolenko/rollup-plugin-typescript2#140]
#### What happens and why it is wrong
After a build using [triple-slash references](https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html) the reference-path is invalid in the build-folder.

The path in the `reference` in the generated declaration file is invalid.

#### Environment 

I have created a repository to explain & reproduce the problem: https://github.com/f1cognite/typescript-reference-problem/

#### Versions
- typescript: 3.1.6
- rollup: 0.67.0
- rollup-plugin-typescript2: 0.17.2

#### rollup.config.js
```js
import typescript from 'rollup-plugin-typescript2';
import pkg from './package.json';

export default {
  input: 'src/index.ts',
  output: [
    {
      file: pkg.main,
      format: 'es',
    },
  ],
  external: [
    ...Object.keys(pkg.dependencies || {}),
    ...Object.keys(pkg.peerDependencies || {}),
  ],
  plugins: [
    typescript({
      typescript: require('typescript'),
      clean: true,
    }),
  ],
};
```

#### tsconfig.json

```json
{
  "compilerOptions": {
    "module": "es6",
    "target": "es5",
    "declaration": true,
    "declarationDir": "dist",
    "outDir": "dist",
    "moduleResolution": "node"
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules"]
}
```

#### package.json
```json
{
  "name": "typescrtipt-reference-problem",
  "private": true,
  "version": "0.0.0",
  "main": "dist/index.js",
  "types": "dist/index.d.ts",
  "devDependencies": {
    "rollup": "^0.67.0",
    "rollup-plugin-typescript2": "^0.17.2",
    "typescript": "^3.1.6"
  },
  "scripts": {
    "clean": "rm -rf dist",
    "build": "yarn clean && rollup -c"
  }
}
```

#### plugin output with verbosity 3

Not relevant

**Comment by ezolenko** [comment]
Try using `useTsconfigDeclarationDir: true` plugin option.

**Comment by ezolenko** [comment]
Another option is to remove reference completely (typescript will still find the types) and make sure they are copied into dist (or published separately so that consumer of your package has to install both your package and those types)

**Comment by f1cognite** [comment]
`useTsconfigDeclarationDir: true` didn't work as expected since it is then referring to my `src/` folder.

It tried your second solution and it seemed fine at first (didn't complain anything when I opened files in `./src/`) but when I build it and tried to open up files in my `./dist` folder it complained. Even after I copied the `d.ts`-file into `./dist`.

**Comment by ezolenko** [comment]
I don't think there is a good way to do it without making your generated types a proper module. 

To workaround, try disabling `useTsconfigDeclarationDir`, moving types out of `src` dir, updating references and copying types into `dist` as part of the build process.
