### ISSUE TITLE
npm audit vulnerability (v0.19.3)

### ISSUE THREAD

**Issue by OG84** [ezolenko/rollup-plugin-typescript2#141]
Please update `rollup-pluginutils`.
The current version seems to have a vulnerability.

Thx 👍 

![image](https://user-images.githubusercontent.com/5689965/53645747-d96b4880-3c39-11e9-99d8-6abb7e9b81d9.png)

**Comment by vpzomtrrfrt** [comment]
Why is this closed?  I'm seeing this issue

**Comment by OG84** [comment]
yeah i wasnt sure if this issue should be addressed here or rather in rollup-pluginutils.
But i can reopen :)

**Comment by ezolenko** [comment]
rollup-pluginutils is updated to `2.4.1` in 0.20.0
