### ISSUE TITLE
"Error: Entry module cannot be external" in version 0.20.0

### ISSUE THREAD

**Issue by jansiegel** [ezolenko/rollup-plugin-typescript2#144]
#### What happens and why it is wrong
The build won't go through, throws the following error:
`Error: Entry module cannot be external`

This seems to be caused by a change here: https://github.com/ezolenko/rollup-plugin-typescript2/commit/29b13a089b6a1a86574255779277d1e06414f557#diff-f41e9d04a45c83f3b6f6e630f10117feR118

#### Environment 
Checked in a setup like this:

`index.ts`:
```typescript
export * from './index2';
```
`index2.ts`:
```
// doesn't matter
```

#### Versions
- typescript: 3.3.3333
- rollup: 1.6.0
- rollup-plugin-typescript2: 0.20.0

#### rollup.config.js

```javascript
import typescript from 'rollup-plugin-typescript2';

export default {
  input: './index.ts',
  output: {
    format: 'cjs',
    file: './dist/build.js',
  },
  plugins: [
    typescript()
  ]
}
```

**Comment by mesqueeb** [comment]
I have the same problem. `0.20.0` breaks my build because of this!
I'm stuck on `0.19.0` 😜

**Comment by diuis** [comment]
Same problem with esm format

**Comment by nerdmax** [comment]
Exact the same problem with all my projects with rollup-plugin-typescript2.

**Comment by zheeeng** [comment]
Same problem breaks building

**Comment by xSNOWM4Nx** [comment]
Same problem here with Version 0.20.0

**Comment by lazarljubenovic** [comment]
I Googled this like crazy two days ago and gave up. Apparently I'm not crazy! Yay! :tada:

**Comment by ezolenko** [comment]
Ugh, I should have actually read the docs... Try now with 0.20.1

**Comment by diuis** [comment]
0.20.1 works: @jansiegel @ezolenko is it posible to close the issue?

**Comment by dangreen** [comment]
some problem with `rollup-plugin-commonjs@10.0.0`
