### ISSUE TITLE
Merge declarations

### ISSUE THREAD

**Issue by ranquild** [ezolenko/rollup-plugin-typescript2#145]
#### What happens and why it is wrong
When setting `"declarations": true` in `tsconfig.json`, plugin outputs multiple `.d.ts` files, however I would like to have bundled`index.d.ts` file in published package as source code is.

#### Versions
- typescript: 3.3.3333
- rollup: 1.6.0
- rollup-plugin-typescript2: 0.20.1

**Comment by ezolenko** [comment]
There is a separate tool for that: https://github.com/SitePen/dts-generator, you can hook it up as a postprocessing step in package.json or something.

I don't think there is a way for rpt2 to hook up to typescript's own way of doing that.

**Comment by ranquild** [comment]
Thanks, it works for me!
