### ISSUE TITLE
type declaration can't be shipped into the dist folder

### ISSUE THREAD

**Issue by zzzgit** [ezolenko/rollup-plugin-typescript2#149]
#### Versions
- typescript: newest
- rollup: newest
- rollup-plugin-typescript2: newest

#### repository
https://github.com/zzzgit/sample

#### problem
1. when using `tsc` command to compile the project, it works fine
2. when using `npm run build` to compile it, declaration files won't be bundled to the `dist` folder

I can't find the cause to this problem.

**Comment by ezolenko** [comment]
You don't seem to be using this plugin? (looking at your sample repo)

**Comment by zzzgit** [comment]
@ezolenko sorry, I failed to commit. I will commit again this morning

**Comment by zzzgit** [comment]
Yes, now I have pulled it again

**Comment by zzzgit** [comment]
Who can help me?

**Comment by ezolenko** [comment]
Works for me, I see all d.ts files in `built/t` folder (as specified in tsconfig)

**Comment by zzzgit** [comment]
![image](https://user-images.githubusercontent.com/1060733/57496322-e6c14500-7304-11e9-9f62-0500f9f77b35.png)


![image](https://user-images.githubusercontent.com/1060733/57496338-fc366f00-7304-11e9-9845-2125957157d5.png)

Only a index.js file here.

**Comment by ezolenko** [comment]
Could you add `verbose: 3` option and attach the output?

**Comment by zzzgit** [comment]
The cause is that I only installed rollup globally, but not locally.
