### ISSUE TITLE
Problem with module augmentation.

### ISSUE THREAD

**Issue by ypopovych** [ezolenko/rollup-plugin-typescript2#152]
Hi,

I tried to use this plugin for my library. It works well except for one strange bug.
Somehow it can't see TS module augmentation from a library in "node_modules" folder.

My library sources: https://github.com/tesseract-one/Tesseract.js

How to reproduce:
1. Export class from one library (in my case it's `TesseractModule` from `packages/core/src/index.ts`)
2. Add an extension to this class in another library (in my case it's `OpenWallet` property, declared in `packages/openwallet/src/index.ts`)
3. Use this extension in the third library (it's used in `packages/ethereum-web3/src/index.ts`)

I'm using `lerna` in my library, so `npm run bootstrap` should be called for bootstrapping, and then `npm run build` for building.

Compilation with `tsc` works fine.

If I will copy extension declaration from the second library into the third library - it will work fine too. 

#### Versions
- typescript: 3.5.1
- rollup: 1.14.3
- rollup-plugin-typescript2: 0.21.1

**Comment by ezolenko** [comment]
You might need to use `rollup-plugin-node-resolve` and `rollup-plugin-commonjs` before `rollup-plugin-typescript2`. First one finds node modules for rollup, second one makes them CJS modules into ES modules.

**Comment by ypopovych** [comment]
All three libraries are mine, and they are es6 modules and generated from ts (with rollup). Seems as it can  find dependencies, but somehow ignoring `declare module` inside one of them

**Comment by ypopovych** [comment]
I think I can show some examples stripped from libs.

The first library(class declaration)
```typescript
export class TesseractModule {
    static addPlugin<T>(prop: string, factory: (TesseractModule) => T) {/*implementation*/}
}
```

Second library(extension)
```typescript
import { TesseractModule } from '@tesseract/core'

declare module '@tesseract/core' {
  interface TesseractModule {
    OpenWallet: OpenWallet
  }
}
TesseractModule.addPlugin('OpenWallet', () => new OpenWallet())
```

Third library
```typescript
import { TesseractModule } from '@tesseract/core'
import { OpenWallet } from '@tesseract/openwallet'

declare module '@tesseract/core' {
  interface TesseractModule {
    Ethereum: Ethereum
  }
}

// It shows error in this line. Can't find OpenWallet property into TesseractModule, which defined in '@tesseract/openwallet'
TesseractModule.addPlugin('Ethereum', (tes) => new Ethereum(tes.OpenWallet))
```

**Comment by ezolenko** [comment]
You still need `rollup-plugin-node-resolve` though, since you import modules from `node_modules`.

What are the errors rollup produces?

**Comment by ypopovych** [comment]
```[!] (rpt2 plugin) Error: /Users/yehor/Documents/Tesseract/Tesseract.js/packages/ethereum-web3/src/index.ts(13,33): semantic error TS2339: Property 'OpenWallet' does not exist on type 'TesseractModule'.
src/index.ts
Error: /Users/yehor/Documents/Tesseract/Tesseract.js/packages/ethereum-web3/src/index.ts(13,33): semantic error TS2339: Property 'OpenWallet' does not exist on type 'TesseractModule'.
```

**Comment by ezolenko** [comment]
Ok, today I learned about module augmentation...

Looks like it needs 3 things to work -- you need to import a module, augment it (with `declare module`) and then you need to export it (so the import statement doesn't get removed from resulting `d.ts`). You don't have the last part. If I add `TesseractModule` to the list of exports from `openwallet/src/index.ts`, everything compiles.

Not sure if it is the export that does it, or the import that now must be preserved in the typings actually.
