### ISSUE TITLE
TS18003: No inputs were found in config file

### ISSUE THREAD

**Issue by slavafomin** [ezolenko/rollup-plugin-typescript2#153]
Hello!

Thank you for this great plugin, it's a life saver!

However, I'm getting the following warning during compilation:

`rpt2: config error TS18003: No inputs were found in config file '/home/sfomin/projects/domclick/react-stage/library/misc/component-builder/config/tsconfig.lib.json'. Specified 'include' paths were '["**/*"]' and 'exclude' paths were '[]'.`

My `tsconfig.json` has only a "compilerOptions" property and no `include`/`exclude` properties at all. I do believe that Rollup is itself responsible for specifying the entry file and therefore all the files that should participate in the build. Please, correct me if I'm wrong.

Shouldn't this error be suppressed by the plugin?

The related question is: do I need to additionally specify inclusion/exclusion lists somewhere and for what purpose?

Thanks!

**Comment by ezolenko** [comment]
rpt2 relies on tsconfig for as much as possible, for complete list of files, for compiler options, etc. This is to make all other tooling (tsc, intelisense in IDEs, etc) work the same. Sometimes people have dev builds using tsc and deployment builds using rollup too.

Another direct reason to have tsconfig specify files is for generating type definitions and supporting watch mode -- not all files used by typescript are visible to rollup at all. Imported type definitions for example, or modules imported only for their types get erased by compiler before they get to rollup. Without using typescript's way of listing all relevant files, some types will be missing from the end result. (as it is we often have too many types exported actually, but that's a better problem to have)

Location of tsconfig file itself is used by typescript when it looks up imports (typescript must find the import first, it can't use rollup's mechanism for that). So if you have it located somewhere to the side, you might have other problems in the future. You can check if there are other errors if you set `abortOnError: false` in plugin options.

So my recommendation is to use tsconfig in a way that typescript's own compiler has nothing to complain about (in your case I think placing tsconfig in source root would do).

**Comment by slavafomin** [comment]
Thank you for explanation @ezolenko. Our use case is somewhat special. We have a monorepo with hundreds of packages and we're developing a single tool, that should be able to compile each package individually. Therefore, I have a single `tsconfig.ts` file, which is stored near the node.js tool. This makes specifying files in this `tsconfig.json` impossible, because the paths will be resolved relative to the config location, regardless of where the actual code is stored. One approach would be to create an empty `tsconfig.json` file in each package and to make it extend the config file stored with the tool.

What would be your recommendations for such scenario? Thank you!

**Comment by ezolenko** [comment]
Yeah, I think creating empty tsconfigs in each package that extends base config is the typescriptic way. 

You might find some other problems, depending on what's in your base config. There are a few closed issues related to base configs, might be more nobody found yet. Let me know if you find something strange. If you increase verbosity the plugin will print final tsconfig after parsing and overrides it allies.
