### ISSUE TITLE
custom transformer does not run when cache exists

### ISSUE THREAD

**Issue by WanderWang** [ezolenko/rollup-plugin-typescript2#155]
#### What happens and why it is wrong

customTransformer does not works then rpt2_cache folder exists

#### Environment 

Windows10 1903 ,WSL Terminal ( Ubuntu )

#### Versions
- typescript:3.4.3
- rollup:1.15.6
- rollup-plugin-typescript2:0.21.1

#### rollup.config.js

```typescript
  const inputOptions = {
        input: './index.ts',
        external: [

        ],
        plugins: [
            nodeResolve(),
            typescript({
                transformers,
                tsconfigDefaults,
                tsconfig: "tsconfig.json",
                tsconfigOverride: {
                    compilerOptions: {
                        module: 'esnext',
                        declarationDir: "../../../dist/" + packageName + "/dts-temp/"
                    }
                },
                useTsconfigDeclarationDir: true
            }),

        ]
    };
    const outputOptions = {
        file: path.join("../../../dist/", packageName, packageName + ".js"),
        format: "es",

    };

    // create a bundle
    const originCwdDir = process.cwd();
    process.chdir(path.resolve(__dirname, '../packages/', packageName, 'src'))
    const bundle = await rollup.rollup(inputOptions);
```

**Comment by WanderWang** [comment]
by the way , set ```{ clean:true }``` in rollup-plugin-typescript2 can resolve this program

**Comment by ezolenko** [comment]
Doesn't work how? Could you make a small test repo with reproduction?

**Comment by WanderWang** [comment]
Steps:



1. Compile with rollup/rollup-plugin-typescript2

2. After compilation, a cache file is generated

3. Modify the compilation script and add transformer

4. Compile without changing any typescript scripts

5. CustomTransformer will not implement





I think it should be the caching mechanism of rollup itself because transformer has not implemented any changes to typescript source code

**Comment by ezolenko** [comment]
I see, might be because object-hash doesn't like the way you do transformers. Could you post what your `transformers` object looks like? Does it have async functions for example?

If possible, run the build with `verbosity: 4` and post `rpt2: plugin options:` part of the output (printed close to the start of output). 

Do you add a new transformer to a list of existing transformers or did you add a first transformer when there was none before? (that last part should work)

**Comment by ezolenko** [comment]
And yeah workaround is to do clean builds

**Comment by agilgur5** [comment]
Closing this as a duplicate of #228 which has had much more activity and OP there responded to requests for more info, while this has been stale for some time.
