### ISSUE TITLE
Let us override "importHelpers: true"

### ISSUE THREAD

**Issue by aleclarson** [ezolenko/rollup-plugin-typescript2#156]
I don't want `tslib` in my bundle (or used by my bundle). I'm only using this plugin to strip types, then I'm feeding the output into Babel to make it ES5 compatible, which uses `@babel/runtime`.

Would you be open to adding a special case for `importHelpers` in pluginOptions?

```js
import ts from 'rollup-plugin-typescript2'

// in rollup plugins array:
ts({ check: false, importHelpers: false })
```

**Comment by aleclarson** [comment]
Oh, I just realized that using `"target": "esnext"` in `tsconfig.json` does what I want. 👍

**Comment by seivan** [comment]
@aleclarson Not exactly.
You might want to target lower but still skip helpers.
e.g React gives you objectAssign already, but now we have two of them with `importHelpers: true`.
It should be possible to skip it.
