### ISSUE TITLE
Typescript Fatal error

### ISSUE THREAD

**Issue by horaklukas** [ezolenko/rollup-plugin-typescript2#16]
Hi,

I'm trying to use rollup Javascript API in our internal build tool and sometimes it happens to me that typescript fail on same low level Fatal error like on the picture below

![image](https://cloud.githubusercontent.com/assets/996088/25283546/6d8bf16a-26b4-11e7-8b71-497921183281.png)

I don't know why, because it happens irregularly, once after 3. rebuild, next time after 15. rebuild. 

My rollup config is really simple and looks like this

```js
import rollup from "rollup";
import typescript from "rollup-plugin-typescript2";
	cache = {};

rollup.rollup({
	entry: "login/src/index.ts",
	plugins: [
		typescript({
			include: module + "login/src/**/*.ts",
			cacheRoot: tempDir + "/.rts2_cache"
		})
	],
	cache: cache[module] || false
}).then(function (bundle) {
	cache[module] = bundle;

	return bundle.write({
		format: "iife",
		moduleName: "app.login",
		dest: "login/dist/login.bundle.js"
	});
});
```

I tried Typescript version 2.1.6 and 2.2.2, both behave same. Don't you have any hint what could I try to avoid it, or at least handle it?

**Comment by ezolenko** [comment]
Looks like a memory leak somewhere or an actual OOM... Is your codebase particularly huge or build machine particularly tiny and lacking swap partition?

This might be in typescript proper or combination of ts/rollup/this plugin/node. 

What's your node version?

Could you try to narrow things down by running (pretty much in this order):
- rollup with that config directly `rollup -c <file>`
This will remove the rest of your build tooling from the equation.
- your rollup setup with [original typescript plugin](https://github.com/rollup/rollup-plugin-typescript)
That plugin uses typescript differently (on file-per-file basis)
- unrolled, by running `tsc` in tsconfig.json folder
That will remove rollup (but tsc is probably doing different things than this plugin does)

Try updating node itself and rollup as well.

Also maybe open a case in typescript, they might have ideas of further diagnostic: 
<https://github.com/Microsoft/TypeScript/issues>.

They will want your tsconfig.json, package.json, environment info, etc.

**Comment by horaklukas** [comment]
I'm trying to rollup just small module that consists of 3 source files and few definition files of other modules. Machine is strong enough, problem could be that I doesn't use unix like OS, but Windows 10.

My configuration is:
 * node 6.2.0
 * rollup 0.41.6
 * rollup-plugin-typescript 0.4.0
 * typescript 2.1.6

Standalone `tsc` would might  probablly work, but that is not what I need. Anyway I will try different setups and observe how it behaves.

**Comment by horaklukas** [comment]
The error haven't appeared for few day so I consider the problem resolved. My problem was poorly configured project. I was missing `exclude: ['node_modules']` in my `tsconfig.json` that probably caused  the troubles, because there was a really huge amount of typescript modules and for some reason compiler didn't manage it well.
