### ISSUE TITLE
outdated micromatch dep (in rollup-pluginutils) is 2.21MB / 6.71MB

### ISSUE THREAD

**Issue by leeoniya** [ezolenko/rollup-plugin-typescript2#161]
@ezolenko 

https://packagephobia.now.sh/result?p=rollup-plugin-typescript2
https://packagephobia.now.sh/result?p=micromatch
http://npm.broofa.com/?q=rollup-plugin-typescript2

i've opened https://github.com/rollup/rollup-pluginutils/issues/65 to try and get it updated. if that ends up happening, might be worth bumping rollup-pluginutils ver.

**Comment by ezolenko** [comment]
I updated all dependencies and I see rollup-pluginutils 2.8.1 requiring `"micromatch": "^4.0.2",` in its dev dependencies, but npm still installs micromatch 3.1.10 and claims rollup-pluginutils requires it. 

Shouldn't it not install micromatch at all, since it is in dev dependency list of my dependency?

**Comment by leeoniya** [comment]
looks like it's getting installed through these chains :(

```
rollup       -> chokidar -> anymatch -> micromatch
rollup-watch -> chokidar -> anymatch -> micromatch
```

i think rollup-watch can be dropped since it's supported natively in rollup now: https://rollupjs.org/guide/en/#rollupwatch

as for rollup itself, ping @lukastaegert, and/or chokidar ping @paulmillr

**Comment by paulmillr** [comment]
If you want to use new micromatch, you / rollup should use chokidar v3.

Chokidar v3 and new micromatch support nodejs v8.16 and higher. So, in this case Rollup would need to drop support for nodejs v6 etc. It's ultimately their call.

See my blog post for perspective on updating to v3: https://paulmillr.com/posts/chokidar-3-save-32tb-of-traffic/

**Comment by leeoniya** [comment]
wow @paulmillr that looks like a huge win for a lot of people if rollup switches to v3 as it's very widely used.

**Comment by lukastaegert** [comment]
Rollup does not have a dependency on chokidar, you have to install it yourself. To my knowledge, v3 should work all right if you have it installed. If it does not, that should be worth a ticked.

**Comment by leeoniya** [comment]
@ezolenko 

i think it's a combination of these devDeps:

```
    "rollup-plugin-typescript2": "0.21.2",
    "rollup-watch": "4.3.1",
```

0.21.2 still depends on rollup-pluginutils 2.6, which pulls in micromatch 3. rollup-watch pulls in an old chokidar, which does the same. removing these deps makes micromatch go away. if you publish 0.22.0 then anyone who uses this package via npm will no longer get the old micromatch (since devdeps arent installed). but cloning this repo an doing `npm i` will still get it due to the above deps.

**Comment by ezolenko** [comment]
Ok, 0.22.0 is out, `node_modules` is a bit smaller now.

**Comment by leeoniya** [comment]
nice. shaved 2MB off `node_modules` and ~2s off `npm i rollup-plugin-typescript2`
