### ISSUE TITLE
Does this plugin benefit from tsc's incremental building technology?

### ISSUE THREAD

**Issue by shrinktofit** [ezolenko/rollup-plugin-typescript2#171]
Our project is written in Typescript and have the requirement to **incremental packing**.

For now, we have already constructed a build flow which implements incremental packing codes but compile using `babel + @babel/preset-typescript`.

We are plan to migrate to `rollup + rollup-plugin-typescript2`. 

As far as I know, rollup doesn't provide the incremental build schema. The rollup watch mode only holds memory cache but we need disk cache, like tsc's incremental build does. (_Their `expermentalCache` option is hard to use, the cache is huge_). The disk cache allow very fast compile and is available even next time the app boots.

If not, I think we have to use "tsc-incremental-build" plus "our incremental packing". That's painful.

I've noticed that there is a `cacheRoot` option.

**Comment by ezolenko** [comment]
No, it doesn't use tsc directly. It does have it's own cache which speeds up builds by 10-50% comparing to a clean build (depending on other plugins and what rollup itself needs to do). If it is easy to setup and try you can do a run with `clean : true` (disables cache completely) and without it.
