### ISSUE TITLE
Async functions emits warning

### ISSUE THREAD

**Issue by bastienrobert** [ezolenko/rollup-plugin-typescript2#174]
When I try to build a file containing async functions, there's the following warning:

`this` has been rewritten to `undefined`

#### Environment 

- node v10.16.0
- rollup-plugin-node-resolve (^5.2.0)
- rollup-plugin-typescript2 (^0.24.2)
- rollup-plugin-babel (^4.3.3)
- rollup-plugin-commonjs (^10.1.0)
- rollup-plugin-terser (^5.1.2)

#### Versions
- typescript: ^3.6.3
- rollup: ^1.21.4
- rollup-plugin-typescript2: ^0.24.2

#### rollup.config.js

```
import resolve from 'rollup-plugin-node-resolve'
import typescript from 'rollup-plugin-typescript2'
import babel from 'rollup-plugin-babel'
import commonjs from 'rollup-plugin-commonjs'
import { terser } from 'rollup-plugin-terser'

import pkg from './package.json'

const extensions = ['.js', '.jsx', '.ts', '.tsx']

export default {
  input: ['src/index.ts'],
  output: {
    file: pkg.main,
    format: 'cjs'
  },
  external: ['@slack/client', 'dlv', 'dotenv', 'googleapis', 'micro'],
  plugins: [
    resolve({ extensions }),
    typescript({
      useTsconfigDeclarationDir: true
    }),
    babel(),
    commonjs(),
    terser()
  ]
}
```

#### tsconfig.json

```
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "moduleResolution": "node",
    "target": "es2015",
    "module": "es2015",
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "declaration": true
  },
  "include": ["src/**/*.ts"],
  "types": ["node"]
}
```

**Comment by ezolenko** [comment]
It that rollup's warning? Could you post your build log?

**Comment by bastienrobert** [comment]
Yes it's a rollup warning ☹️ 

Build log:
```
rollup v1.21.4
bundles src/index.ts → dist/index.js...
(!) `this` has been rewritten to `undefined`
https://rollupjs.org/guide/en/#error-this-is-undefined
src/index.ts
1: var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
                    ^
2:     function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
3:     return new (P || (P = Promise))(function (resolve, reject) {
...and 2 other occurrences
created dist/index.js in 1.2s

[2019-09-24 10:33:53] waiting for changes...
```

**Comment by ezolenko** [comment]
I think this is a problem with your code, read the description at that rollup link: https://rollupjs.org/guide/en/#error-this-is-undefined

**Comment by bastienrobert** [comment]
Yes but when I remove the async, everything is working as expected, so 😕

**Comment by ezolenko** [comment]
You can get js typescript produces from the cache (in `node_modules/.cache/rollup-plugin-typescript2/code` by default). Find the cache for your file and check if the produce js is what you would expect.

The plugin feed this js to rollup instead of ts code.

**Comment by bastienrobert** [comment]
Alright, I think I'm just going crazy. The error has disappeared, I can not re-create it. Well... so i'm closing this 🤷🏻‍♂️
