### ISSUE TITLE
Exported types not present in generated output

### ISSUE THREAD

**Issue by cslecours** [ezolenko/rollup-plugin-typescript2#175]
#### What happens and why it is wrong
repro repository : https://github.com/cslecours/repro-ts-rollup-issue

In the output, I am missing types that were exported. In `dist` I see the `types/index.d.ts` but not `types/abc.d.ts` that it depends on. It seems to be related to the `allImportedFiles` Set that was added by 0.23 as I see that my files are skipped.

I did attempt at a fix, but it will probably break other things.
https://github.com/cslecours/rollup-plugin-typescript2 

#### Versions
- typescript: 3.1.6
- rollup: 1.21.2
- rollup-plugin-typescript2: 0.24.2

#### rollup.config.js
https://github.com/cslecours/repro-ts-rollup-issue/blob/master/rollup.config.js

#### plugin output with verbosity 3

https://github.com/cslecours/repro-ts-rollup-issue/blob/master/output_logs/npm-run-build.txt

**Comment by ezolenko** [comment]
Looks related to #172 

Your fix looks correct actually, create a PR :)
