### ISSUE TITLE
TS plugin generate multiple cache folders for the same TypeScript project

### ISSUE THREAD

**Issue by Soul-Master** [ezolenko/rollup-plugin-typescript2#179]
#### What happens and why it is wrong
TS plugin use entire Rollup options to generate hash code as a part of cache folder name. It means always generate new cache folder even input file is in the same TypeScript project.

![image](https://user-images.githubusercontent.com/442046/66394169-8b53ca00-e9fe-11e9-8b63-378a92d97558.png)

#### Versions
- typescript: 3.6.2
- rollup: 1.20.3
- rollup-plugin-typescript2: 0.24.0

#### rollup.config.js
```
{
        input: 'src/js/page1.ts',
        output: {
            name: 'Page1',
            file: 'src/build/page1.js',
        },
        treeshake: true,
        output: {
            format: 'iife'
        },
        onwarn(warning) {
            if (warning.code === 'EVAL') return;

            console.warn(warning.code + ': ' + warning.message);
        },
        plugins: [
            resolve({
                modulesOnly: false,
                extensions: ['.js', '.json', '.css']
            }),
            sourcePlugin,
            json({
                include: 'src/**/*.json',
                preferConst: true
            }),
            html({
                include: ['src/**/*.html', 'src/**/*.svg'],
                htmlMinifierOptions: {
                    caseSensitive: true,
                    collapseWhitespace: true,
                    collapseBooleanAttributes: true,
                    removeComments: true
                }
            }),
            url({
                limit: 10 * 1024, // inline files < 10k, copy files > 10k
                include: ["src/**/*.png"],
                emitFiles: false
            }),
            less({
                // Generate CSS separately
                output: options.output.file.replace('.js', '.css'),
                exclude: [],
                option: {
                    plugins: [
                        cleanCSSPlugin
                    ]
                }
            }),
            terser({
                // https://github.com/terser-js/terser#minify-options
                compress: {},
                output: {},
                // https://github.com/mishoo/UglifyJS2/issues/1753
                mangle: {
                    safari10: true
                }
            }),
        ]
    }
```

```
{
        input: 'src/js/page2.ts',
        output: {
            name: 'Page2',
            file: 'src/build/page2.js',
        },
        ...
}
```

```
{
        input: 'src/js/page3.ts',
        output: {
            name: 'Page3',
            file: 'src/build/page3.js',
        },
        ...
}
```

```
{
        input: 'src/js/page4.ts',
        output: {
            name: 'Page4',
            file: 'src/build/page4.js',
        },
        ...
}
```

```
{
        input: 'src/js/page5.ts',
        output: {
            name: 'Page5',
            file: 'src/build/page5.js',
        },
        ...
}
```

#### tsconfig.json in `src` folder
```
{
  "extends": "../configs/tsconfig.base",
  "compilerOptions": {
    "composite": true,
    "module": "amd",
    "outDir": "./build",
    "baseUrl": ".",
    "declaration": true,
    "declarationMap": true,
    "sourceMap": false,
    "types": []
  },
  "include": [ "**/*.ts", "**/*.json" ],
  "exclude": [ "build", "lib" ]
}
```

#### tsconfig.base in `config` folder
```
{
  "compileOnSave": true,
  "compilerOptions": {
    "target": "es2016",
    "moduleResolution": "node",
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noUnusedLocals": true,
    "noEmitHelpers": true,
    "strictFunctionTypes": true,
    "alwaysStrict": true,
    "experimentalDecorators": true,
    "keyofStringsOnly": true,
    "forceConsistentCasingInFileNames": true,
    "resolveJsonModule": true,
    // Common ES2016 - Proxy
    "lib": [
      "dom",
      "dom.iterable",
      "es5",
      "es2015.core",
      "es2015.collection",
      "es2015.iterable",
      "es2015.promise",
      "es2016.array.include",
      "es2017.object"
    ],
    "plugins": [
      {
        "name": "typescript-tslint-plugin",
        "ignoreDefinitionFiles": true
      }
    ]
  }
}

```

**Comment by Soul-Master** [comment]
This behavior causes by the following statement.

```
this.cacheDir = `${this.cacheRoot}/${this.cachePrefix}${hash(
	{
		version: this.cacheVersion,
		rootFilenames,
		options: this.options,
		rollupConfig: this.rollupConfig,
		tsVersion: tsModule.version,
	},
	this.hashOptions,
)}`;
```
https://github.com/ezolenko/rollup-plugin-typescript2/blob/2d330640316894752bae5ae64d94bc90652e4564/src/tscache.ts#L119

**Comment by ezolenko** [comment]
This is probably because you are modifying your rollup config. It might be possible for a change there to affect typescript compilation (or rather I don't want to prove that it is impossible), and if plugin serves up cached version, the build will be different from a clean build.

If you run the build with `clean: true` option, all caches should be deleted.

**Comment by ezolenko** [comment]
Multiple subsequent builds when nothing changes should not produce new cache folders, let me know if they do.

**Comment by Soul-Master** [comment]
@ezolenko 
I think you misunderstood my point. Let's me explain more about my use case.

In my project, I have several static pages that are used in different platforms (web/mobile/Electron). Each page consist of 1 static HTML, 1 combined JS and 1 combined CSS. All of these files are generated by Rollup from the same TypeScript project.

I use multiple npm scripts to generate all of these JS files.

`build:dist-page1` "rollup -c ./tools/build-page1.js"
`build:dist-page2` "rollup -c ./tools/build-page2.js"
`build:dist-page3` "rollup -c ./tools/build-page3.js"
`build:dist-page4` "rollup -c ./tools/build-page4.js"
`build:dist-page5` "rollup -c ./tools/build-page5.js"

I use `run-s` command of `npm-run-all` package to run multiple npm scripts sequentially.

`build:dist`: "run-s build:dist-*",

In build-page`x`.js file, it should looks like this.

```
import { defaultOptions } from '../rollup';

export default bundle({
    ...defaultOptions,

    input: 'src/js/pagex.ts',
    output: {
        name: 'Pagex',
        file: 'src/build/pagex.js',
    }
});
```

TypeScript plugin use entire Rollup options to compute hash which includes **input** and **output** properties. It means TypeScript plugin doesn't use the same cache folder when I execute script to build multiple pages.

For example, I execute `npm run build:dist-page1`. It generates `rpt2_5c9d6e4b22f5602f74f7a273eba6c60d5910391b` as a cache folder. Next, I execute `npm run build:dist-page2`. It generates `rpt2_85d409277275b005e933c5f3ed86cb146a918664` as a cache folder.

**Comment by ezolenko** [comment]
So you are using same input typescript and get exactly the same output bundle from rollup, just in several different names (so page1.js === page2.js === etc)? Or are the bundles different?

RE: fixed cache, you can get the same effect if you precompile ts files into js (either as a separate rollup run, or by using `tsc` directly), and then use js directly in your many following rollup calls.

**Comment by Soul-Master** [comment]
page1.ts import some desktop libraries, it has desktop look&feel and some desktop business logic.

Page2.ts import some web libraries, it has web page look & feel and some web business logic.

Both of these pages share a lot of modules. But it is not the same. Around 20% of modules are platform-specified.

**Comment by Soul-Master** [comment]
For fixed cache:
Thanks, I almost forget that I can compile TypeScript to JavaScript before use plain ES6 module as input.

It seems to an appropiated way instead of compiling Rollup with TypeScript file as a input for multiple times.

**Comment by Soul-Master** [comment]
Thanks again for your advise. I compile TypeScript project as ES6 module to cache folder and use the following Rollup options to resolve TypeScript files.

 ```
{
    resolveId(id, importer) {
        let absPath = path.resolve(path.dirname(importer), id);
        const fileName = path.basename(absPath);        

        if (!fileName.includes('.')) {
            return absPath + '.ts';
        }

        return null;
    },
    load(id) {
        if (id.slice(-3) !== '.ts') return null;

        const es6File = cacheFolderPath + id.substring(srcFolderPath.length, id.length - 2) + 'js';

        return { code: fs.readFileSync(es6File, 'utf-8') };
    }
}
```

It reduces compile time for 12 pages around 60%.
![image](https://user-images.githubusercontent.com/442046/66835588-fd418b80-ef89-11e9-9779-7b1a9f8bebb3.png)
