### ISSUE TITLE
Unused transitive dependency included as triple slash reference (Storybook, Emotion)

### ISSUE THREAD

**Issue by ekohanyi** [ezolenko/rollup-plugin-typescript2#185]
#### What happens and why it is wrong
I have a component library that is implemented with React, TypeScript, Storybook and Rollup. When i run rollup, for some reason a dependency of storybook (`@emotion/core`) is getting included in one of my compiled files as a triple slash reference. This dependency isn't listed in the `package.json` and is only in `node_modules` because storybook uses it for something, and I'm not sure why it's being included. 

```javascript
/// <reference types="@emotion/core" />
```

This is also causing a type checking issue in the application consuming the component library. When i run type script checks i get this error: 
```bash
[0] TS2688: Cannot find type definition file for '@emotion/core'.
```

If i go in and delete the triple slash reference in the compiled file before my main application consumes the component library, i don't get any issues, so i would prefer to just not have the reference included rather than having to import `@emotion/core` if it isn't being used.

also open to any other possible solutions (config changes, etc) that people can think of if this really is just an implementation issue

#### Environment 

local environment, using `yalc` to link the component library rollup dist to the main application

#### Versions
- typescript: v3.6.4
- rollup: v1.23.1
- rollup-plugin-typescript2: v0.24.3

#### rollup.config.js
```javascript
import postcss from 'rollup-plugin-postcss';
import url from 'postcss-url';
import precss from 'precss';
import autoprefixer from 'autoprefixer';
import peerDepsExternal from 'rollup-plugin-peer-deps-external';
import commonjs from 'rollup-plugin-commonjs';
import replace from 'rollup-plugin-replace';
import resolve from 'rollup-plugin-node-resolve';
import typescript from 'rollup-plugin-typescript2';
import { terser } from 'rollup-plugin-terser';
import svgr from '@svgr/rollup';

const config = {
  input: // input here,
  output: [
    // output location here
  ],
  external: ['react', 'react-dom'],
  plugins: [
    postcss({
      extract: false, // enables CSS modules for the bundle
      modules: true, // keeps the CSS in the JavaScript file
      plugins: [url({ url: 'inline' }), precss(), autoprefixer()],
      minimize: true, // minimize CSS
    }),
    // svg(),
    svgr({
      svgoConfig: {
        plugins: {
          removeViewBox: false,
        },
      },
    }),
    peerDepsExternal(),
    resolve(),
    //transpile typescript
    typescript({
      rollupCommonJSResolveHack: true,
      //exclude: '**/**/styles.css',
      clean: true,
    }),
    commonjs({
      include: ['node_modules/**'],
      namedExports: {
        'node_modules/react/react.js': ['Children', 'Component', 'PropTypes', 'createElement'],
        'node_modules/react-dom/index.js': ['render'],
        'node_modules/js-cookie/src/js.cookie.js': ['Cookies'],
      },
    }),
  ],
};

export default [config];
```
Note: there's a minified config piece as well but i took that out for simplicity's sake since this issue is appearing in the un-minified files as well

#### tsconfig.json

```javascript
{
  "compilerOptions": {
    "outDir": "dist",
    "module": "esnext",
    "target": "es5",
    "lib": ["es5", "es6", "es7", "es2017", "dom"],
    "sourceMap": true,
    "allowJs": false,
    "jsx": "react",
    "moduleResolution": "node",
    "rootDirs": ["lib"],
    "baseUrl": "lib",
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitAny": false,
    "strictNullChecks": true,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": true,
    "declaration": true,
    "allowSyntheticDefaultImports": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true
  },
  "include": // included directory here,
}

```

**Comment by ezolenko** [comment]
Triple slashes are added by typescript itself. Could you try running `tsc` directly and checking if you get the same result as far as types go?

**Comment by KseniaKuntsevich** [comment]
I had same issue after updating Storybook the latest version 16.4.19.
Command that I run `npx sb@latest upgrade` or `npx npm-check-updates '/storybook/' -u` is looking for '@storybook/*' packages with version 16.4.19.
So it missed @storybook/addon-knobs because its last version is 16.4.

<img width="368" alt="Снимок экрана 2022-02-24 в 00 40 37" src="https://user-images.githubusercontent.com/46778385/155413336-92426808-ec81-4ba3-8425-0df8c75c2544.png">



I needed to update @storybook/addon-knobs manually by

```
npm i @storybook/addon-knobs@6.4 --save-dev
```

**Comment by agilgur5** [comment]
Closing this as stale as OP never responded to requests for more information and did not provide a reproduction, so there's no way of testing or investigating this situation.
As this is added by the TS `LanguageService` API, that's not something rpt2 controls, so it is unlikely to be a bug (though it is _possible_, as sometimes there are bugs that affect resolution etc).

The comment above also suggests that this is _correct_ behavior
