### ISSUE TITLE
Is this plugin deprecated?

### ISSUE THREAD

**Issue by osdevisnot** [ezolenko/rollup-plugin-typescript2#186]
Started Noticing this message on NPM:

![image](https://user-images.githubusercontent.com/802242/67787207-67980880-fa2d-11e9-9e73-d402f810cb9e.png)

**Comment by ezolenko** [comment]
No, that was me deprecating a broken version I released before enough coffee was ingested. Use last good release (0.24.3) for now.

I suppose I should have unpublished it in the first place
