### ISSUE TITLE
Definition files in npm packages are ignored

### ISSUE THREAD

**Issue by kimamula** [ezolenko/rollup-plugin-typescript2#191]
#### What happens and why it is wrong

It is likely this plugin ignores definition files (`*.d.ts` files) included in npm packages.

I have created a simple [example](https://github.com/kimamula/rollup-dts) to reproduce the problem.
You can try it with `npm i && npm start` after `git clone`.

In the example, I prepared pseudo npm package `do-something` which has only 3 files, `index.js`, `index.d.ts` and `package.json`.

##### do-something/index.js
```js
export function doSomething() {}
```

##### do-something/index.d.ts
```ts
export function doSomething(): void;
```

##### do-something/package.json
```json
{
  "name": "do-something",
  "version": "1.0.0"
}
```

I installed the package and used it in the main `index.ts` file.

##### index.ts
```ts
import { doSomething } from 'do-something';
doSomething();
```

This file can be compiled with `tsc` without any error, while compilation with `rollup-plugin-typescript2` shows the following warning messages and results in an invalid JS output.

##### warning messages
```sh
./index.ts → index.js...
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
do-something (imported by index.ts)
(!) Missing global variable name
Use output.globals to specify browser global variable names corresponding to external modules
do-something (guessing 'doSomething')
created index.js in 1s
```

##### invalid JS output
```js
(function (doSomething) {
	'use strict';

	doSomething.doSomething();

}(doSomething));
```

#### Versions
- typescript: 3.7.2
- rollup: 1.26.3
- rollup-plugin-typescript2: 0.25.2

#### rollup.config.js

```js
import typescript from 'rollup-plugin-typescript2';

export default {
  input: './index.ts',
  output: {
    file: 'index.js',
    format: 'iife'
  },
  plugins: [
    typescript()
  ]
};
```

#### tsconfig.json

```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "es2015",
    "strict": true,
    "moduleResolution": "node"
  }
}
```

#### package.json

```json
{
  "name": "rollup-dts",
  "version": "1.0.0",
  "scripts": {
    "start": "rollup -c"
  },
  "devDependencies": {
    "do-something": "file:do-something",
    "rollup": "^1.26.3",
    "rollup-plugin-typescript2": "^0.25.2",
    "typescript": "^3.7.2"
  }
}
```

**Comment by ezolenko** [comment]
This is rollup error, it complains that it can't find an import. You need
to add roolup-plugin-node-resolve before rpt2 in rollup config

**Comment by kimamula** [comment]
Thanks for your explanation.
I got it.
