### ISSUE TITLE
How to override include field?

### ISSUE THREAD

**Issue by Seeingu** [ezolenko/rollup-plugin-typescript2#196]
#### What happens and why it is wrong

Hey there, I want to replace `include` array in `tsconfig.json`, for example, I want to replace `"include": ["a", "b"]` with `include: ["a"]`，but it doesn't work.

Looks like using `_.merge` is the reason. https://github.com/ezolenko/rollup-plugin-typescript2/blob/master/src/parse-tsconfig.ts#L44

#### Versions
- typescript: 3.7.2
- rollup: 1.25.2
- rollup-plugin-typescript2: 0.24.3

#### tsconfig.json

```json
{
  "compilerOptions": {

  },
  "include": ["src/**/*", "example/**/*"]
}
```

#### _.merge output
![_.merge output](https://user-images.githubusercontent.com/18718596/69773048-b2dc3d00-11cc-11ea-9467-9c68cff77775.png)

**Comment by ezolenko** [comment]
Yeah, it is because of _.merge. You can add an exclude list, that will override include.

You could also use a base tsconfig with all the options and without includes, and create a specific leaf tsconfigs that include base and use that with rollup. Or add includes at the plugin level.

**Comment by Seeingu** [comment]
I see. Thanks.

**Comment by agilgur5** [comment]
Duplicate of #86
