### ISSUE TITLE
Cannot import in typescript within nodejs

### ISSUE THREAD

**Issue by JProgrammer** [ezolenko/rollup-plugin-typescript2#20]
I am using this in a gulp to compile using gulp-better-rollup when importing it uses the typings from dist and loads rollup-plugin-typescript2.cjs.js

However rollup does not export the default as default in cjs

Using

`import typescript from "rollup-plugin-typescript2"`

results in `TypeError: rollup_plugin_typescript2_1.default is not a function`.

To work around this I have had to import like this

`import * as typescript from "rollup-plugin-typescript2"`

Then cast as any to invoke.

```
plugins: [
        (typescript as any)()
]
```

Also the interface for the options does not match the documentation, as the typeings has the options object as required and all properties as required.

**Comment by ezolenko** [comment]
Hm, does `import { typescript } from "rollup-plugin-typescript2"` work?

**Comment by ezolenko** [comment]
Also, is your gulpfile itself written in typescript? How do you bootsrtrap that?

**Comment by JProgrammer** [comment]
rollup-plugin-typescript2 doesn't have an export of `typescript` only a default export .
https://github.com/ezolenko/rollup-plugin-typescript2/blob/master/dist/rollup-plugin-typescript2.cjs.js#L610

I am executing a gulpfile written in typescript using ts-node https://github.com/TypeStrong/ts-node#gulp

**Comment by ezolenko** [comment]
I committed option typing fix, and tried to import plugin in a random typescript project -- seems to work for me. 

```
import typescript from "C:\\sandbox\\rollup-plugin-typescript2\\dist";

//...

typescript({cacheRoot: ""});

```

Here is what got generated:

```
function _interopDefault (ex) { return (ex && (typeof ex === 'object') && 'default' in ex) ? ex['default'] : ex; }

var typescript = _interopDefault(require('../../rollup-plugin-typescript2/dist'));

// ...

typescript({ cacheRoot: "" });
```

I'm using typescript 2.3.4 with this in tsconfig.json. module, target, moduleResolution, noEmitHelpers, importHelpers are probably relevant.
```
{
  "compilerOptions": {
      "module": "es2015",
      "target": "es6",
      "moduleResolution": "node",
      "removeComments": true,
      "noImplicitAny": true,
      "experimentalDecorators": true,
      "strictNullChecks": true,
      "noUnusedParameters": true,
      "noUnusedLocals": true,
      "sourceMap": true,
      "noImplicitThis": true,
      "diagnostics": true,
      "listFiles": true,
      "pretty": false,
      "noEmitOnError": false,
      "noEmitHelpers": true,
      "importHelpers": true,
      "traceResolution": false,
      "isolatedModules": false,
      "emitDecoratorMetadata": false,
      "skipDefaultLibCheck": true,
      "declaration": false,
      "noImplicitUseStrict": false,
      "noLib": false,
      "newLine":"LF",
      "forceConsistentCasingInFileNames": true,
      "noImplicitReturns": true,
      "preserveConstEnums": false,
      "suppressImplicitAnyIndexErrors": false
  },
  "include": [
    "typings/**/*.d.ts",
    "src/**/*.d.ts",
    "src/**/*.ts"
  ],
  "exclude": [
    "dist",
    "libs"
  ]
}

```

**Comment by JProgrammer** [comment]
`_interopDefault` seems to be a injection from rollup, I am running directly in nodejs not rollup first.

**Comment by ezolenko** [comment]
What's in your tsconfig.json (the one that ts-node uses) and which typescript version does it use?

When I run tsc directly it works for me too. Depending on `module` I get different transpiles:

### source
```
import rpt from "D:\\source\\scr\\rollup-plugin-typescript2\\dist";
rpt({ verbosity: 4 });
```
![image](https://user-images.githubusercontent.com/1617834/27193223-4f0c464a-51bb-11e7-9aff-e91060fc7d35.png)

### es2015
```
import rpt from "D:\\source\\scr\\rollup-plugin-typescript2\\dist";
rpt({ verbosity: 4 });
```

### commonjs
```
var D__source_scr_rollup_plugin_typescript2_dist_1 = require("D:\\source\\scr\\rollup-plugin-typescript2\\dist");
D__source_scr_rollup_plugin_typescript2_dist_1.default({ verbosity: 4 });
```

BTW, the errors you are getting are during transpiling, not at runtime, right? (I haven't tried to actually run anything yet)

**Comment by ezolenko** [comment]
Closing this for now, let me know if still broken.

**Comment by JProgrammer** [comment]
Sorry @ezolenko the issue happens at runtime not compile time. The tsconfig I am using is.

```{
  "compilerOptions": {
    "target": "es5",
    "moduleResolution": "node",
    "noImplicitAny": false,
    "jsx": "react"
  },
  "exclude": [
    "./dist",
    "__tests__/**/*"
  ]
}```

**Comment by ezolenko** [comment]
Ok, I see the problem, and it does go away with removing default from export: 
```typescript
export function typescript(options?: IOptions)
```

It is then possible to use it normally in ts-node:
```typescript
import { typescript } from "rollup-plugin-typescript2";`

plugins: [
	typescript({ verbosity: 3 }),
],
```

This however breaks the way everybody running plain node imports this plugin (and all other rollup plugins -- you will have trouble importing any of them) -- they have to use named require now, so:
```js
const typescript = require("rollup-plugin-typescript2");

plugins: [
	typescript({ verbosity: 3 }),
],
```
becomes
```js
const typescript = require("rollup-plugin-typescript2");

plugins: [
	typescript.typescript({ verbosity: 3 }),
],
```

I don't know if this is a bug in typescript generating invalid code, or if combination of module/target in tsconfig generates code ts-node doesn't support or if that's just a casualty of JS module system clusterfail.

I'll look for some nicer workaround. Let me know if you have any ideas.

**Comment by wessberg** [comment]
Yup, I find this to be a frequent issue with interoperability between Typescript's and Rollup's interpretations of the module system.

Two ways to fix it:

- Consumers can set this `compilerOption` to `true` in their `tsconfig.json`: `allowSyntheticDefaultImports: true`
- `rollup-plugin-typescript2` could offer both a named and a default export of the transformer function.

**Comment by ezolenko** [comment]
@wessberg try with `module: esnext` in 0.12.0, I think it affect behavior of `allowSyntheticDefaultImports`.

**Comment by j-oliveras** [comment]
If you use a gulpfile.ts, using typescript 2.8 and [`"esModuleInterop": true`](https://www.typescriptlang.org/docs/handbook/compiler-options.html) option you can import this with
```ts
import typescript from "rollup-plugin-typescript2";
```
enabling this option, can change other import behaviours (if an import fails at runtime try removing `* as` from that import, or adding it).

**Comment by paulsouche** [comment]
Hi !

Same issue here I made a simple `rollup.ts` file to bundle a module using `ts-node rollup.ts`

```typescript
import * as rollup from 'rollup';
import * as typescript from 'rollup-plugin-typescript2';
import 'ts-helpers';

const plugins = [(typescript as any)()];

const buildModule = async () => {
  const bundle = await rollup.rollup({
    input: './index.ts',
    plugins,
  });

  await bundle.write({
    file: 'dist/umd/index.js',
    format: 'umd',
    name: 'MyNameSpace.MyName',
    sourcemap: true,
    sourcemapFile: 'dist/umd/index.js.map',
  });
};
```

Everything is working fine with `import * as typescript from 'rollup-plugin-typescript2';` but we need an any cast as explained by @JProgrammer 

I got runtime error `rollup_plugin_typescript2_1.default is not a function` with `import typescript from 'rollup-plugin-typescript2';` because [typescript is not default export](https://github.com/ezolenko/rollup-plugin-typescript2/blob/master/dist/rollup-plugin-typescript2.cjs.js#L20185) even if [declarations say so](https://github.com/ezolenko/rollup-plugin-typescript2/blob/master/dist/index.d.ts#L6)

I tried `"esModuleInterop": true` but got runtime error `ReferenceError: __importStar is not defined` but I think it's not a good idea to find a solution with that.

`ìmport {typescript} from 'rollup-plugin-typescript2'` leads to compilation error `module has no exported member 'typescript'`

`allowSyntheticDefaultImports: true` && `module: esnext` do not work neither....

`require` works but equivalent as `import *` and does not avoid as any cast.

So what about generating a default export correctly to use it with typescript in main file ?

Thanks anyway for the great job !

**Comment by ezolenko** [comment]
@paulsouche does ts-node work with any other rollup plugin? I checked a few and they all have `module.exports = <function>` in cjs build, and `export default <function>;` in es build.

Why does ts-node end up using cjs build (`main` from `package.config` instead of `module` or `jsnext:main`)?

**Comment by nodeful** [comment]
Worked when I did:
```js
import * as typescript from 'rollup-plugin-typescript2'
plugins.push((typescript as any)({
  tsConfig: './tsconfig.json'
}))
```

**Comment by ezolenko** [comment]
Looks like there are bunch of workarounds, closing for now.
