### ISSUE TITLE
declaration maps (*.d.ts.map) have incorrect relative paths in `sources` unless `declarationDir` is set

### ISSUE THREAD

**Issue by agilgur5** [ezolenko/rollup-plugin-typescript2#204]
#### What happens and why it is wrong

This comes from downstream TSDX at https://github.com/jaredpalmer/tsdx/issues/479 (and https://github.com/jaredpalmer/tsdx/issues/135), which I fixed in https://github.com/jaredpalmer/tsdx/issues/488 by adding a `declarationDir`, but I'm not sure if this isn't just a bug here. I believe the potential bug is either in https://github.com/ezolenko/rollup-plugin-typescript2/blob/ac821249f38a083c12071df8b420bea8c527d76e/src/get-options-overrides.ts#L31 or in https://github.com/ezolenko/rollup-plugin-typescript2/blob/df241da73f355140ae5d38b748e22fac3be89b65/src/index.ts#L364 but I'm not sure. Also not sure if this is related to #136 or not.

The tl;dr on those related issues is that TSDX takes `./src/index.ts` as input and outputs `./dist/index.js`, `./dist/index.d.ts`, and if `declarationMap` is `true`, `./dist/index.d.ts.map`, which has a `sources` attribute.
- The problem is that when `declarationDir` is _not_ set, `sources` will _incorrectly_ point to `index.ts`
- When `declarationDir` _is_ set to `./dist`, `sources` will _correctly_ point to `../src/index.ts`.
  - (with `useTsconfigDeclarationDir: true` ofc)

But in both cases, whether `declarationDir` is set to `./dist` or not, everything gets output to `./dist` via Rollup config.

If I'm understanding the code correctly, this is because the TS Language Service isn't creating the files when `declarationDir` isn't set, and so the relative paths are generated incorrectly before `emitFile` is called.
So that _seems_ like a bug here, but maybe I'm missing something or its not fixable without setting `declarationDir`, sorry if that's the case 😅 

#### Environment 

[TSDX @ master](https://github.com/jaredpalmer/tsdx/tree/68f26c90d81aa65ff46098b59d6f5ae9cf591cbd)

#### Versions
- typescript: 3.7.5
- rollup: 1.27.8
- rollup-plugin-typescript2: 0.26.0

#### rollup.config.js

The only difference is what's listed above (`useTsconfigDeclarationDir` and `declarationDir`), but current, non-trivial config is [here](https://github.com/jaredpalmer/tsdx/blob/68f26c90d81aa65ff46098b59d6f5ae9cf591cbd/src/createRollupConfig.ts)

#### tsconfig.json

`declarationDir` is the only relevant one but here's [a fixture](https://github.com/jaredpalmer/tsdx/blob/68f26c90d81aa65ff46098b59d6f5ae9cf591cbd/test/fixtures/build-default/tsconfig.json)

#### package.json

Probably not relevant but [here](https://github.com/jaredpalmer/tsdx/blob/68f26c90d81aa65ff46098b59d6f5ae9cf591cbd/package.json)

#### plugin output with verbosity 3

No errors, so I don't think it's relevant? Can run this on a fixture if needed.

**Comment by ezolenko** [comment]
I think it relates to this line:

https://github.com/ezolenko/rollup-plugin-typescript2/blob/ac821249f38a083c12071df8b420bea8c527d76e/src/get-options-overrides.ts#L32-L33

The line above is when declarations are not requested at all.

That cwd should arguably be rollup output folder. Problem with that is rollup can have multiple output folders configured, and when not using `useTsconfigDeclarationDir`, plugin will emit declarations and their maps and hand them over to rollup, which then decides where to write them. This has one important effect -- it lets other plugins see and potentially process them.

By setting `useTsconfigDeclarationDir`, user decides to control location from tsconfig and write them out of band into a single folder (which is probably a correct thing to do in most cases).

**Comment by ezolenko** [comment]
We can probably set declarationDir to first rollup output folder in this case and get a significant number of cases right instead of none...
