### ISSUE TITLE
Package resolve should be dependency not devDependency

### ISSUE THREAD

**Issue by DcsMarcRemolt** [ezolenko/rollup-plugin-typescript2#21]
This lib is required in src/index.ts, so whenever I do

```javascript
var tsPlugin = require('rollup-plugin-typescript2');
```

Node gives **Error: Cannot find module 'resolve'** when that package is not randomly installed by another package.

**Comment by ezolenko** [comment]
It is in peerDependencies list though... Did npm complain when you did `npm install`?

**Comment by standy** [comment]
Same issue here, getting error from file `rollup-plugin-typescript2.cjs.js` at line 
```
var resolve = require('resolve');
```
Should be inside try/catch

**Comment by ezolenko** [comment]
Ah, I see they depreciated `peerDependencies` in npm3... It just prints a warning now without installing anything. 

Ok, I'll move them all into dependencies.

**Comment by ezolenko** [comment]
Ok, check in 0.4.4. Hopefully doesn't break existing setups or I fail at versioning...
