### ISSUE TITLE
Export IOptions type from the plugin

### ISSUE THREAD

**Issue by slavafomin** [ezolenko/rollup-plugin-typescript2#210]
Hello!

Thank you for this great plugin!

However, right now, typing declarations are only exporting the plugin function, but not the other useful symbols, like options (i.e. `IOptions`).

The generated typing declarations are looking like this right now:
```
declare const typescript: PluginImpl<Partial<IOptions>>;
export default typescript;
```

As you can see you can't import `IOptions` type directly from it. This makes advanced usage of the plugin harder.

`export { IOptions }` should fix it in the `index.ts`.

**Comment by ezolenko** [comment]
Sure, committed, could you try using github version directly (point npm at it, you should see `0.26.1` printed during build) and let me know if it does what you expect it to do?

**Comment by slavafomin** [comment]
Yep, it's working great, thanks! However, the `IOptions` has a lot of required properties, that are not actually required. I think you should make them optional with `?`.

**Comment by ezolenko** [comment]
That's for convenience internally -- I set all defaults, so there is always a value present. Plugin takes `Partial<IOptions>` as input, not `IOptions`

**Comment by slavafomin** [comment]
Yep, I think the common problem with TypeScript is that you have two sides to an interface: user-facing and an internal one. For simplicity of library users I'm preferring to export interfaces that could be used directly, without applying modifiers like `Partial` to them. But that would be just my recommendation.

Thanks again for updating the types. Please, let me know when you will release it on npm 👍

**Comment by ezolenko** [comment]
@slavafomin I changed export to partial options, let me know if it works better and I do a release.

**Comment by slavafomin** [comment]
@ezolenko I don't believe you've pushed it to the GitHub.

**Comment by ezolenko** [comment]
🤦‍♂ I'll push it in 10-12h

**Comment by ezolenko** [comment]
@slavafomin pushed

**Comment by slavafomin** [comment]
Thanks 👍

**Comment by ezolenko** [comment]
In 0.27.0 now
