### ISSUE TITLE
tsx Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by sanewell92** [ezolenko/rollup-plugin-typescript2#23]
When processing a `tsx` source file I get an error, however if I manually compile with `tsc` I don't get an error.

Environment:

  Windows: 10
  NodeJS: 7.10
  NPM: 5.0.4

Project structure

```
./
  tsconfig.json
  package.json
  rollup.config.js
  src/
    main.ts
    jsx-utils.ts
    components/
      topbar.tsx
```

[Here's a gist with the relevant files](https://gist.github.com/sanewell92/5e93d26a3561c544522a6725a4e3663c) in the above structure.

Error:

```
$ npm run build

> testtsx@1.0.0 build C:\repos\testtsx
> rollup -c

🚨   Cannot read property 'length' of undefined
src\components\topbar.tsx

```

I was using the older typescript plugin, `rollup-plugin-typescript` and just `require`'d in my local typescript, and that worked, but found that this existed so I gave it a whirl.

Let me know if I have something setup wrong! <3<3 Thanks for reading.

**Comment by ezolenko** [comment]
Thanks, I'll check it out.

**Comment by ezolenko** [comment]
Looks like you are the first one to use `"jsx": "preserve"` option. :) I'll fix it later today. 

As for not mangling `h`, rollup itself mangles it (to `h$1` for me). I think you are supposed to use `buble-react-rollup-starter` plugin, not `rollup-plugin-jsx` -- author says it is [deprecated](https://github.com/konsumer/rollup-plugin-jsx).

**Comment by ezolenko** [comment]
Ok, try with 0.4.6

**Comment by sanewell92** [comment]
Thanks for pushing that out! I upgraded to this plugin over the older one, yay!

<details>
<summary>The Dream</summary>

For future reference; tsconfig now has an option `"jsxFactory": "h",` - it seems to eliminate the need for jsx/buble/babel plugin altogether. And since typescript also has a concatenation option with `outFile` - I'll be experimenting with removing rollup as well. (I think I needed to ditch the jsx: preserve and use react target, but it's not really react since I can specify the factory... But it does what I want!)

I'm aiming for a zero dependency, minimal devDependency jsx workflow:

**package.json**
```
"scripts": {
  "build": "tsc",
  "start": "http-server -a localhost",
  "dev": "run-p \"build -- -w\" start"
},
...
"dependencies": {},
"devDependencies": {
  "typescript": "2.4.1",
  "npm-run-all": "4.0.2",
  "http-server": "0.10.0"
}
...
```

Living the dream! Perfect for quickly componentizing static sites. If needed, I can add a small data binding implementation, then I can have something pretty nifty.

I'm just experimenting in a quick personal project with a bare metal approach. No jquery, no framework, just lots of ~stolen~borrowed ideas xD.

</details>

**Comment by lastmjs** [comment]
I'm seeing the same kind of error with this config:

```
const bundle = await rollup.rollup({
        experimentalPreserveModules: true,
        input: tempFilePath,
        plugins: [rollupPluginTypescript2({
            abortOnError: false,
            check: false
        }), commonJSPlugin({
            sourceMap: false
        })]
    });
```

Here is the error output:

```
TypeError: Cannot read property 'length' of undefined
    at new MagicString$1 (/home/lastmjs/development/prendus-app/src/node_modules/rollup/dist/rollup.js:6409:35)
    at Module.setSource (/home/lastmjs/development/prendus-app/src/node_modules/rollup/dist/rollup.js:16521:28)
    at /home/lastmjs/development/prendus-app/src/node_modules/rollup/dist/rollup.js:19375:20
    at <anonymous>

```

**Comment by ezolenko** [comment]
@lastmjs this looks like a different error, could you open a new issue and fill in all the info? (and add more details on `experimentalPreserveModules` option)

**Comment by foisonocean** [comment]
I meet the same error without `experimentalPreserveModules ` option.

rollup: v0.65.0
rollup-plugin-typescript2: v0.16.1
typescript: v3.0.1

**Comment by foisonocean** [comment]
I fixed this issue by downgrade typescript from v3.0.1 to v2.9.2. It seems a compatibility wit typescript 3.0.

**Comment by agilgur5** [comment]
The original issue was fixed, so if you experience a similar error message, please file a new issue and fill out the issue template.
It is easier to track that way for most maintainers. It is also likely a _different_ issue / root cause, just with a similar error message (this a very common JS error).
If you believe the issue is similar or a _regression_, can always reference this issue in your new issue.

Locking this as resolved.
