### ISSUE TITLE
My single line alias file omited during bundle process

### ISSUE THREAD

**Issue by cyclops24** [ezolenko/rollup-plugin-typescript2#238]
#### What happens and why it is wrong
I have some single line files like this:
`index.ts`:
```
export { MyComponent } from '../ParentComponentDir'
```
It's just export some plugin (just a single line file with an export code)
I expect to convert this to the exact same but with js extension after my build process. But It's completely removed from my build folder. (It's omitted by rollup or `rollup-plugin-typescript2` and no file created here with the name of `index.js`)
this file just prepares some alias from simplifying import in the host app.
One approach is that copy the missed files after the build process to build folder and rename the extension from `ts` to `js` but I want to know why these files omitted from rollup.

#### Versions
- typescript: 3.7.2
- rollup: 1.27.4
- rollup-plugin-typescript2: 0.27.0

**Comment by ezolenko** [comment]
rollup will drop anything not used by entry file (look up treeshaking in rollup docs)

You can try adding this explicitly as an `input` in rollup config
