### ISSUE TITLE
Not creating source maps

### ISSUE THREAD

**Issue by ncphillips** [ezolenko/rollup-plugin-typescript2#241]
#### What happens and why it is wrong

When I build my projects source maps are not generated

#### Versions
- typescript:
- rollup:
- rollup-plugin-typescript2:

#### rollup.config.js

The rollup config is part of a [package](https://github.com/tinacms/tinacms/blob/master/packages/%40tinacms/scripts/bin/scripts.js#L89-L114) that we use in a monorepo.

#### tsconfig.json

[Shard tsconfig.json](https://github.com/tinacms/tinacms/blob/master/tsconfig.json)

```json
{
  "compilerOptions": {
    "strict": true,
    "declaration": true,
    "target": "es5",
    "esModuleInterop": true,
    "jsx": "react",
    "lib": ["esnext", "dom"]
  }
}
```

Note that when I add `sourceMap: true` it does not change the behaviour

**Comment by danielvy** [comment]
You need to put `sourcemap: true` in your rollup configuration's output options for source maps to be generated.

**Comment by ezolenko** [comment]
Yep, both tsconfig and rollup need the option enabled
