### ISSUE TITLE
Compatibility with rollup-plugin-dts (declaration bundling)

### ISSUE THREAD

**Issue by trusktr** [ezolenko/rollup-plugin-typescript2#246]
Is it possible to make this work with https://github.com/Swatinem/rollup-plugin-dts?

**Comment by ezolenko** [comment]
Looks like rollup-plugin-dts takes in d.ts as input and starts from there. You could try defining 2 bundles -- one for code using rpt2 plugin, and second one for types, using output types of first bundle as input for the second.
