### ISSUE TITLE
Bug: cannot overide `declaration` option

### ISSUE THREAD

**Issue by Mister-Hope** [ezolenko/rollup-plugin-typescript2#257]
#### What happens and why it is wrong

I am setting `declaration: true` in my tsconfig. And I add

```ts
typescript2({
   tsconfigOverride: {
     declaration: false,
  },
}),
```
in the plugin config. I am expecting the types are no longer generated, but the types still generates.

It seems that the d.ts is generated by tsc, and I think the plugin should checked if the user still wants to generate types before simply calling `tsc` to generate types.

**Env**:
All the plugins are in it's latest version.

**Addtional Info**:

After I set `declaration: false` in tsconfig.json, the types are no longer generated

**Why I need this:**
I am using it along with Vue, and I met issue #224.

Also I have several input files, and the tsconfig is containing the whole project, and I got the whole project's declaration files because of issue #211.

So I am going to generate declaration files by my self, while I need the `declaration: true` in tsconfig.json.

**Comment by ezolenko** [comment]
I think you are missing `compilerOptions` object in override:

```
typescript2({
   tsconfigOverride: {
       compilerOptions: {
         declaration: false,
    },
  },
}),
```

**Comment by Mister-Hope** [comment]
Thanks, my fault🌚
