### ISSUE TITLE
Build declaration in a single file

### ISSUE THREAD

**Issue by mlbonniec** [ezolenko/rollup-plugin-typescript2#259]
#### What happens and why it is wrong
Hi, thanks for this plugin. But I've a little problem while building my library. I've `declaration` set to `true` in my `tsconfig.json`, so the plugin generates declaration files. The problem is that declaration are created following the folder structure, in several files. Is it possible to make the declaration built in a single file at the root of the build folder?

#### Environment
macOS Big Sur 11.1

##### Versions
rollup: ^2.36.1 => 2.36.1 
rollup-plugin-typescript2: ^0.29.0 => 0.29.0 
typescript: ^4.1.3 => 4.1.3

**Comment by ezolenko** [comment]
There is a tool that can merge declaration files, you can use that as a separate build step, for example ts-merge (haven't used it)
