### ISSUE TITLE
`microbundle-crl` uses old version of TS incompatible with template literal types

### ISSUE THREAD

**Issue by yaldram** [ezolenko/rollup-plugin-typescript2#263]
### What happens and why it is wrong
I am using `microbundle-crl` for compiling my React TypeScript Project, compiling the code fails when I am using TypeScript Template Types like ```export type SpaceThemeProps = `$${keyof typeof theme['space']}` | (string & {})```

### Error
I get the following error when  I run  `microbundle-crl --no-compress --format modern,cjs` - 
`semantic error TS2305: Module '"../../../../stitches.config"' has no exported member 'SpaceThemeProps'.`

##### Versions

```text
npmPackages:
    typescript: ^4.1.5 => 4.1.5
```

#### rollup.config.js

<details>
  <summary>`rollup.config.js`: </summary>

</details>

#### tsconfig.json

<details>
  <summary>`tsconfig.json`: </summary>
  
```json5
{
  "compilerOptions": {
    "outDir": "dist",
    "module": "esnext",
    "lib": ["dom", "esnext"],
    "moduleResolution": "node",
    "jsx": "react",
    "sourceMap": true,
    "declaration": true,
    "esModuleInterop": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "allowSyntheticDefaultImports": true,
    "target": "es5",
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true
  },
  "include": ["src"],
  "exclude": ["node_modules", "dist", "example", "**/*.stories.tsx"]
}
```

</details>

#### package.json

<details>
  <summary>`package.json`: </summary>

</details>

#### plugin output with verbosity 3

<details>
  <summary>plugin output with verbosity 3: </summary>

</details>

**Comment by yaldram** [comment]
####  WorkAround
- I added the following in my package.json  - 
  ```javascript
  "resolutions": {
      "**/typescript": "^4.1.5",
      "**/@typescript-eslint/eslint-plugin": "^4.15.1",
      "**/@typescript-eslint/parser": "^4.15.1"
    }
  ```
 - Then I ran the following 
 yarn add --dev typescript@latest @typescript-eslint/eslint-plugin@latest @typescript-eslint/parser@latest

And my build worked.

**Comment by ezolenko** [comment]
So you basically updated typescript version?

**Comment by yaldram** [comment]
@ezolenko Hello Sir, yes you are right first I just updated the typscript version in my package.json along with the above 2 packages and then ran `yarn install` but it failed to compile. Then I had to use the above mentioned hack.

**Comment by hanayashiki** [comment]
same problem here, the resolutions changed to `{ "**/typescript": "^4.2.4" }` works for me

**Comment by agilgur5** [comment]
This is an issue with [`microbundle-crl`](https://www.npmjs.com/package/microbundle-crl), which has not been updated in ~2 years, not this plugin.

`microbundle-crl` uses an old version of this plugin under-the-hood, but this plugin does not specify a TS version, TS is listed as a peerDep. `microbundle-crl`, on the other hand, does specify an [old TS version](https://github.com/transitive-bullshit/microbundle/blob/2d43ee15ffe1952fe82656adb7520de296991d53/package.json#L104), specifically TS v3, before TS v4.

Closing as this is out-of-scope for this plugin and is a downstream issue in `microbundle-crl`, not here.
