### ISSUE TITLE
Local TypeScript from node_modules

### ISSUE THREAD

**Issue by rvikmanis** [ezolenko/rollup-plugin-typescript2#27]
Is it somehow possible to use project-local `typescript`?

**Comment by ezolenko** [comment]
I think it does that by default? Plugin does `import "typescript"`. If you set verbosity to high enough level (2 or 3), it will print typescript version it picked up, if you have different local and global versions, you should be able to see which one is used.

If you have a different name for typescript though...

**Comment by rvikmanis** [comment]
I think it always loads the version you have specified in package.json of
your project, i.e latest minor at 2.x

**Comment by ezolenko** [comment]
Ok, I added `typescript` option (in master), try requiring your version of typescript and passing that in.

**Comment by rvikmanis** [comment]
Seems to work. Thanks!
