### ISSUE TITLE
Material UI as peerDependency not working

### ISSUE THREAD

**Issue by andrebnassis** [ezolenko/rollup-plugin-typescript2#277]
#### What happens and why it is wrong
Rollup build failed when "@material-ui/core" is  as peerDependency.

[!] (plugin rpt2) Error: //rollup-material-ui-peerDependencies-error/src/TestComponent/TestComponent.tsx(2,28): semantic error TS2307: Cannot find module '@material-ui/core' or its corresponding type declarations.

PS: I already saw this issue related ([https://github.com/ezolenko/rollup-plugin-typescript2/issues/198](https://github.com/ezolenko/rollup-plugin-typescript2/issues/198)) and the solution doesn't fit for me. I've also opened a question on stackoverflow to explain all my research to find a solution for it. You can see it here:
[https://stackoverflow.com/questions/68581137/is-it-possible-to-have-material-ui-as-peerdependency-but-keep-its-types-as-devde](https://stackoverflow.com/questions/68581137/is-it-possible-to-have-material-ui-as-peerdependency-but-keep-its-types-as-devde)

<hr/>

#### Environment

Here it is a replicated scenario:
[https://github.com/andrebnassis/rollup-material-ui-peerDependencies-error](https://github.com/andrebnassis/rollup-material-ui-peerDependencies-error)

1. clone the repository
2. yarn && yarn build
Then the following error appears:
[!] (plugin rpt2) Error: //rollup-material-ui-peerDependencies-error/src/TestComponent/TestComponent.tsx(2,28): semantic error TS2307: Cannot find module '@material-ui/core' or its corresponding type declarations.
##### Versions

```text
  npmPackages:
    rollup: ^2.36.1 => 2.55.1 
    rollup-plugin-typescript2: ^0.29.0 => 0.29.0 
    typescript: ^4.1.3 => 4.3.5 
```

#### rollup.config.js

<details>
  <summary>`rollup.config.js`: </summary>

import peerDepsExternal from "rollup-plugin-peer-deps-external";
import resolve from "@rollup/plugin-node-resolve";
import commonjs from "@rollup/plugin-commonjs";
import typescript from "rollup-plugin-typescript2";
import postcss from "rollup-plugin-postcss";
import copy from "rollup-plugin-copy";

const packageJson = require("./package.json");

export default {
  input: "src/index.ts",
  output: [
    {
      file: packageJson.main,
      format: "cjs",
      sourcemap: true
    },
    {
      file: packageJson.module,
      format: "esm",
      sourcemap: true
    }
  ],
  plugins: [
    peerDepsExternal(),
    resolve(),
    commonjs(),
    typescript({ useTsconfigDeclarationDir: true, verbosity:3 }),
    postcss(),
    copy({
      targets: [
        {
          src: "src/variables.scss",
          dest: "build",
          rename: "variables.scss"
        },
        {
          src: "src/typography.scss",
          dest: "build",
          rename: "typography.scss"
        }
      ]
    })
  ],
  external:[
    "react",
    "react-dom",
    "@material-ui/core"
  ]
};

</details>

#### tsconfig.json

<details>
  <summary>`tsconfig.json`: </summary>

{
  "compilerOptions": {
    "rootDir": "src",
    "declaration": true,
    "declarationDir": "build",
    "module": "esnext",
    "target": "es5",
    "lib": ["es6", "dom", "es2016", "es2017"],
    "sourceMap": true,
    "jsx": "react",
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true
  },
  "include": ["src/**/*"],
  "exclude": [
    "node_modules",
    "build",
    "storybook-static",
    "src/**/*.stories.tsx",
    "src/**/*.test.tsx"
  ]
}

</details>

#### package.json

<details>
  <summary>`package.json`: </summary>

{
  "name": "react-component-library",
  "version": "1.0.0",
  "main": "build/index.js",
  "module": "build/index.esm.js",
  "files": [
    "build"
  ],
  "types": "build/index.d.ts",
  "description": "A skeleton to create your own React component library using Rollup, TypeScript, Sass and Storybook",
  "scripts": {
    "build": "rollup -c",
    "test": "jest",
    "test:watch": "jest --watch",
    "storybook": "start-storybook -p 6006",
    "storybook:export": "build-storybook",
    "generate": "node ./util/create-component",
    "prepublishOnly": "npm run build"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/HarveyD/react-component-library.git"
  },
  "keywords": [
    "React",
    "Component",
    "Library",
    "Rollup",
    "Typescript",
    "Sass",
    "Storybook"
  ],
  "author": "Harvey Delaney",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/HarveyD/react-component-library/issues"
  },
  "homepage": "https://github.com/HarveyD/react-component-library#readme",
  "peerDependencies": {
    "react": ">=16.8.0",
    "react-dom": ">=16.8.0",
    "@material-ui/core": "^4.12.3"
  },
  "devDependencies": {
    "@babel/core": "^7.12.10",
    "@rollup/plugin-commonjs": "^17.0.0",
    "@rollup/plugin-node-resolve": "^11.0.1",
    "@storybook/react": "^6.1.12",
    "@testing-library/jest-dom": "^5.5.0",
    "@testing-library/react": "^11.2.3",
    "@types/jest": "^24.0.24",
    "@types/react": "^16.9.12",
    "@types/react-dom": "^16.9.8",
    "babel-loader": "^8.1.0",
    "babel-preset-react-app": "^10.0.0",
    "identity-obj-proxy": "^3.0.0",
    "jest": "^26.6.3",
    "node-sass": "^5.0.0",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "rollup": "^2.36.1",
    "rollup-plugin-copy": "^3.3.0",
    "rollup-plugin-peer-deps-external": "^2.2.0",
    "rollup-plugin-postcss": "^3.1.2",
    "rollup-plugin-typescript2": "^0.29.0",
    "sass-loader": "^10.1.1",
    "ts-jest": "^26.4.4",
    "typescript": "^4.1.3"
  },
  "dependencies": {
  }
}

</details>

#### plugin output with verbosity 3

<details>
  <summary>plugin output with verbosity 3: </summary>

rollup -c

src/index.ts → build/index.js, build/index.esm.js...
rpt2: built-in options overrides: {
    "noEmitHelpers": false,
    "importHelpers": true,
    "noResolve": false,
    "noEmit": false,
    "inlineSourceMap": false,
    "outDir": "/home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/.cache/rollup-plugin-typescript2/placeholder",
    "moduleResolution": 2,
    "allowNonTsExtensions": true
}
rpt2: parsed tsconfig: {
    "options": {
        "rootDir": "/home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/src",
        "declaration": true,
        "declarationDir": "/home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/build",
        "module": 99,
        "target": 1,
        "lib": [
            "lib.es2015.d.ts",
            "lib.dom.d.ts",
            "lib.es2016.d.ts",
            "lib.es2017.d.ts"
        ],
        "sourceMap": true,
        "jsx": 2,
        "moduleResolution": 2,
        "allowSyntheticDefaultImports": true,
        "esModuleInterop": true,
        "configFilePath": "/home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/tsconfig.json",
        "noEmitHelpers": false,
        "importHelpers": true,
        "noResolve": false,
        "noEmit": false,
        "inlineSourceMap": false,
        "outDir": "/home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/.cache/rollup-plugin-typescript2/placeholder",
        "allowNonTsExtensions": true
    },
    "fileNames": [
        "/home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/src/index.ts",
        "/home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/src/TestComponent/TestComponent.tsx",
        "/home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/src/TestComponent/TestComponent.types.ts",
        "/home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/src/TestComponent/index.ts"
    ],
    "typeAcquisition": {
        "enable": false,
        "include": [],
        "exclude": []
    },
    "raw": {
        "compilerOptions": {
            "rootDir": "src",
            "declaration": true,
            "declarationDir": "build",
            "module": "esnext",
            "target": "es5",
            "lib": [
                "es6",
                "dom",
                "es2016",
                "es2017"
            ],
            "sourceMap": true,
            "jsx": "react",
            "moduleResolution": "node",
            "allowSyntheticDefaultImports": true,
            "esModuleInterop": true
        },
        "include": [
            "src/**/*"
        ],
        "exclude": [
            "node_modules",
            "build",
            "storybook-static",
            "src/**/*.stories.tsx",
            "src/**/*.test.tsx"
        ],
        "compileOnSave": false
    },
    "errors": [],
    "wildcardDirectories": {
        "/home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/src": 1
    },
    "compileOnSave": false
}
rpt2: typescript version: 4.3.5
rpt2: tslib version: 2.0.1
rpt2: rollup version: 2.55.1
rpt2: rollup-plugin-typescript2 version: 0.29.0
rpt2: plugin options:
{
    "useTsconfigDeclarationDir": true,
    "verbosity": 3,
    "check": true,
    "clean": false,
    "cacheRoot": "/home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/.cache/rollup-plugin-typescript2",
    "include": [
        "*.ts+(|x)",
        "**/*.ts+(|x)"
    ],
    "exclude": [
        "*.d.ts",
        "**/*.d.ts"
    ],
    "abortOnError": true,
    "rollupCommonJSResolveHack": false,
    "tsconfigOverride": {},
    "transformers": [],
    "tsconfigDefaults": {},
    "objectHashIgnoreUnknownHack": false,
    "cwd": "/home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error",
    "typescript": "version 4.3.5"
}
rpt2: rollup config:
{
    "input": "src/index.ts",
    "plugins": [
        {
            "name": "peer-deps-external"
        },
        {
            "name": "node-resolve"
        },
        {
            "name": "commonjs"
        },
        {
            "name": "rpt2"
        },
        {
            "name": "postcss"
        },
        {
            "name": "copy"
        },
        {
            "name": "stdin"
        }
    ],
    "output": [
        {
            "file": "build/index.js",
            "format": "cjs",
            "plugins": [],
            "sourcemap": true
        },
        {
            "file": "build/index.esm.js",
            "format": "esm",
            "plugins": [],
            "sourcemap": true
        }
    ]
}
rpt2: tsconfig path: /home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/tsconfig.json
rpt2: included:
[
    "*.ts+(|x)",
    "**/*.ts+(|x)"
]
rpt2: excluded:
[
    "*.d.ts",
    "**/*.d.ts"
]
rpt2: Ambient types:
rpt2:     /home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/@types/aria-query/index.d.ts
rpt2:     /home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/@types/babel__core/index.d.ts
rpt2:     /home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/@types/babel__generator/index.d.ts
rpt2:     /home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/@types/babel__template/index.d.ts
rpt2:     /home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/@types/babel__traverse/index.d.ts
rpt2:     /home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/@types/braces/index.d.ts
rpt2:     /home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/@types/color-convert/index.d.ts
rpt2:     /home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/@types/color-name/index.d.ts
rpt2:     /home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/@types/estree/index.d.ts
rpt2:     /home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/@types/fs-extra/index.d.ts
rpt2:     /home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/@types/glob/index.d.ts
rpt2:     /home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/@types/glob-base/index.d.ts
rpt2:     /home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/@types/graceful-fs/index.d.ts
rpt2:     /home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/@types/hast/index.d.ts
rpt2:     /home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/@types/html-minifier-terser/index.d.ts
rpt2:     /home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/@types/is-function/index.d.ts
rpt2:     /home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/@types/istanbul-lib-coverage/index.d.ts
rpt2:     /home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/@types/istanbul-lib-report/index.d.ts
rpt2:     /home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/@types/istanbul-reports/index.d.ts
rpt2:     /home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/@types/jest/index.d.ts
rpt2:     /home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/@types/json-schema/index.d.ts
rpt2:     /home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/@types/markdown-to-jsx/index.d.ts
rpt2:     /home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/@types/mdast/index.d.ts
rpt2:     /home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/@types/micromatch/index.d.ts
rpt2:     /home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/@types/minimatch/index.d.ts
rpt2:     /home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/@types/node/index.d.ts
rpt2:     /home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/@types/node-fetch/index.d.ts
rpt2:     /home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/@types/normalize-package-data/index.d.ts
rpt2:     /home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/@types/npmlog/index.d.ts
rpt2:     /home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/@types/overlayscrollbars/index.d.ts
rpt2:     /home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/@types/parse-json/index.d.ts
rpt2:     /home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/@types/parse5/index.d.ts
rpt2:     /home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/@types/prettier/index.d.ts
rpt2:     /home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/@types/pretty-hrtime/index.d.ts
rpt2:     /home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/@types/prop-types/index.d.ts
rpt2:     /home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/@types/q/index.d.ts
rpt2:     /home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/@types/qs/index.d.ts
rpt2:     /home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/@types/reach__router/index.d.ts
rpt2:     /home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/@types/react/index.d.ts
rpt2:     /home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/@types/react-dom/index.d.ts
rpt2:     /home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/@types/react-syntax-highlighter/index.d.ts
rpt2:     /home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/@types/resolve/index.d.ts
rpt2:     /home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/@types/scheduler/index.d.ts
rpt2:     /home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/@types/source-list-map/index.d.ts
rpt2:     /home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/@types/stack-utils/index.d.ts
rpt2:     /home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/@types/tapable/index.d.ts
rpt2:     /home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/@types/testing-library__jest-dom/index.d.ts
rpt2:     /home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/@types/uglify-js/index.d.ts
rpt2:     /home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/@types/unist/index.d.ts
rpt2:     /home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/@types/webpack/index.d.ts
rpt2:     /home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/@types/webpack-env/index.d.ts
rpt2:     /home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/@types/webpack-sources/index.d.ts
rpt2:     /home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/@types/yargs/index.d.ts
rpt2:     /home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/@types/yargs-parser/index.d.ts
rpt2: ambient types changed, redoing all semantic diagnostics
rpt2: transpiling '/home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/src/index.ts'
rpt2:     cache: '/home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/.cache/rollup-plugin-typescript2/rpt2_145486f490525aa885e64e8edf27cb541e65d0c8/code/cache/e05df8d76de9af07ab9b6def73df12d7eac5dadb'
rpt2:     cache miss
rpt2:     cache: '/home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/.cache/rollup-plugin-typescript2/rpt2_145486f490525aa885e64e8edf27cb541e65d0c8/syntacticDiagnostics/cache/e05df8d76de9af07ab9b6def73df12d7eac5dadb'
rpt2:     cache miss
rpt2:     cache: '/home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/.cache/rollup-plugin-typescript2/rpt2_145486f490525aa885e64e8edf27cb541e65d0c8/semanticDiagnostics/cache/e05df8d76de9af07ab9b6def73df12d7eac5dadb'
rpt2:     cache miss
rpt2: generated declarations for '/home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/src/index.ts'
rpt2: dependency '/home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/src/TestComponent/index.ts'
rpt2:     imported by '/home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/src/index.ts'
rpt2: resolving './TestComponent' imported by '/home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/src/index.ts'
rpt2:     to '/home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/src/TestComponent/index.ts'
rpt2: transpiling '/home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/src/TestComponent/index.ts'
rpt2:     cache: '/home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/.cache/rollup-plugin-typescript2/rpt2_145486f490525aa885e64e8edf27cb541e65d0c8/code/cache/10024918a8f4dd27e98df73f999774fc6bb9623f'
rpt2:     cache miss
rpt2:     cache: '/home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/.cache/rollup-plugin-typescript2/rpt2_145486f490525aa885e64e8edf27cb541e65d0c8/syntacticDiagnostics/cache/10024918a8f4dd27e98df73f999774fc6bb9623f'
rpt2:     cache miss
rpt2:     cache: '/home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/.cache/rollup-plugin-typescript2/rpt2_145486f490525aa885e64e8edf27cb541e65d0c8/semanticDiagnostics/cache/10024918a8f4dd27e98df73f999774fc6bb9623f'
rpt2:     cache miss
rpt2: generated declarations for '/home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/src/TestComponent/index.ts'
rpt2: dependency '/home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/src/TestComponent/TestComponent.tsx'
rpt2:     imported by '/home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/src/TestComponent/index.ts'
rpt2: resolving './TestComponent' imported by '/home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/src/TestComponent/index.ts'
rpt2:     to '/home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/src/TestComponent/TestComponent.tsx'
rpt2: transpiling '/home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/src/TestComponent/TestComponent.tsx'
rpt2:     cache: '/home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/.cache/rollup-plugin-typescript2/rpt2_145486f490525aa885e64e8edf27cb541e65d0c8/code/cache/4b0364bc4ff1d3bc060ae0b18227faa193943ab6'
rpt2:     cache miss
rpt2:     cache: '/home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/.cache/rollup-plugin-typescript2/rpt2_145486f490525aa885e64e8edf27cb541e65d0c8/syntacticDiagnostics/cache/4b0364bc4ff1d3bc060ae0b18227faa193943ab6'
rpt2:     cache miss
rpt2:     cache: '/home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/.cache/rollup-plugin-typescript2/rpt2_145486f490525aa885e64e8edf27cb541e65d0c8/semanticDiagnostics/cache/4b0364bc4ff1d3bc060ae0b18227faa193943ab6'
rpt2:     cache miss
[!] (plugin rpt2) Error: /home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/src/TestComponent/TestComponent.tsx(2,28): semantic error TS2307: Cannot find module '@material-ui/core' or its corresponding type declarations.
src/TestComponent/TestComponent.tsx
Error: /home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/src/TestComponent/TestComponent.tsx(2,28): semantic error TS2307: Cannot find module '@material-ui/core' or its corresponding type declarations.
    at error (/home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/rollup/dist/shared/rollup.js:151:30)
    at throwPluginError (/home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/rollup/dist/shared/rollup.js:19340:12)
    at Object.error (/home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/rollup/dist/shared/rollup.js:19992:20)
    at Object.error (/home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/rollup/dist/shared/rollup.js:19516:38)
    at RollupContext.error (/home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/rollup-plugin-typescript2/src/rollupcontext.ts:37:18)
    at /home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/rollup-plugin-typescript2/src/print-diagnostics.ts:41:11
    at arrayEach (/home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/rollup-plugin-typescript2/node_modules/lodash/lodash.js:516:11)
    at Function._.each [as forEach] (/home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/rollup-plugin-typescript2/node_modules/lodash/lodash.js:9368:14)
    at printDiagnostics (/home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/rollup-plugin-typescript2/src/print-diagnostics.ts:9:2)
    at Object.transform (/home/andrebnassis/MyProjects/rollup-material-ui-peerDependencies-error/node_modules/rollup-plugin-typescript2/src/index.ts:244:5)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
</details>

**Comment by andrebnassis** [comment]
I created a script that I call 'rollup -c' twice, so on the first-time material-ui is NOT included as peerDependencies and at the second time material-ui is included as peerDependencies, then the package build perfectly, but it is a workaround. I would like to find a real solution for this problem.

**Comment by andrebnassis** [comment]
I solved this problem by setting all my peerDependencies as devDependencies (https://github.com/HarveyD/react-component-library/issues/40)

**Comment by artemis-prime** [comment]
@andrebnassis That is NOT a solution. That is a workaround.  How do you justify closing this!?

**Comment by andrebnassis** [comment]
> @andrebnassis That is NOT a solution. That is a workaround. How do you justify closing this!?

Hello @artemis-prime , I cannot understand why setting peerDependencies as devDependencies is a workaround. This solution conceptually make sense in my head. But is it a bad practice? 

Anyway, feel free to open an issue with more detailed information if you think this is a bug (I really don't have sufficient knowledge to argue if this is a workaround or final solution. I'm just following this approach since @TimEnglart answer me - https://github.com/HarveyD/react-component-library/issues/40#issuecomment-892292062).

**Comment by agilgur5** [comment]
### peerDeps and devDeps

Setting peerDeps to also be devDeps is standard practice and usually _necessary_ when doing development things (hence the name devDeps) like testing, or in this case, using their type information.

peerDeps of your own package are not automatically installed as far as I know (unless newer NPM versions changed that), that only happens for _consumers_ of packages in newer versions of NPM (and some older versions of NPM too). If they were auto-installed, they'd be added as devDeps too.

> @andrebnassis That is NOT a solution. That is a workaround. How do you justify closing this!?

No, that is the correct solution and definitely not a workaround. You have them as _both_ peerDeps and devDeps (often a looser range for peerDeps than devDeps and maybe a matrix in your CI to handle ensuring that different versions are compatible).

In fact, https://github.com/ezolenko/rollup-plugin-typescript2/issues/198#issuecomment-562193649 is the workaround (adding stub type information instead of the actual dependency)

### `tsc` behavior, not a bug

With regard to the opening comment, `tsc` will also error in the same way on this code as the module and typing information were indeed missing as it was not installed as a devDep and therefore not available in `node_modules`. That error is correct and accurate.

As such this isn't a bug in rpt2 and correct behavior.

Thanks for providing a solution for other readers as well as a detailed repro!
