### ISSUE TITLE
Declared namespace not available in bundle

### ISSUE THREAD

**Issue by mkappelhof** [ezolenko/rollup-plugin-typescript2#278]
#### What happens and why it is wrong

Not 100% sure if this issue belongs here, but I use Storybook to build a component library and declared a global namespace to easily access generic types without having to import them per file. This works fine in Storybook, but when compiled with Rollup & rollup-plugin-typescript2 the generated `.d.ts` files of the components can't access the namespace and i don't see it anywhere in the bundle.

I've created the following `index.d.ts` file in my project

```javascript
declare namespace MyNameSpace{
  type DefaultDataObj = { label?: string, value: string }

  type GenericPropTypes = Pick<React.HTMLAttributes<HTMLDivElement>,
    'className'
  >

  type DynamicObjectType<T> = {
    [key: string]: T
  }
}
```

I then have a `Button` component that looks (stripped) like this

```tsx
interface ButtonProps extends MyNameSpace.GenericPropTypes{
  type: 'primary' | 'ghost'
  children?: React.ReactNode,
}

export const Button = ({ type, className, children }: ButtonProps): JSX.Element => (
  <button type="button" className={className ?? ''}>{ children }</button>
)
```

The generated `Button.d.ts` in the bundle then looks like this

```ts
import React from 'react';
export interface ButtonProps extends MyNameSpace.GenericPropTypes {
    type?: 'primary' | 'ghost';
    children?: React.ReactNode;
}
export declare const Button: ({ type, className, children }: ButtonProps) => JSX.Element;
```

With the error `Cannot find namespace MyNameSpace`

##### Versions

```text
npmPackages:
    rollup: ^2.41.5 => 2.44.0
    rollup-plugin-typescript2: ^0.30.0 => 0.30.0
    typescript: ^4.1.5 => 4.2.3
```

#### rollup.config.js

<details>
  <summary>`rollup.config.js`: </summary>

```js
export default {
  input: 'src/index.ts',
  output: [{
    file: pckg.main,
    format: 'cjs',
    sourcemap: true
  }, {
    file: pckg.module,
    format: 'esm',
    sourcemap: true
  }],
  plugins: [
    typescript(),
    sassPlugin({
      runtime: sass,
      output: 'bundle.css'
      options: { data: '@import "./src/style/variables";@import "./src/style/mixins";' }
    }),
  ],
  external: [
    ...Object.keys(pckg.dependencies || {}),
    ...Object.keys(pckg.peerDependencies || {})
  ]
}
```

</details>

#### tsconfig.json

<details>
  <summary>`tsconfig.json`: </summary>

```json5
{
  "compilerOptions": {
    "baseUrl": "src/",
    "declaration": true,
    "esModuleInterop": true,
    "jsx": "react",
    "module": "esnext",
    "moduleResolution": "node",
    "noImplicitAny": true,
    "outDir": "./lib",
    "preserveConstEnums": true,
    "removeComments": true,
    "sourceMap": true,
    "target": "esnext", 
  },
  "include": [
    "src/",
    "types/declarations.d.ts"
  ],
  "exclude": [
    "build",
    "coverage",
    "cypress",
    "lib",
    "node_modules",
    "src/stories/**"
  ]
}
```

</details>

#### package.json

<details>
  <summary>`package.json`: </summary>

</details>

#### plugin output with verbosity 3

<details>
  <summary>plugin output with verbosity 3: </summary>

</details>

**Comment by ezolenko** [comment]
index.d.ts might be excluded by typescript explicitly based on its name (because you have index.ts as well), ts does this magically to avoid using build output as part of build input when project structure dumps output into source tree. Try naming the file differently.

**Comment by agilgur5** [comment]
I think this would come out similar if using `tsc`, so I'm not sure that this is a bug with rpt2.

From the code sample given, `MyNameSpace` isn't directly `import`ed, so I believe that is correct output.

In this case, I believe it depends on TS to detect `index.d.ts` as an ambient typing (similar to `@types/`).
Then, I'm guessing you're getting the `Cannot find namespace` error when trying to import the compiled component. If TS can't detect the same ambient typings when you're importing, that would be a correct error.

I believe this can be resolved by publishing the `index.d.ts` file with your component (e.g. with `rollup-plugin-copy` or something).
It might also be possible to rename it as a `.ts` file instead and `import type` from it, which would be simpler (I don't 100% remember if that works though)

**Comment by sdwvit** [comment]
I stumbled upon this issue as well. My understanding is that rollup decides to include file into a bundle if it is imported somewhere in a chain of imports starting with the entry file. Because of this, and the fact that d.ts are made to avoid importing shared types, d.ts are not included into the bundle.
