### ISSUE TITLE
The `dist/_virtual/_tslib.js` doesn't play nice with Node and ES modules

### ISSUE THREAD

**Issue by NSeydoux** [ezolenko/rollup-plugin-typescript2#282]
#### What happens and why it is wrong

This feels like an extension to the issue documented in https://github.com/ezolenko/rollup-plugin-typescript2/pull/170. I'll reproduce the PR comment for context: 
> Rollup has preserveModules option which is used to skip flat bundling and writing instead to disk a directory structure resembling the input one. This plugin makes tslib a "virtual" module by default - this means that it virtually creates an input file for Rollup to consume, but obviously it's not part of the input directory structure. To deal with it in combination with preserveModules Rollup creates a _virtual output directory and put such modules in it. As filename of such a virtual module it uses "as is" the given identifier - in this case \0tslib. Problem is that it doesn't add any extension to it and this trips other tools if you don't include the extension in the virtual identifier - i.e. webpack and it's resolving algorithm.

In my use case, I'd like the `dist/_virtual/_tslib.js` file to have a `.mjs` extension so that it is recognized as an ES module by NodeJS when doing submodule exports. I guess the easiest approach would be to add a configuration option for the plugin to specify the extension, with `.js` as a default. If you're happy with the suggestion, I can look into submitting a PR (I worked around the issue for the time being). Using the rollup configuration would be fancier, but I'd not be sure how to approach it.

##### Versions

```text
rollup: ^2.56.2 => 2.56.2
rollup-plugin-typescript2: ^0.30.0 => 0.30.0
typescript: ^4.3.5 => 4.3.5
```

#### rollup.config.js

<details>
  <summary>`rollup.config.js`: </summary>

```
import pkg from "./package.json";
import typescript from "rollup-plugin-typescript2";

export default {
  input: "./src/index.ts",
  output: [
    {
      file: pkg.main,
      format: "cjs",
    },
    {
      file: pkg.module,
      entryFileNames: "[name].es.js",
      format: "esm",
    },
    {
      dir: "dist",
      entryFileNames: "[name].mjs",
      format: "esm",
      preserveModules: true,
    },
    {
      dir: "umd",
      format: "umd",
      name: "SolidClientVc",
    },
  ],
  plugins: [
    typescript({
      // Use our own version of TypeScript, rather than the one bundled with the plugin:
      typescript: require("typescript"),
      tsconfigOverride: {
        compilerOptions: {
          module: "esnext",
        },
      },
    }),
  ],
  external: ["cross-fetch", "http-link-header"],
};

```

</details>

#### tsconfig.json

<details>
  <summary>`tsconfig.json`: </summary>

Not sure this is relevant, but better too much information than not enough right ^^

```
{
  "compilerOptions": {
    "target": "es2017",
    "module": "commonjs",
    "lib": ["es2015", "dom"],
    "declaration": true,
    "outDir": ".", 
    "rootDir": "src",
    "strict": true,                           /* Enable all strict type-checking options. */
    "types": ["jest"],                           /* Type declaration files to be included in compilation. */
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "stripInternal": true,                 /* Do not emit declarations for code that has an @internal annotation in it’s JSDoc comment. */
    "skipLibCheck": true, /* temporarily skip lib checks due to a solid-client bug */
  },
  "include": ["src/**/*.ts", ".eslintrc.js"],
  "exclude": []
}
```

</details>

#### package.json

<details>
  <summary>`package.json`: </summary>
```
{
  "name": "@inrupt/solid-client-vc",
  "description": "A library to act as a client to a server implementing the W3C VC HTTP APIs.",
  "version": "0.1.0",
  "license": "MIT",
  "scripts": {
    "build": "rollup --config rollup.config.js",
    "prepublishOnly": "npm run build",
    "prepare": "husky install"
  },
  "homepage": "https://docs.inrupt.com/developer-tools/javascript/client-libraries/",
  "main": "dist/index.js",
  "module": "dist/index.es.js",
  "types": "dist/index.d.ts",
  "exports": {
    ".": {
      "require": "./dist/index.js",
      "import": "./dist/index.mjs"
    },
    "./common": "./dist/common/common.mjs",
    "./issue": "./dist/issue/issue.mjs",
    "./derive": "./dist/lookup/derive.mjs",
    "./revoke": "./dist/revoke/revoke.mjs"
  },
  "files": [
    "dist",
    "src",
    "umd"
  ],
  "sideEffects": false,
  "repository": {
    "type": "git",
    "url": "https://github.com/inrupt/solid-client-vc-js.git"
  },
  "devDependencies": {
    "@inrupt/eslint-config-base": "^0.2.0-alpha.1",
    "@inrupt/eslint-config-lib": "^0.2.0-alpha.1",
    "@inrupt/solid-client-authn-node": "^1.11.2",
    "@skypack/package-check": "^0.2.2",
    "@testing-library/testcafe": "^4.4.0",
    "@types/dotenv-flow": "^3.1.1",
    "@types/jest": "^27.0.1",
    "@types/node": "^16.6.2",
    "@typescript-eslint/eslint-plugin": "^3.10.1",
    "@typescript-eslint/parser": "^3.10.1",
    "dotenv-flow": "^3.2.0",
    "eslint": "^7.32.0",
    "eslint-config-airbnb-base": "^14.2.1",
    "eslint-config-prettier": "^6.15.0",
    "eslint-plugin-header": "^3.1.1",
    "eslint-plugin-import": "^2.24.0",
    "eslint-plugin-jest": "^23.20.0",
    "eslint-plugin-license-header": "^0.2.0",
    "eslint-plugin-prettier": "^3.4.0",
    "fast-check": "^2.17.0",
    "husky": "^5.2.0",
    "jest": "^27.1.0",
    "license-checker": "^25.0.1",
    "lint-staged": "^10.2.9",
    "prettier": "2.2.1",
    "rollup": "^2.56.2",
    "rollup-plugin-typescript2": "^0.30.0",
    "testcafe": "^1.15.2",
    "ts-jest": "^27.0.5",
    "typedoc": "^0.20.37",
    "typedoc-plugin-markdown": "^3.10.4",
    "typescript": "^4.3.5"
  },
  "dependencies": {
    "@types/http-link-header": "^1.0.3",
    "cross-fetch": "^3.1.4",
    "http-link-header": "^1.0.3"
  },
  "lint-staged": {
    "*.{js,jsx,ts,tsx}": "eslint --cache --fix",
    "*.{ts,tsx,js,jsx,css,md,mdx}": "prettier --write"
  },
  "publishConfig": {
    "access": "public"
  }
}

```
</details>

#### plugin output with verbosity 3

<details>
  <summary>plugin output with verbosity 3: </summary>

See attachment.
[output.log](https://github.com/ezolenko/rollup-plugin-typescript2/files/7136853/output.log)

</details>

**Comment by ezolenko** [comment]
Sure, this sounds reasonable, please make a PR. I recall \0 in front was to hide it from the other plugins, but I'm not sure why that was necessary, official typescript plugin did this, so I did it too. Setting mjs extension might serve the same purpose.

**Comment by NSeydoux** [comment]
It looks like the issue has been resolved another way, as the bug is no longer manifesting. I'll close the issue for now, and re-open if relevant.

**Comment by agilgur5** [comment]
This might be feasible to auto-interpret from `tsconfig` `module` and Rollup's `output.format` instead of requiring a new config option. `output.format` is probably necessary to interpret as, for example, one probably wouldn't use `.mjs` for a CJS output.

Since this has been resolved differently (per above), doesn't seem to have any other demand, and is an edge-case edge-case (using `preserveModules` + `tslib`), doesn't seem like there's a need for this feature right now.
