### ISSUE TITLE
`import { jsx } from '@emotion/react'` isn't working as intended -- use `jsx: "preserve"`

### ISSUE THREAD

**Issue by HiWayne** [ezolenko/rollup-plugin-typescript2#299]
#### What happens and why it is wrong

I want use css prop of emotion in React tsx:

```ts
/** @jsx jsx */
import { jsx } from '@emotion/react';
```

But the comment: `/** @jsx jsx */` was removed and the line of `jsx` was tree-shaked by rollup-plugin-typescript2

So babel plugin can't work normally in next step.

#### Environment

macbook pro - Catalina 10.15.7 
node - 12.18.0

##### Versions

typescript - 4.5.4
rollup - 2.60.1
rollup-plugin-typescript2 - 0.29.0

#### rollup.config.js
This is minimum reproducible configuration

<details>
  <summary>`rollup.config.js`: </summary>

```js
const pkg = require(path.join(__dirname, `xxx/package.json`));
const peerDependencies = Object.keys(pkg.peerDependencies || {});
const dependencies = Object.keys(pkg.dependencies || {});
const allProductionDependencies = [...peerDependencies, ...dependencies];

const external = moduleId => {
  return allProductionDependencies.some(dependence => {
    return moduleId.includes(dependence);
  });
};

export default {
  input: path.join(__dirname, 'xxx/index.tsx'),
  output: {
    file: path.join(__dirname, 'xxx.dist.js'),
    format: 'esm',
    exports: 'named',
  },
  external,
  plugins: [

    // just has rollup-plugin-typescript2

    // nodeResolve()
    // commonjs(),
    typescript(),
    // babel(),
    // ......
  ],
};
```

</details>

#### tsconfig.json

<details>
  <summary>`tsconfig.json`: </summary>

```json
{
  "compilerOptions": {
    "baseUrl": "./",
    "strictNullChecks": true,
    "moduleResolution": "node",
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "jsx": "react",
    "noUnusedParameters": true,
    "noUnusedLocals": true,
    "noImplicitAny": true,
    "target": "esnext",
    "lib": ["dom", "es2017"],
    "skipLibCheck": true,
    "declaration": true,
    "types": ["node"]
  },
  "exclude": ["node_modules", "lib", "es"],
  "includes": ["./types/index.d.ts"]
}
```
</details>

#### package.json

<details>
  <summary>`package.json`: </summary>

</details>

#### part of plugin output

<details>
  <summary>part of plugin output : </summary>

```js
// no jsx from emotion
import React, { forwardRef, useRef, useState, useImperativeHandle, useEffect, useCallback } from 'react';

// React Component:
const Component = () => {
  return React.createElement()
}
```

</details>

Maybe i use it incorrectly, if that, please tell how can configure it correctly.

Add `"jsxFactory": "jsx",` in `tsconfig.json` can resolve it **"inelegantly"**. But i must write "import { jsx } from '@emotion/react' " in every component file.

**Comment by agilgur5** [comment]
Looking at your `tsconfig.json`, I believe the problem is that your [`jsx` configuration](https://www.typescriptlang.org/tsconfig#jsx) is set to `react`, so it'll output as React JSX as you configured it.

I believe what you want is `jsx: "preserve"` instead, which, per the linked docs above, will leave the JSX untouched, then the Babel plugin should run fine in the next step
