### ISSUE TITLE
No compiler errors compared to tsc

### ISSUE THREAD

**Issue by XDex** [ezolenko/rollup-plugin-typescript2#3]
Hi, 

I'm trying to use the plugin, however I'm getting no compiler errors at all when building with rollup, compared to running `tsc`.  

Here's the output from `tsc`:

```
src/main/ts/core/api/track-event.ts(83,17): error TS2345: Argument of type 'string' is not assignable to parameter of type 'ZeptoEventHandlers'.
src/main/ts/core/content/renderers/helpers/renderer-helpers.ts(71,12): error TS2345: Argument of type '"load"' is not assignable to parameter of type 'ZeptoEventHandlers'.
src/main/ts/core/content/renderers/helpers/renderer-helpers.ts(77,12): error TS2345: Argument of type '"error"' is not assignable to parameter of type 'ZeptoEventHandlers'.
src/main/ts/core/content/renderers/set-attribute.ts(26,12): error TS2345: Argument of type '"load"' is not assignable to parameter of type 'ZeptoEventHandlers'.
src/main/ts/core/content/renderers/set-attribute.ts(31,12): error TS2345: Argument of type '"error"' is not assignable to parameter of type 'ZeptoEventHandlers'.
src/main/ts/foundation/zepto.ts(1621,14): error TS2322: Type '(selector: any, context: any) => any' is not assignable to type 'ZeptoStatic'.
  Property 'camelCase' is missing in type '(selector: any, context: any) => any'.
```

Here's my rollup config:
```javascript
import typescript from 'rollup-plugin-typescript2';
import resolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';
import path from 'path';
import license from 'rollup-plugin-license';
import cleanup from 'rollup-plugin-cleanup';

export default {
  entry: './src/main/ts/bootstrap.ts',

  format: 'iife',

  moduleName: 'testmodule',

  dest: './dist/out.js',

  sourceMap: false,

  plugins: [
    typescript({
      check: true,
      include: [ "*.ts+(|x)", "**/*.ts+(|x)" ]
	}),
    resolve({
      jsnext: true,
      main: true,
      browser: true
	}),
    commonjs({
      include: 'node_modules/**',
      exclude: [ 'node_modules/@types/**' ],
      extensions: [ '.js' ],
      ignoreGlobal: false,
      sourceMap: false,
      namedExports: {
        'node_modules/js-cookie/src/js.cookie.js': [ 'get', 'set', 'remove']
      }
    }),
    license({
      sourceMap: true,
      banner: {
        file: path.join(__dirname, 'tools/decorations/license.txt')
      }
    }),
    cleanup({
      comments: 'some'
    })
  ]
}
```

And `tsconfig.json`:
```javascript
{
  "compilerOptions": {
    "module": "commonjs",
    "moduleResolution": "node",
    "target": "es5",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "noImplicitAny": false,
    "removeComments": false,
    "noEmitHelpers": true,
    "sourceMap": false,
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "maxNodeModuleJsDepth": 1,
    "types" : [
      "es6-shim",
      "js-cookie",
      "query-string"
    ]
  },
  "include": [
    "**/*.ts"
  ],
  "exclude": [
    "node_modules"
  ],
  "compileOnSave": false,
  "buildOnSave": false
}
```

I'm using TypeScript v2.2.1

**Comment by ezolenko** [comment]
Could you change plugin settings to this:
```
typescript({
    verbosity: 3,
    clean: true,
    check: true,
})
```

Then run the build and post the plugin output here? (unless there is something sensitive in your project structure)

**Comment by ezolenko** [comment]
Also try 0.2.0, I just updated the way errors are dealt with.

**Comment by XDex** [comment]
@ezolenko Thanks for the quick response, I'll try these suggestions first thing tomorrow!

**Comment by XDex** [comment]
@ezolenko I've updated the plugin and applied the verbosity, clean and check settings, as you suggested. Now it fails with this error: `rpt2: Cannot write file '/home/andrei/work/bumblebee-rxjs/node_modules/zepto/index.js' because it would overwrite input file.`
Also, no TS errors are reported.
I've attached the logged info.
[rpt2_log.txt](https://github.com/ezolenko/rollup-plugin-typescript2/files/821075/rpt2_log.txt)

**Comment by XDex** [comment]
Also, when I set `allowJs=false` in `tsconfig.json` the plugin runs without failing with this error, however no TS errors are reported at all, while `tsc` still reports a bunch..

**Comment by ezolenko** [comment]
That allowJs thing looks like a separate bug, the error is from typescript compiler option diagnostics (which I was checking in the middle, because an entry point called "intro()" is obviously in the middle... :)). Might be some confusion with zepto the npm module and zepto.ts the source file, but I'm not sure who is confused.

It did block all semantic diagnostics from the log though.

Could you try master branch (npm install "git+https://git@github.com/ezolenko/rollup-plugin-typescript2.git") and attach full log if it gets everything? I'm remotely debugging with printf here...

Do you have `maxNodeModuleJsDepth` set to 1 for a reason? (while simultaneously excluding node_modules)

**Comment by ezolenko** [comment]
re: `Cannot write file because it would overwrite input file`, there is report on typescript about similar issues. So likely not related to this plugin: https://github.com/Microsoft/TypeScript/issues/14538

**Comment by XDex** [comment]
@ezolenko So, I've tried the master branch, and I'm still getting no errors, the logs are attached..
[rpt2_log.txt](https://github.com/ezolenko/rollup-plugin-typescript2/files/833791/rpt2_log.txt)
[tsc_log.txt](https://github.com/ezolenko/rollup-plugin-typescript2/files/833790/tsc_log.txt)

> Do you have maxNodeModuleJsDepth set to 1 for a reason? (while simultaneously excluding node_modules)
Not really, just forgot to remove it after excluding `node_modules`

**Comment by ezolenko** [comment]
Huh, you are still not getting the second half executed. I begin to wonder if I'm using entirely wrong entry point for semantic error checks...

What's your rollup version btw?

**Comment by ezolenko** [comment]
Ok, could you try with 0.3.0. You are likely using older rollup version that doesn't have plugin entry point I was (wrongly anyway) using.

**Comment by XDex** [comment]
@ezolenko I've just tried v0.3.0 and it correctly failed at one of the problematic files, however the error message was ambiguous:
```
rpt2: transpiling '/home/andrei/work/bumblebee-rxjs/src/main/ts/core/content/renderers/helpers/renderer-helpers.ts'
Error transforming /home/andrei/work/bumblebee-rxjs/src/main/ts/core/content/renderers/helpers/renderer-helpers.ts: this.context.error is not a function
```
I had rollup v0.36, and after I've bumped it to the latest v0.41.5 things have finally been corrected, now the proper error message as reported by tsc is displayed:
```
rpt2: transpiling '/home/andrei/work/bumblebee-rxjs/src/main/ts/core/content/renderers/helpers/renderer-helpers.ts'
🚨   rpt2: /home/andrei/work/bumblebee-rxjs/src/main/ts/core/content/renderers/helpers/renderer-helpers.ts (77,12): Argument of type '"error"' is not assignable to parameter of type 'ZeptoEventHandlers'.
src/main/ts/core/content/renderers/helpers/renderer-helpers.ts
```
Compared to `tsc`, only one error is shown though, I guess this is expected, right?

Thanks for your effort in fixing this!

**Comment by ezolenko** [comment]
You should be able to get all errors if you set `abortOnError` option to false (should be default though). Of course then rollup will not fail on errors... :)

**Comment by jdalrymple** [comment]
Sorry for bringing this back from the dead, but im getting the same problem :/

versions:
rollup: 0.66.6
typescript: 3.1.3
rollup-plugin-typescript2: 0.17.1

config:
```
import ts from 'rollup-plugin-typescript2';
import typescript from 'typescript';
import pkg from './package.json';

  {
    input: 'src/index.ts',
    output: {
      file: pkg.main,
      format: 'cjs',
    },
    external: [...Object.keys(pkg.dependencies)],
    plugins: [
      ts({ typescript, clean: true, verbosity: 3, check: true, abortOnError: false }),
    ],
  },
```

Rollup finishes without any problems, but id i run tsc, i get a whole slew of errors

**Comment by ezolenko** [comment]
@jdalrymple this is expected -- the plugin sets `moduleResolution: node` regardless of what is in tsconfig (see readme for this and other enforced options).

**Comment by jdalrymple** [comment]
You're correct, I totally missed that in the docs! Sorry about that.
