### ISSUE TITLE
Allow to override CompilerOptions from TypeScript

### ISSUE THREAD

**Issue by tkrotoff** [ezolenko/rollup-plugin-typescript2#33]
This was possible with the [original plugin](https://github.com/rollup/rollup-plugin-typescript):
*The plugin loads any [`compilerOptions`](http://www.typescriptlang.org/docs/handbook/compiler-options.html) from the `tsconfig.json` file by default. Passing options to the plugin directly overrides those options.*

Also [ts-loader](https://github.com/TypeStrong/ts-loader) for Webpack allows it:
`{ test: /\.tsx?$/, loader: 'ts-loader', options: {compilerOptions: {module: 'esnext', declaration: false}} }`

**Comment by ezolenko** [comment]
In master now, check if it works for you.

**Comment by tkrotoff** [comment]
Works fine, thx a lot 👍 
However, what about following ts-loader and awesome-typescript-loader convention and not introducing `tsconfigOverride` :
```
typescript({
  abortOnError: false,
  clean: true,
  tsconfigOverride: {compilerOptions: {module: 'esnext', declaration: false}}
})
```
vs
```
typescript({
  abortOnError: false,
  clean: true,
  compilerOptions: {module: 'esnext', declaration: false}
})
```

**Comment by ezolenko** [comment]
With full override you can modify other tsconfig parameters that are normally outside of `compilerOptions` object. One interesting example is setting or changing base tsconfig with `extends`.

**Comment by tkrotoff** [comment]
I see 👍
