### ISSUE TITLE
.rpt2_cache should be in /tmp

### ISSUE THREAD

**Issue by tkrotoff** [ezolenko/rollup-plugin-typescript2#34]
Instead of having `.rpt2_cache` directory created inside the "working/current" directory, it should be in [`/tmp`](https://en.wikipedia.org/wiki/Temporary_folder) so that users don't have to `.gitignore` it.

**Comment by ezolenko** [comment]
You should be able to override the location in plugin options:
```
plugins: [
    typescript( { cacheRoot: `${require('temp-dir')}/.rpt2_cache` }),
]
```

I don't want to move cache out by default, because there will be potential for conflict (single system building multiple copies of the same repository simultaneously for example)

**Comment by enil** [comment]
At least I think it should be documented the plugin creates a temp directory in the current directory.
