### ISSUE TITLE
ES5 target produces const when using object spread operator

### ISSUE THREAD

**Issue by alexanderby** [ezolenko/rollup-plugin-typescript2#36]
Same error as here https://github.com/rollup/rollup-plugin-typescript/issues/87

Not an issue for https://github.com/alexlur/rollup-plugin-typescript

**Comment by ezolenko** [comment]
Is it exact same issue (with `const`) or is it the same in general way of tslib code not passing through other plugins? That part is pretty much unmodified vs alexlur version and tslib itself is transpiled into what looks like es5.

Could you post your package.json, tsconfig and rollup config? (or ideally an example repo :))

Thanks

**Comment by alexanderby** [comment]
I thought the problem was in spread operator, but it is not. I've misused `tsconfigOverride`, assigned `{target: 'es5'}` instead of `{compilerOptions: {target: 'es5'}}`.
