### ISSUE TITLE
How to handle rootDirs outside a project root?

### ISSUE THREAD

**Issue by mattdsteele** [ezolenko/rollup-plugin-typescript2#37]
I have a Lerna project with this structure:

```
<root>
│   package.json
│   tsconfig.json
│
├───packages
│   ├───foo
│   │   │   package.json
│   │   │   rollup.config.js
│   │   │   tsconfig.json
│   │   │
│   │   └───src
│   │           foo.ts
│   │           index.ts
│   │
│
└───shared
    └───utils
        │   index.ts
        │   style-cache.ts
        │
        └───decorator
                decorators.ts
```

I'm using TypeScript's `rootDirs` option to include the `shared/utils` folder in my `foo` build: https://www.typescriptlang.org/docs/handbook/module-resolution.html#virtual-directories-with-rootdirs

This works fine when compiling with `tsc`, but it's failing on the Rollup build with errors like:

```
[!] Error: Unexpected token
..\..\shared\utils\decorator\decorators.ts (2:26)
1: import { styleCacheSingleton } from '../style-cache';
2: const makeDecorator = (key: string) => {
                             ^
```

After debugging it appears the reason this is happening is that the file in `shared/utils` are being excluded from TypeScript processing.

This is the result of the [createFilter](https://github.com/ezolenko/rollup-plugin-typescript2/blob/fa1bbf88824e4fe92a21bca4be6e47d8e072b67d/src/index.ts#L74) function, which by default does a `path.resolve()` wherever the Rollup command is being invoked: https://github.com/rollup/rollup-pluginutils/blob/master/src/createFilter.js#L6

So! I'm looking for feedback on how you think I should resolve this. I can work around it by manually adding the out-of-directory folder to an include list:

```
  plugins: [
    ts({
      include: ['**/*.ts', '../../shared/**/*.ts']
    })
  ]
```

But, it feels to me like this should be handled automatically by this plugin if it finds a `rootDirs` folder in tsconfig. What do you think? Is it worth putting a PR together? Or is there a better way for me to handle this?

**Comment by ezolenko** [comment]
Hm, yeah, looks like this should be handled by default. Maybe only if plugin's `include` is not changed, it would be tricky to correctly update custom include list -- for example a naive approach would turn yours into `['**/*.ts', '../../shared/**/*.ts', '../../shared/**/*.ts', '../../shared/../../shared/**/*.ts']`

A PR would be welcome!

**Comment by ezolenko** [comment]
Ok, merged your PR and added same treatment to excludes. Check if it still works for you :)

**Comment by mattdsteele** [comment]
@ezolenko Works great! Would you be able to publish 0.8 to NPM? 🥂

**Comment by ezolenko** [comment]
Yep, I'll release it in a few days
