### ISSUE TITLE
include not overrided

### ISSUE THREAD

**Issue by kalitine** [ezolenko/rollup-plugin-typescript2#39]
#It's either a bug or maybe a wanted functionality. Here are my tsconfig file and plugin options which work well:
`tsconfig.dist.esm.json`:
```json
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "declaration": true,
    "declarationDir": "dist/esm"
  },
  "include": ["src/**/*.ts"]
}

```

`rollup.config.js`:
```javascript
typescript({
  tsconfig: 'tsconfig.dist.esm.json',
  useTsconfigDeclarationDir: true
})
```

I wanted to rid of `tsconfig.dist.esm.json` and thus modified `rollup.config.js` file:
```javascript
typescript({
  tsconfig: 'tsconfig.dist.esm.json',
  tsconfigOverride: {
    compilerOptions: {
      declaration: true,
      declarationDir: 'dist/esm'
    },
    include: ['src/**/*.ts']
  },
  useTsconfigDeclarationDir: true
})
```

But it does not work. The plugin does not pay attention to `txconfigOverride.compilerOptions.declarationDir` option. Would be nice if it could.

**Comment by ezolenko** [comment]
Seems to work for me, I added `declarationDir` to `tsconfigOverride.compilerOptions`, and depending on `useTsconfigDeclarationDir` it puts them in default location (with the bundle) or in the place `declarationDir` points to.

You have 2 dots in `tsconfig.dist.esm..json`, is that intentional or a copy-paste error?

What's in the file itself? Plugin will fail if the file doesn't exist at all, so it needs to have at least `{}` in there. (but you should be able to point all builds at single file and use overrides to tweak them).

Check if you have correct plugin version, `tsconfigOverride` was added in `0.7.0`.

**Comment by ezolenko** [comment]
Ok, merged your PR and added same treatment for excludes. Check if it still works for you :)

**Comment by kalitine** [comment]
Thanks, I've edited the issue, as 2 dots were just copy-paste error.
Sorry, you are right it works with the `rollup.config.js` I've mentioned above.

But I've also mistaken with this example, as I wanted to rid of `tsconfig.dist.esm.json`, thus I do not want this file to exist, which means to have `rollup.config.js` like this:
```
typescript({
  tsconfigOverride: {
    compilerOptions: {
      declaration: true,
      declarationDir: 'dist/esm'
    },
    include: ['src/**/*.ts']
  },
  useTsconfigDeclarationDir: true
})
```

But you said that it must exist even just `{}`, so it's ok that it does not work without.

As I steel want to rid of `tsconfig.dist.esm.json` I tried another solution. This config extends `tsconfig.json`, so I tried this configuration:
```
typescript({
  tsconfig: 'tsconfig.json',
  tsconfigOverride: {
    compilerOptions: {
      declaration: true,
      declarationDir: 'dist/esm'
    },
    include: ['src/**/*.ts']
  },
  useTsconfigDeclarationDir: true
})
```
And strangely this did not work for me. I looked to the difference between `tsconfig.dist.esm.json` and `tsconfig.json`. And here is what I found. With the following `tsconfig.json` it does not work:
```json
{
  "compilerOptions": {
    "target": "ES5",
    "module": "ES2015",
    "lib": [ "ES2015", "ES2016", "ES2017", "DOM" ],
    "moduleResolution": "node",
    "downlevelIteration": true,
    "types": ["node", "text-encoding"]
  },
  "include": [
    "src/**/*",
    "test/**/*"
  ],
  "exclude": ["**/proto/index.d.ts"]
}
```

But if I remove `    "test/**/*"` line, it works. Which means that override for `include` options does not work.

**Comment by ezolenko** [comment]
Ah, yes, that works as coded. Objects and arrays are merged, not replaced. This is a different behavior from tsconfig `extends` option (and I probably shouldn't have called it `override` :)). Arguably either way is useful in different cases.

You can achieve what you want by creating `tsconfig.base.json` file without `test/**/*` in includes (but with all the other common options) and using that for rollup directly. Then create `tsconfig.json` that `extends` your base and specifies full include list and use that outside of rollup. (see `Configuration inheritance` in [tsconfig-json](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html))

Doesn't reduce number of files, but removes duplication.

**Comment by kalitine** [comment]
Ok, I see. Yes *override* confused me. No problem I will preserve my `tsconfig.dist.esm.json` which extends `tsconfig.json` and is not a big deal.

**Comment by agilgur5** [comment]
See #86 for the root cause fix
