### ISSUE TITLE
Large cache throws Invalid string length when stringifying config

### ISSUE THREAD

**Issue by ryanhyslop** [ezolenko/rollup-plugin-typescript2#42]
On a watch, first compile is ok but then re-compiling after a change throws the following;

```
/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:19791
            context.debug("rollup config:\n" + JSON.stringify(rollupOptions, undefined, 4));
                                                    ^
RangeError: Invalid string length
```

The rollupOptions object is massive if I log it out:

```
  cache:
   { imports: [],
     exports: [ 'app' ],
     modules:
      [ [Object],
        [Object],
        ..... (removed for brevity)
        [Object],
        [Object],
        [Object],
        ... 1651 more items ],
```

Which seems to be whats throwing what is essentially an out of memory error from JSON.stringify

Commenting out the line to log out that and everything works fine. Just wondering whether I'm doing something wrong to result in such a large cache (it is a big project) or whether this is just a use case thats never manifested itself in 'regular' use.

**Comment by ezolenko** [comment]
No, I don't think you are doing anything wrong. Looks like rollup adds stuff to options after I grab it and I keep stringifying it needlessly.

**Comment by ezolenko** [comment]
Probably causes or affects #40 too.

**Comment by ezolenko** [comment]
Ok, try again with master branch.

It is interesting why you hit that line on a watch rebuild though. Do you use rollup watch or something else?

**Comment by ryanhyslop** [comment]
Hi, thanks for the quick response. I've tried out master and initial testing it looks like its working now 👍 

We are running an old version of roll up currently (0.39) and rollup-watch (4.0.0) guess it shouldn't come as a surprise theres some issues :)
