### ISSUE TITLE
Cannot make it work with 'rollup-plugin-commonjs'

### ISSUE THREAD

**Issue by psxcode** [ezolenko/rollup-plugin-typescript2#43]
config
```javascript
// rollup.config.js
import typescript from 'rollup-plugin-typescript2';
import commonjs from 'rollup-plugin-commonjs';
import nodeResolve from 'rollup-plugin-node-resolve'

export default {
  input: 'src/index.ts',
  output: {
    format: 'es',
    file: 'dist/index.js'
  },

  plugins: [
    typescript(),
    nodeResolve(),
    commonjs()
  ]
}
```
input
```javascript
// index.ts
var f = require('untypedModule')
f()
```
output
```javascript
// dist/index.js
var f = require('untypedModule')
f()
```

when typescript() removed from plugins array
```javascript
// dist/index.js
function f() {...}
f()
```
As you can see 'typescript-plugin' somehow prevents 'commonJs' and 'nodeResolve' to produce proper output 

If I remove 'typescript-plugin' from chain, the output is correct

Please help.

**Comment by ezolenko** [comment]
What's wrong with the output exactly?

**Comment by psxcode** [comment]
content of 'untypedModule' was not injected into bundle.
When I remove 'typescript()' from plugins array - 
content of 'untypedModule' is being injected and require('untypedModule') is being removed.

**Comment by ezolenko** [comment]
Are there any errors from typescript, rollup or other plugins?

**Comment by ezolenko** [comment]
Yep, a sample would be nice.

**Comment by psxcode** [comment]
[test.zip](https://github.com/ezolenko/rollup-plugin-typescript2/files/1479406/test.zip)
Here is a ultra minimal test.
`npm i && npm run build`
modify rollup.config.js and rebuild,
output is at dist/index.js

**Comment by ezolenko** [comment]
Hm, I run npm install and npm build without modifying anything and I'm getting this in output:

```js
function helper$1 (param) {
    return `param`
}


var helpers = Object.freeze({
	helper: helper$1
});

const { helper } = helpers;

helper();

var src = {

};

export default src;
```

**Comment by psxcode** [comment]
Yes. And now please change input file to `index.ts` inside `rollup.config.js`

**Comment by ezolenko** [comment]
Looks like you need `"allowJs": true` in tsconfig (that forces `"declaration": false`, beacuse ts can't generate declarations when there are untyped modules in the mix). Then change require to import: `import { helper } from './helpers'`

Then rollup will generate correct bundle -- an empty file -- because you don't explicitly export anything. Once you export stuff, for example `export const x = helper()`, the bundle will contain your helper (but only with the stuff you actually use, the rest rollup will shake from the tree).

**Comment by psxcode** [comment]
Got it.
So you think it is impossible to make `require` work.
With `typescript` I must use `import`, right?

**Comment by ezolenko** [comment]
Yeah, I think typescript doesn't try to resolve requires, so they are invisible to rollup (because of `"module": "es2015"` option likely, which this plugin requires), but I'm not entirely sure.

**Comment by qingtiantongxie** [comment]
what should i do if i want to import some dynamic css in my code ？ it looks like this `require('./theme/' + getPath() + '.css')。

more information i post here:  https://github.com/ezolenko/rollup-plugin-typescript2/issues/284

**Comment by agilgur5** [comment]
> it looks like this `require('./theme/' + getPath() + '.css')`

TypeScript supports [dynamic imports](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-4.html#dynamic-import-expressions).

> more information i post here: #284

I also wrote there that any sort of dynamic import can get hairy with a static analyzer like Rollup.
