### ISSUE TITLE
This plugin doesn't work with non ts files

### ISSUE THREAD

**Issue by ko22009** [ezolenko/rollup-plugin-typescript2#438]
import bold from 'assets/fonts/OpenSans/OpenSans-Bold.woff2';

alias assets doesn't work.

**Comment by agilgur5** [comment]
### entirely removed issue template...

Please don't remove the issue template, it's there for a reason.

Please do be respectful to maintainers, the vast majority of which are unpaid volunteers.
To be explicit, a one line issue that removes the entire issue template is _not_ respectful.

### aliases

> alias assets doesn't work.

"Aliases" are not truly supported by TypeScript itself, please see #201 for significant details about this.

### fonts

> This plugin doesn't work with non ts files

It is a TS plugin, it's only meant to handle TS files. `tsc` itself does not handle non-TS files.

If you're trying to import a font into your library, you need a separate plugin for that. TS also needs declarations for that, as it does for all non-TS asset files, see also #160
