### ISSUE TITLE
[!] (plugin rpt2) RollupError: src/components/LShape/LShape.vue?vue&type=script&setup=true&lang.ts:1:10 - error TS2305: Module '"vue"' has no exported member 'mergeDefau lts'.

### ISSUE THREAD

**Issue by zhong1998** [ezolenko/rollup-plugin-typescript2#440]
## Troubleshooting

1. Does `tsc` have the same output? If so, please explain why this is incorrect behavior
    

1. Does your Rollup plugin order match [this plugin's compatibility](https://github.com/ezolenko/rollup-plugin-typescript2#compatibility)? If not, please elaborate
    

1. Can you create a [minimal example](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this behavior? Preferably, use [this environment](https://stackblitz.com/edit/rpt2-repro) for your reproduction
    

## What happens and why it is incorrect
I use export default definecomponent can be ok ，but use setup lang="ts" is false. it seems the plugin is wrong in run time.

## Environment

{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "strict": true,
    "jsx": "preserve",
    "moduleResolution": "node",
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "forceConsistentCasingInFileNames": true,
    "useDefineForClassFields": true,
    "sourceMap": true,
    "baseUrl": ".",
    "types": [
      "webpack-env",
      "jest"
    ],
    "paths": {
      "@/*": [
        "src/*"
      ]
    },
    "lib": [
      "esnext",
      "dom",
      "dom.iterable",
      "scripthost"
    ]
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.tsx",
    "src/**/*.vue",
    "tests/**/*.ts",
    "tests/**/*.tsx"
  ],
  "exclude": [
    "node_modules"
  ]
}

### Versions

   "rollup-plugin-typescript2": "^0.34.1",

```text

```

<details>
  <summary><h4><code>rollup.config.js</code></h4>: </summary>

import fs from "fs"
import vue from "rollup-plugin-vue"
import css from "rollup-plugin-css-only"
import typescript from "rollup-plugin-typescript2";

const {name} = JSON.parse(fs.readFileSync("package.json", "utf-8"))
const file = type => `dist/${name}.${type}.js`

const overrides = {
    compilerOptions: {declaration: true},
}
export default {
    input: "src/index.ts",
    output: {
        name,
        file: file("esm"),
        format: 'es'
    },
    plugins: [
        typescript({tsconfigOverride:overrides}),
        vue(),
        css({output: "bundle.css"})
    ]
}

```js

```

</details>

<details>
  <summary><h4><code>tsconfig.json</code></h4>: </summary>

```json5

```
<template>
  <img :src="src" class="component" :style="styleProps" @click.prevent="handleClick">
</template>

<script lang="ts" setup>
import {defineProps, withDefaults} from "vue"
import useComponentCommon from "./../../hook/useComponentCommon"
import {imageDefaultProps, imageStylePropsNames} from "../../defaultProps"

interface imgProps {
  src: string;
  actionType: string;
  url: string;
  // size
  height: string;
  width: string;
  paddingLeft: string;
  paddingRight: string;
  paddingTop: string;
  paddingBottom: string;
  // border type
  borderStyle: string;
  borderColor: string;
  borderWidth: string;
  borderRadius: string;
  // shadow and opacity
  boxShadow: string;
  opacity: string;
  // position and x,y
  position: string;
  left: string;
  top: string;
  right: string;
}

const props = withDefaults(defineProps<imgProps>(), {
  ...imageDefaultProps
})
const {styleProps, handleClick} = useComponentCommon(props, imageStylePropsNames)
</script>

<style scoped>
.component {
  max-width: 100%;
  position: relative !important;
}
</style>

</details>

<details>
  <summary><h4><code>package.json</code></h4>: </summary>

{
  "name": "xxxx",
  "version": "xxxx",
  "private": true,
  "type": "module",
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "test:unit": "vue-cli-service test:unit",
    "lint": "vue-cli-service lint",
    "build:esm": "rollup --config build/rollup.config.js"
  },
  "dependencies": {
    "core-js": "^3.8.3",
    "lodash-es": "^4.17.21",
    "vue": "^3.2.13"
  },
  "devDependencies": {
    "@types/jest": "^27.0.1",
    "@types/lodash-es": "^4.17.6",
    "@typescript-eslint/eslint-plugin": "^5.4.0",
    "@typescript-eslint/parser": "^5.4.0",
    "@vue/cli-plugin-babel": "~5.0.0",
    "@vue/cli-plugin-eslint": "~5.0.0",
    "@vue/cli-plugin-typescript": "~5.0.0",
    "@vue/cli-plugin-unit-jest": "~5.0.0",
    "@vue/cli-service": "~5.0.0",
    "@vue/eslint-config-typescript": "^9.1.0",
    "@vue/test-utils": "^2.0.0-0",
    "@vue/vue3-jest": "^27.0.0-alpha.1",
    "babel-jest": "^27.0.6",
    "eslint": "^7.32.0",
    "eslint-plugin-vue": "^8.0.3",
    "jest": "^27.0.5",
    "rollup-plugin-css-only": "^4.3.0",
    "rollup-plugin-typescript2": "^0.34.1",
    "rollup-plugin-vue": "^6.0.0",
    "ts-jest": "^27.0.4",
    "tslib": "^1.14.1",
    "typescript": "~4.5.5"
  }
}

```json

```

</details>

<details>
  <summary><h4>plugin output with verbosity 3</h4>: </summary>

```text

```

</details>

**Comment by agilgur5** [comment]
So there was no repro provided here and no logs either, but this issue sounds very similar to #325 with the case of Vue SFCs (also potentially #235 / https://github.com/vuejs/rollup-plugin-vue/issues/311). Per that issue, that is due to a problem in Vue typings or `rollup-plugin-vue` (which has long been deprecated), and so it is out of the control and scope of rpt2.

That being said, there is a [workaround provided](https://github.com/ezolenko/rollup-plugin-typescript2/issues/325#issuecomment-1274421299) in that issue that may work for your issue as well

**Comment by wwei-github** [comment]
Has this problem been solved? I have also encountered this, but I don't know why

**Comment by veco9** [comment]
I'm experiencing the same issue. The problem arises due to the destructuring that occurs in the "defaults" parameter of the "withDefaults" function.
```
{
  ...imageDefaultProps
}
```
Even if you pass it like this:
```
{
   ...{someProperty: "foo"}
}
```
or 

```
{
   Object.assign({}, {someProperty: "foo"})
}
```

I have also left a comment on the issue [vite-plugin-dts#188](https://github.com/qmhc/vite-plugin-dts/issues/188#issuecomment-1570226566).
 I would greatly appreciate any assistance or possible workarounds.

**Comment by agilgur5** [comment]
Per https://github.com/qmhc/vite-plugin-dts/issues/188#issuecomment-1570226566, it looks like this indeed was a Vue typings issue:

> I've found a comment in vue@3.3.4 "runtime-core.d.ts":
> `/* removed internal: mergeDefaults */`
