### ISSUE TITLE
use tsc allowJs and outDir compilerOptions

### ISSUE THREAD

**Issue by guidorice** [ezolenko/rollup-plugin-typescript2#46]
I am using `tsc` to transpile ES6 javascript to ES5, by using
```
compilerOptions: {
        "allowJs": true,
        "outDir": "./build",
      ...
},
```
In my rollup.config.js, I have  ` input: 'build/index.js'`,
My build script is then  `tsc && rollup -c`. This seems to work fine.

I would like to be able to use rollup-plugin-typescript2, rather than calling tsc on the command line, but rollup-plugin-typescript2 seems to disallow the outDir option. The docs say this option is forced. "outDir: process.cwd()". Would it be possible to support this workflow with rollup-plugin-typescript2?

**Comment by ezolenko** [comment]
Yeah, rollup-plugin-typescript2 doesn't write out individual transpiled files (if you ignore cache), it just passes code back to rollup and that rolls them into the bundle. 

If you change your rollup config to `input: './index.js'`, and pass `{ include: ["*.js", "**/*.js"] }` as plugin options, then everything would probably work.

**Comment by ezolenko** [comment]
Normally if you were writing typescript, rollup entry point would be something like `./index.ts` and `outDir` would effectively be ignored.

**Comment by guidorice** [comment]
Thanks @ezolenko , I gave that a try, but for some reason it cannot find node modules.

> src/index.js → public/bundle.js...
[!] (rpt2 plugin) Error: Could not find file: '/Users/alex/Desktop/catalog-viewer/catalog-viewer/node_modules/ramda/src/pathOr.js'.

But that file exists...

Another problem is that the `outDir` compiler option is required when using `allowJs`. Because otherwise tsc fails with this error:

> error TS5055: Cannot write file 'path.../file.js' because it would overwrite input file.

Here is my tsconfig.json. This works fine with just running `tsc`, it writes the results into build/

```
{
    "compilerOptions": {
        "allowJs": true,
        "checkJs": false,
        "declaration": false,
        "lib": ["DOM", "ES5", "ES6", "ScriptHost"],
        "module": "es2015",
        "moduleResolution": "node",
        "noEmitOnError": true,
        "noImplicitAny": true,
        "noUnusedLocals": true,
        "outDir": "./build",
        "removeComments": true,
        "sourceMap": false,
        "target": "ES5",
        "types": []
    },
    "include": ["src/**/*"],
    "exclude": [
        "**/*.spec.ts",
        "**/*.test.js"
    ]
}
```

Here is my current rollup.config.js

```
import uglify from 'rollup-plugin-uglify';
import replace from 'rollup-plugin-replace';
import typescript from 'rollup-plugin-typescript2';
import pkg from './package.json';

const CI_BUILD_TYPE = process.env.CI_BUILD_TYPE || 'development';
const VERSION = process.env.CI_TAG || pkg.version;
const UGLIFY = CI_BUILD_TYPE === 'production';

export default {
    input: 'src/index.js',
    output: {
        file: 'public/bundle.js',
        format: 'iife',
        sourcemap: true,
    },
    plugins: [
        replace({
            values: { CI_BUILD_TYPE, VERSION },
        }),
        typescript({ include: ["*.js", "**/*.js"] }),
        UGLIFY ? uglify() : {}
    ],
};
```
I am stumped on this now, please let me know if you have any other ideas.  We can close the issue if it seems like rollup-plugin-typescript2 might not be able to support the workflow.

**Comment by ezolenko** [comment]
To find node modules and make them visible to rollup you need `rollup-plugin-node-resolve` and `rollup-plugin-commonjs` plugins.

```
import resolve from "rollup-plugin-node-resolve";
import commonjs from "rollup-plugin-commonjs";

// ...
	plugins: [
		resolve({ jsnext: true, preferBuiltins: true }),
		commonjs({ include: "node_modules/**" }),
		typescript({ include: ["*.js", "**/*.js"] }),

```

For `outDir` you should be able to keep it at any value you want (if you want to be able to run `tsc` independently from rollup) and plugin will override it when `tsconfig.json` is used in rollup. Try that and let me know if there are related errors emitted by the plugin itself.

**Comment by guidorice** [comment]
@ezolenko aha, the "Error: Could not find file:" threw me off in the wrong direction. This was the change I needed to make in my config:

        typescript({ include: ["src/*.js", "src/**/*.js"] }),

Thanks again for your help! best regards
