### ISSUE TITLE
Turborepo Sveltekit : cannot import TS files from workspace

### ISSUE THREAD

**Issue by MarArMar** [ezolenko/rollup-plugin-typescript2#465]
## Troubleshooting

Reproduction repo: https://github.com/MarArMar/TurboTest

```sh
npx turbo run dev --filter=SveltekitTypia
```

Bug 1: Cannot import TS files (critical because blocks dev)
```
SveltekitTypia:dev: Parse failure: Unexpected token (1:7)
SveltekitTypia:dev: At file: /@fs/.../TurboTest/packages/common/lib/log.ts
SveltekitTypia:dev: Contents of line 1: export type LogFunction = (...params: any) => void
SveltekitTypia:dev: Sourcemap for ".../TurboTest/apps/SveltekitTypia/src/routes/typia.ts" points to missing source files
SveltekitTypia:dev: 13:38:59 [vite] Error when evaluating SSR module /src/routes/+page.svelte: failed to import "/@fs/.../TurboTest/packages/common/lib/log.ts"
SveltekitTypia:dev: |- Error: Parse failure: Unexpected token (1:7)
SveltekitTypia:dev: At file: /@fs/.../TurboTest/packages/common/lib/log.ts
SveltekitTypia:dev: Contents of line 1: export type LogFunction = (...params: any) => void
```
Note: it seems it imports them as JS because if you remove all TS syntax it works.

Bug 2: Does not find source files (not critical because it does not block dev)
```
SveltekitTypia:dev: Sourcemap for ".../TurboTest/apps/SveltekitTypia/src/hooks.server.ts" points to missing source files
```

1. Does your Rollup plugin order match [this plugin's compatibility](https://github.com/ezolenko/rollup-plugin-typescript2#compatibility)? If not, please elaborate

Yes 
```js
	plugins: [sveltekit(),
		typescript({
			
			check: false,
})]
```

## Environment
Turborepo & Sveltekit

### Versions

```text
  System:
    OS: Windows 10 10.0.19043
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
    Memory: 2.61 GB / 15.74 GB
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.8.0 - ~\AppData\Local\pnpm\pnpm.EXE
```

<details>
  <summary><h4><code>rollup.config.js</code></h4>: </summary>

```js
import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig } from 'vite';
import typescript from "rollup-plugin-typescript2";

export default defineConfig({
	esbuild: false,
	plugins: [sveltekit(),
		typescript({
			check: false, // If not set, has another error before
		})]
});
```

</details>

<details>
  <summary><h4><code>tsconfig.json</code></h4>: </summary>

```json5
{
  "extends": "./.svelte-kit/tsconfig.json",
  "compilerOptions": {
    "allowJs": true,
    "checkJs": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "sourceMap": true,
    "strict": true,
    
    "noEmitOnError": false,
    "plugins": [
      {
        "transform": "typia/lib/transform"
      }
    ],
    "strictNullChecks": true
  }
  // Path aliases are handled by https://kit.svelte.dev/docs/configuration#alias
  //
  // If you want to overwrite includes/excludes, make sure to copy over the relevant includes/excludes
  // from the referenced tsconfig.json - TypeScript does not merge them in
}
```

</details>

<details>
  <summary><h4><code>package.json</code></h4>: </summary>

```json
{
  "name": "SveltekitTypia",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "dev": "vite dev --open",
    "build": "vite build",
    "prepare": "ts-patch install"
  },
  "devDependencies": {
    "@sveltejs/adapter-auto": "^2.0.0",
    "@sveltejs/kit": "^1.20.4",
    "@typescript-eslint/eslint-plugin": "^6.0.0",
    "@typescript-eslint/parser": "^6.0.0",
    "eslint": "^8.28.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-svelte": "^2.30.0",
    "rollup-plugin-typescript2": "^0.36.0",
    "svelte": "^4.0.5",
    "svelte-check": "^3.4.3",
    "ts-node": "^10.9.1",
    "ts-patch": "^3.0.2",
    "tslib": "^2.6.2",
    "typescript": "^5.2.2",
    "typia": "^5.2.6",
    "vite": "^4.4.2"
  },
  "dependencies": {
    "common": "workspace:*"
  },
  "type": "module"
}
```

</details>

**Comment by agilgur5** [comment]
This doesn't seem to be an rpt2 error as none of the errors you have listed are from rpt2 or from TS.

> Note: it seems it imports them as JS because if you remove all TS syntax it works.

The TS compiler (and rpt2 as a result) is compatible with both syntaxes and does not give such an error.

> 1. Does your Rollup plugin order match [this plugin's compatibility](https://github.com/ezolenko/rollup-plugin-typescript2#compatibility)? If not, please elaborate

> `rollup.config.js`

This is a Vite config, not a Rollup config. Additionally, I believe SvelteKit is expecting JS and not TS (I believe it uses Vite/`esbuild` for transpilation), hence the error you're getting may very well be from SvelteKit, not rpt2.

I haven't used Svelte before though, so I can't really help you further than that, but it is pretty clear that it is not an rpt2 bug

**Comment by MarArMar** [comment]
Ok so I updated the example repo with all possible info : https://github.com/MarArMar/TurboSvelteKitTypia/

- ✅ TS files from the same project work 
- ✅ JS file from the PNPM workspace work
- ✅ On a regular Sveltekit install, TS files on the PNPM workspace work
- BUT When I import a TS file on the PNPM workspace work I get this : 

Parse failure: Unexpected token (3:26)
At file: /@fs/C:/Users/Jack/Programmation/Aleph/TurboSvelteKitTypia/packages/common/log.ts
Contents of line 3: export const messageLoaded: string =

If I write a regular JS file inside the TS file it works again

I also tried putting the rpt2 plugin before the sveltekit plugin, it didn't work

Do you have any clue what is happening or where should I look ? I am really becoming desperate

**Comment by MarArMar** [comment]
Ok made it work @agilgur5

The issue was I had to add in the config : Updates : now works, see config, had to add  " include: ["../../**/*.ts+(|x)"],"

export default defineConfig({
  esbuild: false,
  plugins: [
    typescript({
      include: ["../../**/*.ts+(|x)"],
    }),
    sveltekit(),
  ],
});

**Comment by agilgur5** [comment]
Ah yea, since you're including files outside of the Rollup root, those files would be ignored [by default](https://github.com/ezolenko/rollup-plugin-typescript2?tab=readme-ov-file#plugin-options)

**Comment by Shofikul-Isl4m** [comment]
i am facing the same issue with next js turborepo . i can not import from packages its giving TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for C:\Users\hropa\Desktop\draw-app\packages\common\src\types.ts. but if i use built exports : dist/iindex.js in package.json then its working

**Comment by agilgur5** [comment]
@Shofikul-Isl4m that isn't the same error nor the same stack (and very likely different versions of Turborepo too). It's also a nearly 3 year old, closed, resolved issue. Your error message also does not seem specific to `rollup-plugin-typescript2`.

Please file a separate issue and carefully follow the directions in the issue template, in particular to provide a minimal reproduction. There's nothing much anyone can do given just an error message and no other details.
