### ISSUE TITLE
TSDX: `import yargs from 'yargs'` error "has no call signatures"

### ISSUE THREAD

**Issue by Yueyanc** [ezolenko/rollup-plugin-typescript2#467]
## Troubleshooting

1. Does `tsc` have the same output? If so, please explain why this is incorrect behavior
    

1. Does your Rollup plugin order match [this plugin's compatibility](https://github.com/ezolenko/rollup-plugin-typescript2#compatibility)? If not, please elaborate
    

1. Can you create a [minimal example](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces this behavior? Preferably, use [this environment](https://stackblitz.com/edit/rpt2-repro) for your reproduction
    

here! https://stackblitz.com/github/Yueyanc/README-i18n?file=README.md

## What happens and why it is incorrect

throw error

Type 'typeof import("F:/project/README-i18n/node_modules/@types/yargs/index")' has no call signatures.

more rollup detail config will print by `tsdx.config.js`

### Versions

```text

rollup-plugin-typescript2@0.27.3
rollup@1.32.1
typescript@3.9.10

```

<details>
  <summary><h4><code>rollup.config.js</code></h4>: </summary>

```js

```

</details>

<details>
  <summary><h4><code>tsconfig.json</code></h4>: </summary>

```json5

```

</details>

<details>
  <summary><h4><code>package.json</code></h4>: </summary>

```json

```

</details>

<details>
  <summary><h4>plugin output with verbosity 3</h4>: </summary>

```text

```

</details>

**Comment by Yueyanc** [comment]
Maybe tsdx has a incorrect version 3.9.10?

**Comment by agilgur5** [comment]
Please fill out the issue template in its entirety, it is there for a reason.

> Maybe tsdx has a incorrect version 3.9.10?

TSDX has not had a release [since 2020](https://github.com/jaredpalmer/tsdx/releases/tag/v0.14.1), it is unmaintained and has been for years. I was the longest solo maintainer of TSDX, that last release is by me, and I quite after experiencing [too much abuse and toxicity](https://x.com/agilgur5/status/1488621603944554496?s=20) in return for volunteering my time, particularly by the creator.

Since it's unmaintained, it also has an old version of rpt2.

In any case, this repo is for `rollup-plugin-typescript2`, not TSDX. rpt2 cannot change TSDX's versions or configuration. A reproducible bug report would have to be filed using rpt2 itself, not TSDX, and fill out the issue template in its entirety.

**Comment by agilgur5** [comment]
> ```
> Type 'typeof import("F:/project/README-i18n/node_modules/@types/yargs/index")' has no call signatures.
> ```

Based on your error and similar errors like #455, I'm guessing this is probably an import error.

You have `import yargs from 'yargs'` in ESM, but `yargs` [uses CJS](https://github.com/yargs/yargs/blob/0c95f9c79e1810cf9c8964fbf7d139009412f7e7/README.md?plain=1#L62) and so has no default export. You might want to use a namespace import like `import * as yargs from 'yargs'` or check your [`esModuleInterop`](https://www.typescriptlang.org/tsconfig#esModuleInterop) config.

In either case, that's not an rpt2 error, `tsc` will give you the same error.

**Comment by Yueyanc** [comment]
> Please fill out the issue(问题) template(模板) in its entirety(整体), it is there for a reason.
> 
> > Maybe tsdx has a incorrect version(版本) 3.9.10?
> 
> TSDX has not had a release [since 2020](https://github.com/jaredpalmer/tsdx/releases/tag/v0.14.1), it is unmaintained([网络] 服务接口与内部的) and has been for years. I was the longest solo maintainer(保持) of TSDX, that last release is by me, and I quit after experiencing [too much abuse and toxicity(毒性)](https://x.com/agilgur5/status/1488621603944554496?s=20) in return for volunteering 1000s of hours of my time, particularly by the creator(造物主).
> 
> Since it's unmaintained([网络] 服务接口与内部的), it also has an old version(版本) of rpt2.
> 
> In any case, this repo(回购) is for `rollup-plugin-typescript2`, not TSDX. rpt2 cannot change TSDX's versions(版本) or configuration(配置). A [minimal(最小)](https://stackoverflow.com/help/minimal-reproducible-example), reproducible(重现) bug report would have to be filed(提起) using rpt2 itself, not TSDX, and fill out the issue(问题) template(模板) in its entirety(整体).

thinks for your contributions to open source，I will switch to tsup，I think the issue was caused by old ts verison, not rpt2.

**Comment by Yueyanc** [comment]
> > ```
> > Type 'typeof import("F:/project/README-i18n/node_modules/@types/yargs/index")' has no call signatures.
> > ```
> 
> Based on your error(误差) and similar errors(误差) like #455, I'm guessing this is probably an import(进口) error(误差).
> 
> You have `import yargs from 'yargs'` in ESM, but `yargs` [uses CJS](https://github.com/yargs/yargs/blob/0c95f9c79e1810cf9c8964fbf7d139009412f7e7/README.md?plain=1#L62) and so has no default(默认) export. You might want to use a namespace([计]命名空间) import(进口) like `import * as yargs from 'yargs'` or check your [`esModuleInterop`](https://www.typescriptlang.org/tsconfig#esModuleInterop) config([计] 显示配置信息命令).
> 
> In either case, that's not an rpt2 error(误差), `tsc` will give you the same error(误差).

import yargs from 'yargs' not resolve this issue ,Perhaps the cause of this problem is that the version below ts4.5 is not support .d.ms?
