### ISSUE TITLE
support for pretty: true?

### ISSUE THREAD

**Issue by guidorice** [ezolenko/rollup-plugin-typescript2#47]
@ezolenko when my tsconfig has pretty: true, I can see
```
$ tsc

src/About/About.js(22,9): error TS1136: Property assignment expected.

22         ;doh
           ~
```
just curious if this plugin can report that too? Fair enough it does give the row,column info like this:

> [!] (rpt2 plugin) Error: ...path.../src/About/About.js (22,9): syntax error TS1136 Property assignment expected.
src/About/About.js

But it would be super awesome to show what tsc shows for the context. I tried adjusting the verbosity but that did not seem to do it.

**Comment by ezolenko** [comment]
Yeah, that's a good idea. Try with latest commit, should follow `pretty` option now.

**Comment by guidorice** [comment]
Thanks much! very awesome work :)
