### ISSUE TITLE
Helpers missing from output file

### ISSUE THREAD

**Issue by mohd-akram** [ezolenko/rollup-plugin-typescript2#48]
I get a `Uncaught ReferenceError: __awaiter is not defined` when compiling a file with async. I'm using the latest TypeScript (2.6.2), rollup (0.53.0) and plugin (0.9.0).

main.ts

```typescript
async function main() {
}
main();
```

rollup.config.js

```javascript
import typescript from 'rollup-plugin-typescript2';

export default {
  output: {
    format: 'iife'
  },
  plugins: [
    typescript()
  ]
}
```

tsconfig.json

```json
{
  "compilerOptions": {
    "lib": [
      "es2015"
    ]
  }
}
```

main.js:

```javascript
(function () {
'use strict';

function main() {
    return __awaiter(this, void 0, void 0, function () {
        return __generator(this, function (_a) {
            return [2 /*return*/];
        });
    });
}
main();

}());
```

**Comment by ezolenko** [comment]
Looks like you are hitting this one: https://github.com/Microsoft/TypeScript/issues/12167 -- ts treats this as global script, not a module, so it doesn't generate tslib imports.

When I add any import or export to `main.ts`, I get __awaiter/__genrator imported.

The plugin forces `"noEmitHelpers": true, "importHelpers": true` to avoid multiple copies of tslib. Let me know if you can't make your code into a module for some reason, so far I haven't seen a reason those options should not be forced.

**Comment by mohd-akram** [comment]
Did a quick test — seems like setting `importHelpers: true` alone is sufficient to prevent duplicates while fixing this problem.

**Comment by ezolenko** [comment]
If ts emits helpers in each js file (like it would do when `"noEmitHelpers": false`), then rollup will happily rename them when making a bundle, so you'd end up with __generator$1, __generator$2, etc. 

Could you post the test? Did you use 2 separate modules? Last time I checked it did that anyway, I'll try again later.

**Comment by mohd-akram** [comment]
I modified `rollup-plugin-typescript2.cjs.js` in `node_modules` to remove `noEmitHelpers: true` and didn't find any duplicates of `__awaiter`. I then removed `importHelpers: true` which caused `__awaiter$1` to be added to the output. Both modules had async functions in them.

To test with `tsc`:

`tsc main.ts --importHelpers --module es2015 --lib es2015 --moduleResolution node`

main.ts:
```typescript
import f from './module';

async function main() {
  await f();
}
main();
```

module.ts:
```typescript
async function f() {
}
export default f;
```

main.js:
```javascript
import * as tslib_1 from "tslib";
import f from './module';
function main() {
    return tslib_1.__awaiter(this, void 0, void 0, function () {
        return tslib_1.__generator(this, function (_a) {
            switch (_a.label) {
                case 0: return [4 /*yield*/, f()];
                case 1:
                    _a.sent();
                    return [2 /*return*/];
            }
        });
    });
}
main();
```

module.js
```javascript
import * as tslib_1 from "tslib";
function f() {
    return tslib_1.__awaiter(this, void 0, void 0, function () {
        return tslib_1.__generator(this, function (_a) {
            return [2 /*return*/];
        });
    });
}
export default f;
```

**Comment by ezolenko** [comment]
Thanks, I'll test on a few versions of typescript and remove `noEmitHelpers` override if it works everywhere.

**Comment by ezolenko** [comment]
This is in 0.10.0
