### ISSUE TITLE
Emit compiled js/map too?

### ISSUE THREAD

**Issue by ericanderson** [ezolenko/rollup-plugin-typescript2#49]
In my builds, I would like to write the compiled source to disk. That way you can get the rolledup version by default but one could require just what you want in certain scenarios

**Comment by ezolenko** [comment]
Best way to do that would be running tsc on the side (don't forget to set `outDir` in tsconfig). Plugin uses most of the options from tsconfig (check readme for list of options it changes), so you will end up with the same code, minus any changes other rollup plugins do.

**Comment by agilgur5** [comment]
You can use Rollup's [`preserveModules`](https://rollupjs.org/guide/en/#outputpreservemodules) feature for this.
Although it won't be bundled at all that way.

If you know what files are going to be used ahead-of-time (i.e. you've defined a public API), you can also use Rollup's [multi-entry feature](https://rollupjs.org/guide/en/#input) instead by specifying multiple `input`s as an array or object.
Note that you may run into #136 that way, but there are workarounds for that.
