### ISSUE TITLE
Override tsconfig.json option 'declarationDir' fail.

### ISSUE THREAD

**Issue by zheeeng** [ezolenko/rollup-plugin-typescript2#52]
#### What happens and why it is wrong
Typescript compile option doesn't allow set `declaration: false` and `declarationDir` at same time. 

```
options error TS5052 Option 'declarationDir' cannot be specified without specifying option 'declaration'.
```

But according to https://github.com/Microsoft/TypeScript/issues/14184, setting with `declarationDir: null` and `declaration: false` is able to cancel emitting type files.

Unfortunately, after setting override `declarationDir: null`, `declaration: false` and `useTsconfigDeclarationDir:false`, in lvl 3 verbosity, terminal reports that declarationDir in parsed tsconfig is current project path. The expected `declarationDir` should be `null`.

#### Versions
- typescript: 2.6.2
- rollup: 0.55.1
- rollup-plugin-typescript2: 0.10.0

#### rollup.config.js

```ts
import typescript from 'rollup-plugin-typescript2'
import camelCase from 'camel-case'

const pkg = require('./package.json')

export default {
  input: 'src/index.ts',
  output: {
    file: pkg.main,
    format: 'umd',
    name: camelCase(pkg.name),
  },
  watch: {
    include: 'src/**',
  },
  plugins: [
    typescript({
      verbosity: 3,
      tsconfigOverride: {
        compilerOptions: {
          target: 'es5',
          declaration: false,
          declarationDir: null,
        },
      },
      useTsconfigDeclarationDir: true,
    }),
  ],
}
```

#### tsconfig.json

```json
{
  "compilerOptions": {
    "module": "esnext",
    "target": "es6",
    "lib": ["es6", "es7", "es2017", "dom"],
    "moduleResolution": "node",
    "declarationDir": "dist/types",
    "declaration": true,
    "allowSyntheticDefaultImports": true,
  },
  "include": [
    "src/*"
  ]
}
```

**Comment by ezolenko** [comment]
With your options, I end up passing `declaration: false, declarationDir: null` to `typescript.parseJsonConfigFileContent()`, and then typescript itself replaces `declarationDir` with cwd. See values in `raw` below.

Either this is regression in typescript, or that code path was never fixed. I'll open a case with them.

```
rpt2: parsed tsconfig: {
    "options": {
        "module": 5,
        "target": 1,
        "noImplicitAny": true,
        "sourceMap": true,
        "noUnusedParameters": true,
        "noUnusedLocals": true,
        "noImplicitThis": true,
        "diagnostics": true,
        "listFiles": true,
        "pretty": true,
        "moduleResolution": 2,
        "noEmitOnError": false,
        "strictNullChecks": true,
        "forceConsistentCasingInFileNames": true,
        "noImplicitReturns": true,
        "declaration": false,
        "declarationDir": "d:/source/scr/rollup-plugin-typescript2",
        "outDir": "d:\\source\\scr\\rollup-plugin-typescript2",
        "noEmitHelpers": false,
        "importHelpers": true,
        "noResolve": false,
        "noEmit": false,
        "configFilePath": "d:\\source\\scr\\rollup-plugin-typescript2/tsconfig.json"
    },
    "raw": {
        "compilerOptions": {
            "module": "es6",
            "target": "es5",
            "noImplicitAny": true,
            "sourceMap": true,
            "noUnusedParameters": true,
            "noUnusedLocals": true,
            "noImplicitThis": true,
            "diagnostics": true,
            "listFiles": true,
            "pretty": true,
            "moduleResolution": "node",
            "noEmitOnError": false,
            "strictNullChecks": true,
            "forceConsistentCasingInFileNames": true,
            "noImplicitReturns": true,
            "declaration": false,
            "declarationDir": null,
            "outDir": "./build"
        },
        "include": [
            "src/**/*.ts"
        ]
    }
}
```

**Comment by zheeeng** [comment]
Thx very much. As a temporary solution, can we eliminate the declarationDir option in parsed configs if we gonna cancel the declarationDir by setting it as `null`. After all, this signature of `declarationDir ` is `string`, set `null` is also inappropriate.

**Comment by ezolenko** [comment]
Yeah, there is a couple of ways I can implement a workaround so that 14184 actually applies. I'm not even sure if that workaround is not the intended way the API should be used anyway...

**Comment by zheeeng** [comment]
Just a guess, maybe typescript engine verifying options declarationDir and declaration options before config parsing. Maybe the PWD is the default value to feed to the compiler, the implementation of rollup-plugin-typescript2 getting parsed config then feed it to typescript be blocked by config verifying. I have tried to dig out whether if or not but the mass code base fails me.

**Comment by ezolenko** [comment]
Ok, I put a minimal fix in for now, try on master.

**Comment by ezolenko** [comment]
Should be in 0.11.0 now
