### ISSUE TITLE
Ability to specify default tsconfig options

### ISSUE THREAD

**Issue by freeman** [ezolenko/rollup-plugin-typescript2#53]
Hello,

I am trying to make [microbundle](https://github.com/developit/microbundle) switch to using this plugin for typescript compilation (see developit/microbundle#71). 

As part of that change (and to keep with the #0CJS approach of microbundle) we'd like to generate declaration by default when the user does not provide a tsconfig.json. However if the user explicitly does not want declaration files to be generated, we should respect that.

Currently there is only a way to override tsconfig options with `tsconfigOverride`. Would you be open to adding a `tsconfigDefaults` option that would be overridden by explicit `tsconfig.json` values ?

**Comment by ezolenko** [comment]
Sure, sounds reasonable and simple enough, although I probably have too many tsconfig-related options already. :)

**Comment by ezolenko** [comment]
Check if `tsconfigDefaults` branch works for you.

**Comment by freeman** [comment]
thanks, reading the commit it looks perfect. I'll try to test it by tomorrow.

**Comment by freeman** [comment]
Just tested in microbundle and it works perfectly !

**Comment by ezolenko** [comment]
Cool, thanks. I'll merge and release in a day or two.

**Comment by ezolenko** [comment]
Should be in 0.11.0 now
