### ISSUE TITLE
support custom transformer

### ISSUE THREAD

**Issue by foisonocean** [ezolenko/rollup-plugin-typescript2#56]
Could you support `getCustomTransformers` like [ts-loader](https://github.com/TypeStrong/ts-loader) does?

**Comment by ezolenko** [comment]
Actually I added them a while ago, just never got around to testing them properly. Could you try `transformers` branch and check if it actually works? I just brought it up to speed with master, 

If you get a self-contained test example that would be perfect too. 

I'll merge it into master eventually, once I come up with a few test cases.

**Comment by ezolenko** [comment]
Merged branch to master, it is largely untested, but shouldn't interfere with builds that don't use it.

**Comment by ezolenko** [comment]
In 0.14.0 now
