### ISSUE TITLE
Can't use this plugin with rollup watch

### ISSUE THREAD

**Issue by sateffen** [ezolenko/rollup-plugin-typescript2#6]
When using rollup in watch mode (*rollup --watch*) this plugin will allow the first build but no following one. Each time I change a file it tells me:

> bundling...
> �   ENOENT: no such file or directory, open '.../.cache/rollup-plugin-typescript2/38c1142761dfd23593156a9ffdbc77dede334f14/code/cache_/ff351ee7256cf7
> 98f62b4f46f09ac4534010406c'
> src/gl/gl.tsx

The file does not exist, but I guess it's the hash of the new file. In this scenario, I changed some code in *src/gl/gl.tsx*, which lead to the rebuild.

Stopping *rollup --watch* and rerunning it generates a valid bundle, but every following build afterwards are breaking as well.

I'm using rollup 0.41.5, rollup-plugin-typescript2 0.3.0 and node 6.9.1

**Comment by ezolenko** [comment]
I got over that one in the `watch` branch somewhat. But  there is a bigger problem -- rollup-watch only looks at modules that rollup sees, and that excludes any type-only imports and all d.ts files. Basically every time ts will not generate a `require` call, rollup will not see that file. So you can mutilate your interface definitions all you want, rollup won't try to transpile that file or anything that imports it.

**Comment by sateffen** [comment]
In my opinion that's ok, if it's pointed out in the documentation.

the d.ts files are meta information, that append the usual information. It's not that cool, that the d.ts changes get ignored, but it's actually something I personally could work with. The most important thing is to tell it straight forward in the documentation.

Maybe there'll be an option for this in the future, or the guys from rollup know a possible solution?

**Comment by ezolenko** [comment]
Could you try with master branch to see if it behaves reasonably?

**Comment by brandom** [comment]
I just tried master with --watch and I get `Cannot read property 'length' of undefined`.

Compiles correctly but with above error on file change on `0.3.0`.

**Comment by ezolenko** [comment]
@brandom: what's your rollup config look like? I'm trying to detect watch mode by counting targets, maybe you don't have any defined...

**Comment by brandom** [comment]
Rollup config
```js
export default {
  format: "iife",
  plugins: [
    typescript({
      typescript: require("typescript")
    }),
    node({
      jsnext: true,
      main: true,
      browser: true
    }),
    commonjs(),
    babel({
      babelrc: false,
      exclude: "node_modules/**",
      presets: [
        "es2017",
        "es2016",
        [
          "es2015",
          {
            modules: false
          }
        ]
      ],
      plugins: ["lodash", "external-helpers"]
    }),
    uglify({}, minify)
  ],
  external: []
};
```
And then spawning --watch from within gulp
```js
function devBundle(cb) {
  let rollup = spawn("./node_modules/.bin/rollup", [
    "-c",
    "rollup.config.dev.js",
    "--watch",
    "--input",
    "./components/app/App.ts",
    "--output",
    `./dist/js/${jsFileName}`
  ]);
  rollup.stderr.on("data", data => rollupLog(data));
  return rollup;
}
```

**Comment by ezolenko** [comment]
Ok, your config should work with master now I think (or at least get to the next bug :)).

I'm still seeing weird ignoring of bad edits in index file (while correct errors show up for edits in other files), so this is not quite ready for npm release.

**Comment by brandom** [comment]
@ezolenko Thanks, I will try to find some time to do some additional testing this weekend.

**Comment by ezolenko** [comment]
Ok, this is in 0.4.0 now, seems to work aside from #7.
