### ISSUE TITLE
noEmitOnError: false seems to be ignored

### ISSUE THREAD

**Issue by TobiaszCudnik** [ezolenko/rollup-plugin-typescript2#62]
#### What happens and why it is wrong

Semantic errors result in no emit. Adding `noEmitOnError: false` doesn't help.

Error:
```
[!] (rpt2 plugin) Error: /Users/.....ts(1286,2): semantic error TS2300 Duplicate identifier 'on'.
```

#### Versions
- typescript: 2.7.2
- rollup: 0.51.8
- rollup-plugin-typescript2: 0.11.1

#### rollup.config.js

```
config.plugins[0] = typescript({
  target: 'es6',
  isolatedModules: true,
  module: 'es6',
  typescript: tsc,
  noEmitOnError: false
})
```

#### tsconfig.json

```
{
    "compilerOptions": {
        "target": "es6",
        "module": "commonjs",
        "declaration": true,
        "removeComments": false,
        "lib": ["es2017", "dom"],
        "sourceMap": true,
        "strict": true,
        "suppressImplicitAnyIndexErrors": true,
        "preserveConstEnums": true,
        "outDir": "build"
    },
    "include": [
        "src/**/*"
    ]
}
```

How can I force it to pass through? `ts-ignore` all of them? Fixing those errors is not an option at the moment. Thanks.

**Comment by ezolenko** [comment]
There is `abortOnError` option, set to true by default. You can either set it to `false` and ignore printed errors, or you can set `check` to false and avoid all checking entirely.

Also take a look at readme for options the plugin takes, you can't pass in tsconfig options directly like you could in the original.

**Comment by TobiaszCudnik** [comment]
Thanks! That's exactly what I was looking for, `check: false` did the job in my case. I guess I was going through the readme too quickly... ;)
