### ISSUE TITLE
rollup helpers (tslib) will included always 

### ISSUE THREAD

**Issue by RueDeRennes** [ezolenko/rollup-plugin-typescript2#63]
the tslib will always included in my transpiled js bundles.
is any way to turn it off?

in my usecase, i would include the tsLib in the index.html and not as boilerplate in every js file.
thx

**** tsconfig.json

    "compilerOptions": {
        "noEmitHelpers": true,
        "importHelpers": false,
        "outDir": "./dist/js",
        "rootDir": "./src",
        "declarationDir": "./dist/types",
        "declaration": true,
        "sourceMap": true,
        "lib": [
            "es6",
            "dom"
        ]
    },

****

**Comment by ezolenko** [comment]
Try telling rollup that tslib is external module (in `external` in rollup config)

**Comment by RueDeRennes** [comment]
it work, but it seems to be a smelly workaround 👎

**Comment by youngjuning** [comment]
use `rollup-plugin-node-externals`
