### ISSUE TITLE
Question: How to specify declaration dir to output files directly in build folder?

### ISSUE THREAD

**Issue by szimek** [ezolenko/rollup-plugin-typescript2#64]
#### What happens and why it is wrong
I'm rewriting my library (https://github.com/szimek/signature_pad) to TypeScript - this is the first time I'm working with this language. I've specified `declarationDir: 'dist/types'` in `tsconfig.js` and set `useTsconfigDeclarationDir: true`. However, after building the library, the declaration files end up in `dist/types/src`. Is it supposed to be like this? If not, how can I change it, so that they end up directly in `dist/types`?

#### Versions
- typescript: 2.7.2
- rollup: 0.56.5
- rollup-plugin-typescript2: 0.12.0

#### rollup.config.js
https://github.com/szimek/signature_pad/blob/typescript/rollup.config.js

#### tsconfig.json
https://github.com/szimek/signature_pad/blob/typescript/tsconfig.json

#### package.json
https://github.com/szimek/signature_pad/blob/typescript/package.json

**Comment by ezolenko** [comment]
Yeah, typescript mirrors your project structure considering project root to be location of `tsconfig.json` -- plugin uses unmodified d.ts path to write out declarations when `useTsconfigDeclarationDir` is used.

If you don't use `useTsconfigDeclarationDir`, declarations will be dumped together with rollup output.

Either way should work if you set correct `types` property in package.json, but neither is very clean in your case I guess...

**Comment by szimek** [comment]
@ezolenko Thanks!

> If you don't use `useTsconfigDeclarationDir`, declarations will be dumped together with rollup output.

That's good enough ;)

**Comment by agilgur5** [comment]
> typescript mirrors your project structure

You can set [`rootDir`](https://www.typescriptlang.org/tsconfig#rootDir) in your `tsconfig.json` to influence this behavior.
See https://github.com/ezolenko/rollup-plugin-typescript2/issues/275#issuecomment-1107881058 for more details.

That issue effectively duplicates this one, but has gotten a lot more activity

**Comment by wakaztahir** [comment]
Please reopen this issue
