### ISSUE TITLE
The support of browser field spec

### ISSUE THREAD

**Issue by katyo** [ezolenko/rollup-plugin-typescript2#67]
#### What happens and why it is wrong

I imported a module which has different typing for NodeJS and browsers.
It uses [this specification](https://github.com/defunctzombie/package-browser-field-spec) to select right js. It works fine for .js but not for .d.ts.
I cannot compile my code for browser because the server-side typings still is used.
I don't sure what the issue is related to this plugin.
May be actually this problem sits in 'rollup-plugin-node-resolve'.

#### Versions
- typescript: 2.6.2
- rollup: 0.57.1
- rollup-plugin-typescript2: 0.12.0

#### rollup.config.js

```javascript
import { join } from 'path';
import nodeResolve from 'rollup-plugin-node-resolve';
import sourceMaps from 'rollup-plugin-sourcemaps';
import typescript from 'rollup-plugin-typescript2';

export default {
    input: `src/client.ts`,
    output: {
        file: 'dist/client.js',
        format: 'cjs',
        sourcemap: true
    },
    plugins: [
        typescript({
            tsconfigOverride: {
                compilerOptions: {
                    module: 'es6'
                }
            }
        }),
        nodeResolve({
            browser: true // use browser field of package.json to resolve
        }),
        sourceMaps(),
    ],
}
```

#### tsconfig.json

```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "noImplicitAny": true,
    "sourceMap": true,
    "strictNullChecks": true,
    "declaration": false,
    "removeComments": false,
    "noUnusedLocals": true,
    "importHelpers": true,
    "lib": [
      "dom",
      "es5",
      "es2015.core"
    ]
  }
}
```

**Comment by ezolenko** [comment]
Which package did you import? How does it specify different typings for different targets? (didn't find anything about typings in the spec)

**Comment by ezolenko** [comment]
See #66, you probably have the same problem -- put `nodeResolve` before `typescript`.
