### ISSUE TITLE
when tsconfig specifies `inlineSourceMap: true` then no sourcemap is generated

### ISSUE THREAD

**Issue by TheRealPiotrP** [ezolenko/rollup-plugin-typescript2#71]
#### What happens and why it is wrong
in my tsconfig.json I have `inlineSourceMap: true`. I also configured rollup to use `sourcemap: 'inline'`. Rollup builds occur without issue, but my resultant .js file contained an inline sourcemap for non-ts assets only. After much experimentation I found that I can re-enable sourceMaps for TS with the following configuration:
```
    typescript({
        tsconfigOverride: {
            compilerOptions: {
                sourceMap: true,
                inlineSourceMap: false,
```

This is not intuitive. I've already expressed that I want sourcemaps, and that I want rollup to generate an inline sourcemap. The plugin should ideally respect the inlineSourceMap option in tsconfig.json. If this is not feasible [likely because it's hard to scrape out inline source maps from tsc output] then there should be an error displayed and rollup should fail, telling the user they must disable inlineSourceMap and enable sourceMap in their typescript overrides.

#### Environment 
Not relevant

#### Versions
- typescript: 2.7.2
- rollup: 0.57.1
- rollup-plugin-typescript2: 0.12.0

#### rollup.config.js
I'm only including the relevant portion.

Original:
```
    typescript({
        tsconfigOverride: {
            compilerOptions: {
                module: "ES2015"
            }
        }
    }),
```

With Workaround:
```
    typescript({
        tsconfigOverride: {
            compilerOptions: {
                sourceMap: true,
                inlineSourceMap: false,
                module: "ES2015"
            }
        }
    }),
```

#### tsconfig.json
```
{
	"compilerOptions": {
		...
		"inlineSourceMap": true,
		...
	},
        ...
}
```

**Comment by TheRealPiotrP** [comment]
To be clear, I have a reasonable workaround. I'd only like it to be less difficult to discover. At a minimum, this issue should help others find it...

**Comment by lolgesten** [comment]
My use case is developer mode with rollup:

* rollup-plugin-typescript2 + rollup `format: 'es'` and `preserveModules: false`
* use `<script type="module"` to load modules from page.

With `inlineSourceMaps: true` I can get my typescript source also in this dev mode, but the force setting to `false` means I need to use the OP override.

@ezolenko care to elaborate why forcing `inlineSourceMap` to `false` would be wanted behavior?

**Comment by agilgur5** [comment]
@lolgesten Rollup [handles sourcemaps](https://rollupjs.org/guide/en/#source-code-transformations) (as other plugins on-chain can further change them), so it makes more sense that related `tsconfig` options are forced/ignored and the Rollup config is respected instead.

Does setting [`sourcemap: "inline"`](https://rollupjs.org/guide/en/#outputsourcemap) (as mentioned by OP) handle your use-case?

**Comment by lolgesten** [comment]
@agilgur5 sorry i don't have my test setup anymore. We decided to go with esbuild in the end.
