### ISSUE TITLE
Export default function generates unconsumable index.d.ts

### ISSUE THREAD

**Issue by IlyaSemenov** [ezolenko/rollup-plugin-typescript2#77]
#### What happens and why it is wrong

Rolling up a module with a default function export doesn't generate a consumable `index.d.ts` (see example below). I realise that it's probably not rollup-plugin-typescript2's direct fault, but still it prevents automatically generating publishable packages.

I can see that others typically use `namespace foo {}` workaround ([example](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/koa-logger/index.d.ts)), but this is not happening with rollup-plugin-typescript2.

#### Steps to reproduce

Rollup a very simple `src/index.ts` which exports a default function:

```ts
export default function foo() {
	console.log("Hello, world!")
}
```

This emits the following bundle:

```js
'use strict';

function foo() {
    console.log("Hello, world!");
}

module.exports = foo;
//# sourceMappingURL=bundle.cjs.js.map
```

and `dist/index.d.ts`:

```d.ts
export default function foo(): void;
```

Now, import it from an another file `test.ts`:

```ts
import foo from '.'
foo()
```

this will fail:

```
foo()
   ^
TypeError: _1.default is not a function
```

Change import to `* as foo`:

```ts
import * as foo from '.'
foo()
```

This will fail, too:

```
test.ts (2,1): Cannot invoke an expression whose type lacks a call signature. Type 'typeof "/Users/semenov/tmp/rollup/lib/dist/index"' has no compatible call signatures. (2349)
```

Now change `index.d.ts` manually to this:

```d.ts
declare function foo(): void;
declare namespace foo {}
export = foo
```

and finally:

```console
$ npm run test
Hello, world!
```

Note that `"allowSyntheticDefaultImports": true` has no effect on the behaviour (I conducted 8 experiments: 2 types of import statement, enable/disable namespace hack, enable/disable allowSyntheticDefaultImports).

#### Versions
- typescript: 2.8.3
- rollup: 0.58.2
- rollup-plugin-typescript2: 0.13.0

#### rollup.config.js

```js
import typescript from 'rollup-plugin-typescript2'

export default {
	input: 'src/index.ts',
	output: {
		file: 'dist/bundle.cjs.js',
		format: 'cjs',
		sourcemap: true,
	},
	plugins: [
		typescript(),
	],
}
```

#### tsconfig.json

```json
{
	"compilerOptions": {
		"declaration": true
	}
}
```

#### package.json

```json
{
  "main": "dist/bundle.cjs.js",
  "types": "dist/index.d.ts",
  "scripts": {
    "build": "rollup -c",
    "test": "ts-node test"
  },
  "devDependencies": {
    "rollup": "^0.58.2",
    "rollup-plugin-typescript2": "^0.13.0",
    "ts-node": "^6.0.2",
    "typescript": "^2.8.3"
  },
  "dependencies": {}
}
```

**Comment by ezolenko** [comment]
Similar to #20 (there is also a workaround there). I haven't found a correct way of solving it, looks like there is fundamental incompatibility between expectations of various module loaders regarding default exports.

**Comment by IlyaSemenov** [comment]
OK, I figured that the workaround is to use *both* `esModuleInterop` and `allowSyntheticDefaultImports`. This allows to import the exported function with the auto generated `index.d.ts`.

This is very strange as [the documentation](https://www.typescriptlang.org/docs/handbook/compiler-options.html) clearly says that `esModuleInterop` automatically enables `allowSyntheticDefaultImports`. This doesn't happen to me. Also, the library being rolled up suffers from the same issue, but I will not pollute the bug tracker and will rather open a separate issue for it.

I'll close this one as I understand it's not really a rollup plugin problem.
