### ISSUE TITLE
check: false isn't working in watch mode

### ISSUE THREAD

**Issue by marijnh** [ezolenko/rollup-plugin-typescript2#82]
#### What happens and why it is wrong

When I configure the plugin to not check, but run rollup with `-w` checking seems to still be taking place (I get errors, and the build is no faster than with `check: true`).

#### Versions

Version 0.14.0, TypeScript 2.8.4, Rollup 0.56.5.

#### rollup.config.js

```
import typescript from "rollup-plugin-typescript2";
import commonjs from "rollup-plugin-commonjs"

export default {
  input: "./view/test/test.ts",
  output: {
    format: "umd",
    file: "./view/test/test_built.js",
    sourcemap: false
  },
  plugins: [
    typescript({
      check: false,
      tsconfigOverride: {
        compilerOptions: {lib: ["ES6", "dom"], sourceMap: false, target: "es5", strict: false},
        include: null
      }
    }),
    commonjs()
  ]
}
```

#### tsconfig.json

```
{
  "compilerOptions": {
    "lib": ["ES6", "dom"],
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "sourceMap": true,
    "strict": true,
    "target": "es5"
  },
  "include": ["*/src/*.ts"]
}
```

**Comment by ezolenko** [comment]
Forgot to check that option in watch mode... :) Could you check if master works for you? @marijnh 

I'll do a release sometime this week.

**Comment by marijnh** [comment]
Yes! Thanks for the fix. (For some reason, it's still not nearly as fast as rollup-typescript, but clearly better than before.)
