### ISSUE TITLE
Plugin is producing invalid `*.d.ts`

### ISSUE THREAD

**Issue by killtheliterate** [ezolenko/rollup-plugin-typescript2#84]
#### What happens and why it is wrong

`rollup-plugin-typescript2` is generating `*.d.ts` file that is not valid TypeScript:

`export declare function deferredAction<T extends StdOut>(saga: Saga<T, Action>, io: T): (action: DeferredAction) => IterableIterator<SetContextEffect<any> | etc..| import("../node_modules/redux-saga/effects").Effect[]>;`

Notice the `import("../node_modules/redux-saga/effects").Effect[]` that is trying to be used as a type parameter.

I've run `tsc` directly, which behaves as expected (aside from dumping all the built files in the wrong spot).

This is for a library I'm working on, so the source (and the branch) is [here](https://github.com/killtheliterate/redux-saga-try-catch/tree/rollup-weird)

#### Versions
- typescript: `^2.9.1`
- rollup: `^0.59.4`
- rollup-plugin-typescript2: `^0.14.0`

#### rollup.config.js

```
import typescript from 'rollup-plugin-typescript2'

const baseConfig = {
  plugins: [ typescript() ],

  input: 'src/index.ts',

  external: [
    'redux',
    'redux-saga',
    'redux-saga/effects'
  ]
}

const esConfig = Object.assign(
  {},
  baseConfig,
  {
    output: {
      exports: 'named',
      file: 'dist/es/index.js',
      format: 'es'
    }
  }
)

const cjsConfig = Object.assign(
  {},
  baseConfig,
  {
    output: {
      exports: 'named',
      file: 'dist/cjs/index.js',
      format: 'cjs'
    }
  }
)

export default [
  cjsConfig,
  esConfig
]
```

#### tsconfig.json

```
{
  "exclude": [
    "**/*.test.ts",
    "node_modules"
  ],

  "include": [ "src/**/*.ts" ],

  "compilerOptions": {
    "baseUrl": "./",
    "declaration": true,
    "downlevelIteration": true,
    "jsx": "react",
    "module": "esnext",
    "moduleResolution": "node",
    "noUnusedParameters": true,
    "removeComments": false,
    "sourceMap": true,
    "strict": true,
    "target": "es5",

    "lib": [
      "dom",
      "esnext"
    ],

    "paths": {
      "@/*": ["src/*"]
    },

    "plugins": [
      { "name": "tslint-language-service"}
    ]
  }
}
```

#### package.json

```
{
  scripts: { "build": "rm -rf dist && npx rollup -c" }
}
```

#### plugin output with verbosity 3

I don't see anything that looks relevant, though I can amend this.

**Comment by killtheliterate** [comment]
I've just tried the same with `webpack`, and it produces the same issue—though `tsc` does not. Something strange in my implementation, I guess.

**Comment by killtheliterate** [comment]
@ezolenko took your advice and ran `./node_modules/.bin/tsc`, which *does* reproduce the problem—hmm, something got weird in TypeScript `2.9.1` — the global `tsc` is `2.8.1`.

I factored out those typings, as they were kind of borked, but still weird.

**Comment by ezolenko** [comment]
You might want to search for similar issues or open one in typescript proper.

**Comment by killtheliterate** [comment]
@ezolenko yep yep, will do some digging—close this, will post a link if I do open an issue.

**Comment by mnewmedia** [comment]
@killtheliterate Got the same problem, did you find a solution?

**Comment by mnewmedia** [comment]
Nevermind but for others i had the error because of 
```
  public change$ = this._subjects.change.asObservable();
```
but changing it to:
```
  public change$: Observable<any> = this._subjects.change.asObservable();
```

fixed the problem.

**Comment by agilgur5** [comment]
Not sure what the root TS issue was here, but updating (local) TS should fix this if anyone comes up on it.

Also there was a similar issue with TS 3.7 in #276 which does link to an upstream TS issue.
