### ISSUE TITLE
Can't unset sourceRoot

### ISSUE THREAD

**Issue by nolazybits** [ezolenko/rollup-plugin-typescript2#99]
#### What happens and why it is wrong

I have the following error
`rpt2: options error TS5051 Option 'sourceRoot can only be used when either option '--inlineSourceMap' or option '--sourceMap' is provided.`

and config
```
    plugins: [
        typescript({
            tsconfigOverride: {
                compilerOptions: {
                    sourceRoot: null
                }
            }
        })
    ]
```

I was expecting sourceRoot to not be set anymore and the error/warning to disappear.

#### Versions
- typescript: 2.9.2
- rollup: 0.62.0
- rollup-plugin-typescript2: 0.15.1

**Comment by ezolenko** [comment]
This is because inlineSourceMap gets forcefully unset leaving sourceRoot dangling.

Should be fixed in master now -- you won't need to unset sourceRoot, but you still won't be able to unset random options.

**Comment by nolazybits** [comment]
Wow thank you so much for being that much reactive :+1:
I'll report back on Monday.

Thanks again!
